/* HomeTikki · KANTO — Round 2 area-fusion layer.
   Ward-level dossiers + per-station character. EVERY field carries a tier:
   V verified pull · S souba benchmark · P proxy (formula stated) ·
   E editorial (typical/known — verify) · Q adapter queued.
   Numbers we could not verify this round are NOT invented — they are
   approximations labeled E with the adapter that will replace them (Q).

   quiet: night-quiet 1–5, tier P. Formula: base 3 · −1 express tracks race
   past a local-only platform · −1 trunk-road (Route 15 / Route 1), freight,
   industrial or nightlife adjacency · +1 temple/canal/back-grid insulation.
   air: band 1 (inland cleaner) / 2 (urban-core NO₂ typical) / 3 (industrial
   bayside — watch PM on still winter days), tier P — Soramame adapter queued.
   people: foreign-resident share ≈, age & balance — tier E, e-Stat queued.
   crime: qualitative ward pattern — tier E, MPD / pref-police open data queued. */

const AREA_WARD = {
  chuo: {
    crime:  { tier:'E', en:'Low violent crime; property theft clusters at the Ginza-side nightlife edge; bike theft near stations.', ja:'凶悪犯罪は少ない。銀座側の夜間エリアで窃盗、駅前で自転車盗が中心。' },
    air:    { tier:'P', band:2, en:'urban-core NO₂ typical; no industrial load', ja:'都心型NO₂。工業負荷なし' },
    people: { tier:'E', foreign:'≈5%', en:'median age ≈44 · new-tower families & DINKs · slight female excess · foreign residents ≈5%', ja:'年齢中央値≈44 · タワー型ファミリー/DINKs · 女性やや多 · 外国人≈5%' },
    uber:   { tier:'E', full:true },
    grocery:{ tier:'E', en:'Maruetsu Petit grid + Nihombashi depachika (Mitsukoshi/Takashimaya) for the good stuff', ja:'マルエツプチ網＋日本橋デパ地下' },
    coffee: { tier:'E', en:'kissaten heritage + third-wave spillover from Ginza', ja:'喫茶店文化＋銀座系ロースター' },
  },
  minato: {
    crime:  { tier:'E', en:'Low overall; Shimbashi drink district generates the ward\'s petty-crime column; residential blocks calm.', ja:'全体に低い。新橋の飲み屋街で軽犯罪、住宅地は静穏。' },
    air:    { tier:'P', band:2, en:'urban-core typical; heavy road frontage on Sakurada-dōri/Daiichi-Keihin', ja:'都心型。桜田通り・第一京浜沿いは車道負荷' },
    people: { tier:'E', foreign:'≈8%', en:'corridor\'s most international ward — embassies, intl schools · median ≈44', ja:'沿線で最も国際的 — 大使館・インター校 · 中央値≈44' },
    uber:   { tier:'E', full:true },
    grocery:{ tier:'E', en:'Maruetsu/mybasket infill; Shinagawa ecute for commute-home shopping', ja:'マルエツ/まいばすけっと＋品川エキュート' },
    coffee: { tier:'E', en:'office-tower espresso + Zōjō-ji temple-side kissa', ja:'オフィス系エスプレッソ＋増上寺門前喫茶' },
  },
  shinagawa: {
    crime:  { tier:'E', en:'Quiet residential profile; shukuba lanes well-watched; station-front bike theft is the main line item.', ja:'住宅型で静か。旧宿場は目が行き届く。駅前自転車盗が主。' },
    air:    { tier:'P', band:2, en:'Daiichi-Keihin frontage carries the load; canal back-grids noticeably calmer', ja:'第一京浜沿い中心。運河裏手は穏やか' },
    people: { tier:'E', foreign:'≈4%', en:'median ≈45 · mixed families + single professionals · balanced', ja:'中央値≈45 · ファミリー＋単身 · 均衡' },
    uber:   { tier:'E', full:true },
    grocery:{ tier:'E', en:'shōtengai greengrocers + Life/Maruetsu; Ōimachi mega-stores one stop west', ja:'商店街青果＋ライフ/マルエツ。大井町の大型店も近い' },
    coffee: { tier:'E', en:'Tennōzu waterfront roasters 8′ from Kitashinagawa', ja:'天王洲のロースター（北品川徒歩8分）' },
  },
  ota: {
    crime:  { tier:'E', en:'Low; Kamata east-exit nightlife edge carries the ward\'s numbers; shōtengai blocks are village-calm.', ja:'低い。蒲田東口の夜エリアに集中、商店街ブロックは平穏。' },
    air:    { tier:'P', band:2, en:'Route 15 + Haneda road traffic; back grids fine; flight paths mostly seaward', ja:'国道15号＋空港交通。裏手は良好。飛行経路は海側中心' },
    people: { tier:'E', foreign:'≈4%', en:'median ≈46 · Kamata pockets genuinely multicultural · balanced-to-male', ja:'中央値≈46 · 蒲田は多文化 · やや男性多' },
    uber:   { tier:'E', full:true },
    grocery:{ tier:'E', en:'OK Store discount kingdom + shōtengai produce — corridor\'s cheapest basket', ja:'オーケーストア＋商店街 — 沿線最安の買い物カゴ' },
    coffee: { tier:'E', en:'proper old-school kissa culture, morning sets everywhere', ja:'正統派喫茶店文化・モーニング常備' },
  },
  kawasaki: {
    crime:  { tier:'E', en:'Highest on this corridor: station-east entertainment district drives it; Daishi/riverside daily-life areas are ordinary-calm. Read block by block.', ja:'沿線では最も高い（駅東側歓楽街由来）。大師・川沿い生活圏は普通に平穏。ブロック単位で判断を。' },
    air:    { tier:'P', band:3, en:'industrial belt — watch PM on still winter days; improving decade over decade', ja:'工業地帯 — 冬の無風日はPM注意。長期的には改善' },
    people: { tier:'E', foreign:'≈6–7%', en:'most international after Minato · young workforce, male excess · median ≈45', ja:'港区に次ぐ国際性 · 若い労働人口・男性多 · 中央値≈45' },
    uber:   { tier:'E', full:true },
    grocery:{ tier:'E', en:'station mega-retail (Atre/More\'s) + Daishi shōtengai; cheap and complete', ja:'駅前大型＋大師商店街。安くて揃う' },
    coffee: { tier:'E', en:'La Cittadella espresso + shōwa kissa survivors', ja:'ラ チッタデッラ系＋昭和喫茶' },
  },
  tsurumi: {
    crime:  { tier:'E', en:'Moderate-low; industrial edges dark at night but residential cores steady.', ja:'中〜低。工業縁辺は夜暗いが住宅核は安定。' },
    air:    { tier:'P', band:3, en:'bayside industrial adjacency — same PM caveat as Kawasaki, milder inland', ja:'臨海工業隣接 — 川崎同様PM注意、内陸側は軽い' },
    people: { tier:'E', foreign:'≈5%', en:'historic Okinawan + Latin-American community around Nakadōri — best food payoff on the corridor · median ≈46', ja:'仲通りの沖縄・中南米コミュニティ · 中央値≈46' },
    uber:   { tier:'E', full:true, thin:true },
    grocery:{ tier:'E', en:'shōtengai + Okinawan grocers (the miso, the umibudō) + OK Store', ja:'商店街＋沖縄食材店＋オーケー' },
    coffee: { tier:'E', en:'Okinawan cafés — zenzai in summer, sātā andagī always', ja:'沖縄カフェ — ぜんざい・サーターアンダギー' },
  },
  kanagawaku: {
    crime:  { tier:'E', en:'Low; quiet grid between two terminals; port-side lanes empty late.', ja:'低い。二つのターミナルに挟まれた静かな住宅網。' },
    air:    { tier:'P', band:2, en:'road + rail corridor stack (Route 15, JR, Keikyu) — set-back blocks fine', ja:'国道15号・JR・京急の並走帯。奥のブロックは良好' },
    people: { tier:'E', foreign:'≈4%', en:'median ≈46 · long-tenure families + new tower arrivals', ja:'中央値≈46 · 定住ファミリー＋新築タワー層' },
    uber:   { tier:'E', full:true, thin:true },
    grocery:{ tier:'E', en:'mybasket density + Yokohama depachika 5′ away', ja:'まいばすけっと網＋横浜デパ地下5分' },
    coffee: { tier:'E', en:'kissa pockets; the serious coffee is one stop south', ja:'喫茶点在。本気のコーヒーは横浜側' },
  },
  nishi: {
    crime:  { tier:'E', en:'Terminal-district property crime typical of a five-line hub; west-exit residential rises calm.', ja:'ターミナル型の窃盗が典型。西口の住宅坂は平穏。' },
    air:    { tier:'P', band:2, en:'urban-core typical; sea breeze helps', ja:'都心型。海風が効く' },
    people: { tier:'E', foreign:'≈5%', en:'median ≈45 · everything from tower DINKs to student share-flats', ja:'中央値≈45 · タワーDINKsから学生まで' },
    uber:   { tier:'E', full:true },
    grocery:{ tier:'E', en:'Norengai basement + every chain that exists', ja:'のれん街＋全チェーン' },
    coffee: { tier:'E', en:'Minato Mirai roasters, harbor-view seats', ja:'みなとみらい系ロースター・港ビュー' },
  },
};

/* ————— per-station character (tier E unless marked) + quiet (tier P) ————— */
const AREA_ST = {
  ningyocho:  { quiet:{v:4, why:{en:'back-grid shitamachi; traffic stays on the avenues',ja:'裏路地の下町。車は大通り側'}},
    char:{en:'Shitamachi that kept its manners — doll-makers\' lanes, Meijiza theater, amazake alley. The corridor\'s gentlest landing for a newcomer.', ja:'行儀のいい下町 — 人形師の路地、明治座、甘酒横丁。新参者に最も優しい起点。'},
    style:{en:'low-rise infill + 2010s 1K/1LDK towers over shops', ja:'低層＋店舗上1K/1LDKタワー'},
    landmarks:{en:'Meijiza · Suitengū (safe-birth shrine) · Amazake Yokochō', ja:'明治座 · 水天宮 · 甘酒横丁'},
    food:{en:'Tamahide\'s oyakodon queue, Imahan sukiyaki, ningyō-yaki to go', ja:'玉ひで・今半・人形焼'},
    hobby:{en:'rakugo & theater nights, craft-shop hopping', ja:'落語・観劇・職人店巡り'} },
  nihombashi: { quiet:{v:3, why:{en:'office canyon — dead-quiet nights, expressway overhead hum',ja:'オフィス街 — 夜は静か、首都高の低音'}},
    char:{en:'Kilometer zero. Weekday power, weekend emptiness — you rent the city\'s center and get its Sundays to yourself.', ja:'日本国道路元標。平日は中枢、週末は貸切。'},
    style:{en:'office-conversion 1K/1LDK, weekday-quiet', ja:'オフィス転用型1K/1LDK'},
    landmarks:{en:'Nihombashi bridge · Coredo · Bank of Japan', ja:'日本橋 · コレド · 日銀'},
    food:{en:'depachika dinners, centuries-old eel and tempura counters', ja:'デパ地下・老舗鰻天'},
    hobby:{en:'museum row (Artizon 10′), bridge-to-bridge river walks', ja:'美術館・川沿い散歩'} },
  takaracho:  { quiet:{v:3, why:{en:'Shōwa-dōri traffic; side blocks fine',ja:'昭和通りの交通。脇は静か'}},
    char:{en:'The quiet seam between Kyōbashi galleries and Hatchōbori brokers — unfashionable address, everything at arm\'s reach.', ja:'京橋と八丁堀の縫い目。地味な住所、全部が近い。'},
    style:{en:'compact office-district 1K, gallery-adjacent', ja:'オフィス街型コンパクト1K'},
    landmarks:{en:'Artizon Museum · Kyōbashi Edogrand', ja:'アーティゾン · 京橋エドグラン'},
    food:{en:'gallery-café lunches; Tsukiji outer market 12′ on foot', ja:'ギャラリーカフェ・築地場外12分'},
    hobby:{en:'gallery-hopping, standing sushi apprenticeship', ja:'画廊巡り・立ち食い鮨'} },
  hgashiginza: { quiet:{v:3, why:{en:'Kabukiza side calm; Ginza spill two blocks west',ja:'歌舞伎座側は穏やか。銀座の賑わいは2ブロック西'}},
    char:{en:'Live behind the Kabukiza curtain — Ginza\'s stagehands\' quarter, theater crowds by day, hush by midnight.', ja:'歌舞伎座の裏側に住む。夜半は静寂。'},
    style:{en:'compact designer 1R/1K behind the theater', ja:'劇場裏のデザイナーズ1R/1K'},
    landmarks:{en:'Kabukiza · Tsukiji outer market next door', ja:'歌舞伎座 · 築地場外隣接'},
    food:{en:'Tsukiji breakfast as a lifestyle; Nair\'s, Japan\'s oldest Indian', ja:'築地朝食・ナイルレストラン'},
    hobby:{en:'single-act kabuki tickets (¥1–2k), market-knife window shopping', ja:'一幕見席・包丁店巡り'} },
  shimbashi:  { quiet:{v:2, why:{en:'izakaya district under the girders — lively until last train',ja:'ガード下酒場 — 終電まで賑やか'}},
    char:{en:'Salaryman Rome. If your evenings end late and social, no address on earth is more efficient; light sleepers look elsewhere.', ja:'サラリーマンの都。夜型に最適、浅い眠りの人は再考を。'},
    style:{en:'pied-à-terre 1K over izakaya; double-glazing or regret', ja:'酒場上の1K。二重サッシ必須'},
    landmarks:{en:'SL Square · Karasumori shrine lanes', ja:'SL広場 · 烏森の路地'},
    food:{en:'yakitori smoke under the tracks, thousand-yen lunches everywhere', ja:'ガード下焼き鳥・千円ランチ'},
    hobby:{en:'izakaya anthropology, Shiodome architecture walks', ja:'居酒屋巡り・汐留建築散歩'} },
  daimon:     { quiet:{v:3, why:{en:'temple precinct absorbs the night; Daimon-dōri hum',ja:'増上寺境内が夜を吸う。大門通りの音'}},
    char:{en:'Tokyo Tower fills your street\'s end and Zōjō-ji\'s bell sets the morning — the corridor\'s most cinematic ordinary address.', ja:'通りの先に東京タワー、朝は増上寺の鐘。'},
    style:{en:'tower 1LDK + temple-block low-rise', ja:'タワー1LDK＋門前低層'},
    landmarks:{en:'Zōjō-ji · Tokyo Tower · Shiba Park', ja:'増上寺 · 東京タワー · 芝公園'},
    food:{en:'soba lunches, monk-hours bakeries', ja:'蕎麦・朝型ベーカリー'},
    hobby:{en:'tower-loop running, temple photography at dawn', ja:'タワー周回ラン・朝の寺撮影'} },
  mita:       { quiet:{v:3, why:{en:'Sakurada-dōri traffic; Tsuki-no-misaki slope quiet',ja:'桜田通りの交通。月の岬側は静か'}},
    char:{en:'Keiō students below, embassy hill above — a working slope with Ramen Jirō\'s mother church at its foot.', ja:'慶應とイタリア大使館の坂。麓にラーメン二郎本店。'},
    style:{en:'student 1K + hillside embassy-belt 1LDK', ja:'学生1K＋坂上1LDK'},
    landmarks:{en:'Keiō University · Italian embassy slope', ja:'慶應義塾 · 綱町'},
    food:{en:'Ramen Jirō Mita HQ (the original queue), student teishoku', ja:'二郎三田本店・学生定食'},
    hobby:{en:'slope-and-temple walks, university lecture crashing (open days)', ja:'坂道散歩・公開講座'} },
  sengakuji:  { quiet:{v:4, why:{en:'temple quarter; Daiichi-Keihin one block off',ja:'寺町。第一京浜は1ブロック外'}},
    char:{en:'The junction itself — 47 rōnin at your door, every through-train in your pocket. Takanawa Gateway City rising next door.', ja:'直通の結節点。赤穂義士の門前、高輪ゲートウェイシティ隣接。'},
    style:{en:'temple-side low-rise + new Takanawa towers', ja:'寺側低層＋高輪新タワー'},
    landmarks:{en:'Sengakuji temple · Takanawa Gateway City (2025)', ja:'泉岳寺 · 高輪ゲートウェイシティ'},
    food:{en:'temple-gate wagashi, Takanawa hotel breakfasts', ja:'門前和菓子・高輪ホテル朝食'},
    hobby:{en:'Akō rōnin history, new-town architecture watching', ja:'義士史跡・新街区ウォッチ'} },
  shinagawa:  { quiet:{v:2, why:{en:'mega-terminal + Gateway City construction',ja:'巨大ターミナル＋工事'}},
    char:{en:'Not a neighborhood — a machine you live on top of. Every shinkansen, both airports, one escalator from bed.', ja:'街というより装置。新幹線も空港も一本。'},
    style:{en:'terminal towers, serviced flats', ja:'ターミナルタワー・サービス付き'},
    landmarks:{en:'Shinagawa terminal · Shinatatsu ramen row', ja:'品川駅 · 品達'},
    food:{en:'ecute everything, ramen row under the tracks', ja:'エキュート・品達ラーメン'},
    hobby:{en:'dawn shinkansen-spotting, Gotenyama garden walks', ja:'新幹線見物・御殿山散歩'} },
  kitashina:  { quiet:{v:4, why:{en:'old Tōkaidō back-lanes; sea-road traffic stays west',ja:'旧東海道の裏道。交通は西側'}},
    char:{en:'First post town on the old Tōkaidō — noren curtains, temple gates, and Tennōzu\'s waterfront cafés eight minutes east.', ja:'東海道品川宿。暖簾と寺、天王洲まで8分。'},
    style:{en:'machiya-scale walk-ups, renovated shukuba lanes', ja:'町家スケール・宿場リノベ'},
    landmarks:{en:'Shinagawa-juku lanes · Tennōzu Isle', ja:'品川宿 · 天王洲アイル'},
    food:{en:'shukuba izakaya, waterfront brewery (T.Y. Harbor)', ja:'宿場居酒屋・水辺ブルワリー'},
    hobby:{en:'old-road walking, canal kayaking (Tennōzu)', ja:'旧道歩き・運河カヤック'} },
  shimbamba:  { quiet:{v:4, why:{en:'shrine forest + shōtengai; expresses pass but set back',ja:'品川神社の杜＋商店街'}},
    char:{en:'Shinagawa shrine\'s fuji-zuka mini-mountain, a working shōtengai, and rents that forgot they\'re 3 minutes from the terminal.', ja:'品川神社の富士塚と商店街。品川3分の家賃ではない。'},
    style:{en:'shrine-block walk-ups + 90s family stock', ja:'神社脇の中層＋90年代ファミリー'},
    landmarks:{en:'Shinagawa Shrine (climb the fuji-zuka) · Mēguro river mouth', ja:'品川神社富士塚 · 目黒川河口'},
    food:{en:'shōtengai croquettes, river-mouth izakaya', ja:'商店街コロッケ・河口居酒屋'},
    hobby:{en:'fuji-zuka sunrise climbs (2 minutes to summit), festival season', ja:'富士塚登山・例大祭'} },
  aomono:     { quiet:{v:3, why:{en:'tokkyū stop + Jōnan road; arcade absorbs evenings',ja:'特急停車＋城南の道路。アーケードが夜を吸収'}},
    char:{en:'The greengrocers\' crossroads it\'s named for, now the express-stop bargain of the Shinagawa shore.', ja:'青物市の辻。品川湾岸の特急停車バーゲン。'},
    style:{en:'arcade-side 1LDK + canal family stock', ja:'アーケード脇1LDK＋運河ファミリー'},
    landmarks:{en:'Jōnan shopping arcade · Shinagawa temples', ja:'城南商店街 · 品川寺'},
    food:{en:'arcade standing bars, temple-front unagi', ja:'アーケード立ち飲み・門前鰻'},
    hobby:{en:'temple-bell circuit (Shinagawa-dera\'s giant Jizō), arcade shogi', ja:'品川寺地蔵・商店街将棋'} },
  samezu:     { quiet:{v:4, why:{en:'canal-side; only locals stop',ja:'運河沿い。普通のみ停車'}},
    char:{en:'Shark-sands village turned license-center joke — stay for the boat basin, dawn rowers, and honest rents.', ja:'鮫洲 — 免許センターの街。舟溜まりと正直な家賃。'},
    style:{en:'canal-side 90s stock + new compact 1LDK', ja:'運河沿い90年代＋新築コンパクト'},
    landmarks:{en:'Samezu boat basin · Ōi racecourse twilight races 12′', ja:'鮫洲舟溜 · 大井競馬トゥインクル'},
    food:{en:'boat-basin izakaya, racecourse yatai nights', ja:'舟溜居酒屋・競馬場屋台'},
    hobby:{en:'sculling club, twilight horse races', ja:'ボート・薄暮競馬'} },
  tachiaigawa: { quiet:{v:4, why:{en:'boat basin + Ryōma\'s quarter; Daiichi-Keihin one block',ja:'舟溜＋龍馬の町。第一京浜1ブロック'}},
    char:{en:'Sakamoto Ryōma stood guard here at 17; the fishing boats still go out. A harbor village hiding inside the megacity.', ja:'龍馬像と漁船の町。巨大都市の中の港村。'},
    style:{en:'harbor-lane low-rise + levee-view 2LDK', ja:'漁港低層＋堤防ビュー2LDK'},
    landmarks:{en:'Ryōma statue · Tachiai river mouth boats', ja:'龍馬像 · 立会川河口'},
    food:{en:'boat-basin seafood, shōtengai yakitori', ja:'漁港海鮮・商店街焼き鳥'},
    hobby:{en:'haze-fishing boat trips, Ryōma history walk', ja:'ハゼ釣り船・龍馬史跡'} },
  omorikaigan: { quiet:{v:3, why:{en:'Route 15 + monorail; aquarium park side calm',ja:'国道15号＋モノレール。公園側は穏やか'}},
    char:{en:'Where Tokyo\'s nori was farmed — now the aquarium\'s dolphin shows echo over a bayside grid of honest family flats.', ja:'海苔養殖の海辺。水族館とファミリー住宅。'},
    style:{en:'bayside danchi renewal + park-side 2LDK', ja:'湾岸団地更新＋公園側2LDK'},
    landmarks:{en:'Shinagawa Aquarium · nori museum (Ōmori Furusato-no-hamabe)', ja:'しながわ水族館 · 海苔のふるさと館'},
    food:{en:'nori-maki heritage, park picnic konbini', ja:'海苔巻き・公園ピクニック'},
    hobby:{en:'aquarium membership, beach-park volleyball', ja:'水族館年パス・浜辺公園'} },
  heiwajima:  { quiet:{v:3, why:{en:'tokkyū stop; logistics hum + keirin crowd days',ja:'特急停車。物流の低音＋競輪開催日'}},
    char:{en:'Reclaimed-island utility: 24h onsen, bowling, keirin, big-box everything — leisure infrastructure instead of charm, and it works.', ja:'埋立島の実用主義。温泉・ボウリング・競輪。'},
    style:{en:'worker 1K + renewal towers on the island edge', ja:'ワーカー1K＋島縁タワー'},
    landmarks:{en:'Heiwajima Onsen (24h) · BIG FUN · keirin dome', ja:'平和島温泉 · ビッグファン · 競輪場'},
    food:{en:'food-court teishoku, truckers\' curry at 3am', ja:'フードコート定食・深夜カレー'},
    hobby:{en:'midnight onsen runs, keirin spectating, flea market (weekends)', ja:'深夜温泉・競輪・フリマ'} },
  omorimachi: { quiet:{v:3, why:{en:'local stop between two trunk roads',ja:'普通駅。幹線に挟まれる'}},
    char:{en:'Unfamous, unpretentious, fifteen minutes from everything — the classic Ōta compromise, priced accordingly.', ja:'無名で気取らない大田区の典型。'},
    style:{en:'shōtengai walk-ups, sentō blocks', ja:'商店街中層・銭湯ブロック'},
    landmarks:{en:'Mikai shrine lanes · sentō circuit', ja:'貴舩神社 · 銭湯巡り'},
    food:{en:'motsuyaki alleys, bakery morning sets', ja:'もつ焼き横丁・パン屋モーニング'},
    hobby:{en:'kuroyu sentō collecting (Ōta has 30+)', ja:'黒湯銭湯収集'} },
  umeyashiki: { quiet:{v:4, why:{en:'plum-garden heritage grid; expresses pass the platform',ja:'梅園跡の住宅網。優等は通過'}},
    char:{en:'Named for an Edo plum garden travelers detoured to see; the shōtengai still runs at garden pace.', ja:'江戸の梅園の名残。商店街は庭の速度。'},
    style:{en:'shōtengai walk-ups + hushed back grid', ja:'商店街中層＋静かな裏路地'},
    landmarks:{en:'Umeyashiki park (the plum remnant) · Kōbō-daishi road stones', ja:'梅屋敷公園 · 大師道標石'},
    food:{en:'shōtengai croquettes & taiyaki, family kissa', ja:'コロッケ・たい焼き・家族喫茶'},
    hobby:{en:'February plum viewing at your own station, sentō culture', ja:'梅見・銭湯'} },
  kamata:     { quiet:{v:2, why:{en:'junction viaduct + airport expresses + east-exit nightlife',ja:'高架junction＋空港優等＋東口夜街'}},
    char:{en:'The corridor\'s engine room — gyōza capital, black-water onsen, Yūzawaya crafts empire, and the airport line under your floor.', ja:'沿線のエンジンルーム。羽根つき餃子と黒湯、ユザワヤ、空港線。'},
    style:{en:'junction towers + shōtengai maze flats', ja:'ジャンクションタワー＋商店街迷路'},
    landmarks:{en:'Yūzawaya · hane-tsuki gyōza birthplace · kuroyu onsen', ja:'ユザワヤ · 羽根つき餃子 · 黒湯温泉'},
    food:{en:'gyōza pilgrimage (Ni-Hao, Kinchun), 24h shōtengai', ja:'餃子巡礼・24時間商店街'},
    hobby:{en:'crafts (8 floors of Yūzawaya), onsen-sentō doubleheaders', ja:'手芸・温泉銭湯はしご'} },
  zoshiki:    { quiet:{v:3, why:{en:'shōtengai active evenings; back grid settles by 22:00',ja:'商店街は宵まで。裏は22時に静まる'}},
    char:{en:'A kilometer of covered shōtengai doing exactly what shōtengai are supposed to do — Rising place\'s ¥79k 1K buys into all of it.', ja:'雑色商店街1km。79,000円の1Kでこの生活。'},
    style:{en:'shōtengai walk-ups + riverside family stock', ja:'商店街中層＋川側ファミリー'},
    landmarks:{en:'Zōshiki shōtengai · Tama river levee 10′', ja:'雑色商店街 · 多摩川土手10分'},
    food:{en:'shōtengai bakeries, standing soba, yakitori by the gram', ja:'パン屋・立ち食い蕎麦・量り焼き鳥'},
    hobby:{en:'levee cycling, shōtengai festival calendar', ja:'土手サイクリング・商店街祭'} },
  rokugodote: { quiet:{v:4, why:{en:'levee-side; river absorbs the night',ja:'土手沿い。川が夜を吸う'}},
    char:{en:'Last stop in Tokyo — the Tama levee is your front yard, Kawasaki\'s lights are your river view, sunsets are nightly programming.', ja:'東京最後の駅。多摩川土手が庭。'},
    style:{en:'river-terrace mansions, levee sunsets', ja:'リバーテラス型・土手夕景'},
    landmarks:{en:'Tama river levee · Rokugō bridge crossing', ja:'多摩川土手 · 六郷橋'},
    food:{en:'levee bentō picnics, bridge-side unagi', ja:'土手弁当・橋際鰻'},
    hobby:{en:'levee running/cycling course, riverside baseball leagues', ja:'土手ラン・草野球'} },
  kawasaki:   { quiet:{v:2, why:{en:'terminal + east entertainment district',ja:'ターミナル＋東側歓楽街'}},
    char:{en:'Kanagawa\'s loudest downtown and proud of it — cinema city, Daishi pilgrimages, factory-night-view cruises, big-city rents one river cheaper.', ja:'神奈川最強の繁華街。映画・大師・工場夜景。'},
    style:{en:'terminal towers (Rivarier) + Daishi-line low-rise', ja:'駅前タワー＋大師線低層'},
    landmarks:{en:'La Cittadella · Kawasaki Daishi · factory night views', ja:'ラ チッタデッラ · 川崎大師 · 工場夜景'},
    food:{en:'Shōwa-alley horumon, Chinatown-grade neighborhood Chinese', ja:'昭和横丁ホルモン・町中華'},
    hobby:{en:'cinema nights, Daishi temple markets, industrial-port cruises', ja:'映画・大師縁日・運河クルーズ'} },
  hatcho:     { quiet:{v:3, why:{en:'Nambu-branch junction + Route 15 nearby',ja:'南武支線分岐＋国道15号'}},
    char:{en:'Borderland platform where the Nambu branch peels off — Tokyo-side prices with Kawasaki-side convenience, and Bashō stopped here once.', ja:'南武支線の分岐点。芭蕉の句碑がある境界の駅。'},
    style:{en:'borderland low-rise — cheapest square meters on the Tokyo side', ja:'境界低層 — 都側最安㎡'},
    landmarks:{en:'Bashō poem stone · two-line junction', ja:'芭蕉句碑 · 分岐駅'},
    food:{en:'workers\' teishoku, ramen on the truck road', ja:'定食・トラック街道ラーメン'},
    hobby:{en:'branch-line trainspotting, Tōkaidō boundary walks', ja:'支線撮影・旧道歩き'} },
  ichiba:     { quiet:{v:4, why:{en:'old market street, residential core',ja:'旧市場の住宅核'}},
    char:{en:'The Tōkaidō\'s old market suburb — an unhurried shōtengai, an ichirizuka milestone mound, rents near the corridor\'s floor.', ja:'東海道の市場町。一里塚と商店街。'},
    style:{en:'market-street low-rise, family two-stories', ja:'市場通り低層・二階建てファミリー'},
    landmarks:{en:'Ichirizuka mound · market-street shrine', ja:'市場一里塚 · 熊野神社'},
    food:{en:'market-street tofu & greengrocers', ja:'豆腐店・八百屋'},
    hobby:{en:'old-Tōkaidō walking stage, shōtengai bingo nights', ja:'旧道歩き・商店街行事'} },
  tsurumi:    { quiet:{v:3, why:{en:'twin terminals + Route 1; Okinawa-town side calmer',ja:'二駅＋国道1号。沖縄タウン側は穏やか'}},
    char:{en:'Little Okinawa on the Keihin line — Nakadōri\'s soba and sanshin, two stations\' worth of trains, Sōji-ji\'s forest up the hill.', ja:'京浜の小さな沖縄。仲通りと總持寺。'},
    style:{en:'station towers + Okinawa-town low-rise', ja:'駅前タワー＋沖縄タウン低層'},
    landmarks:{en:'Okinawa-town Nakadōri · Sōji-ji forest', ja:'沖縄タウン仲通り · 總持寺'},
    food:{en:'Okinawa soba, taco rice, umibudō grocers', ja:'沖縄そば・タコライス・海ぶどう'},
    hobby:{en:'sanshin lessons, Eisā festival season, zazen next stop', ja:'三線・エイサー・坐禅'} },
  kagetsu:    { quiet:{v:4, why:{en:'Sōji-ji\'s forest absorbs the line',ja:'總持寺の杜が線路音を吸う'}},
    char:{en:'Renamed for the grand Zen headquarters at its door — Sōji-ji\'s cedars, morning zazen, and a platform almost nobody uses.', ja:'總持寺の門前駅。杉木立と朝坐禅。'},
    style:{en:'temple-hill walk-ups, student flats (Tsurumi Univ)', ja:'寺坂中層・鶴見大学生向け'},
    landmarks:{en:'Sōji-ji (Sōtō Zen head temple)', ja:'大本山總持寺'},
    food:{en:'temple shōjin lunches, student teishoku', ja:'精進料理・学生定食'},
    hobby:{en:'public zazen sittings, cemetery cedar walks', ja:'坐禅会・杉並木散歩'} },
  namamugi:   { quiet:{v:2, why:{en:'brewery freight + Route 15 + industrial canal',ja:'ビール工場物流＋国道15号＋運河'}},
    char:{en:'Where the Namamugi Incident sparked a war and Kirin now brews — fish wholesalers at dawn, brewery tours at noon, freight at night.', ja:'生麦事件とキリンビールの町。魚河岸と工場。'},
    style:{en:'brewery-side worker flats, canal lofts', ja:'工場側ワーカー向け・運河ロフト'},
    landmarks:{en:'Kirin Yokohama brewery · Namamugi fish market · incident monument', ja:'キリン横浜工場 · 生麦魚河岸 · 事件碑'},
    food:{en:'fish-market breakfasts, brewery-fresh beer restaurant', ja:'魚河岸朝食・工場直ビール'},
    hobby:{en:'brewery tour (free tastings), dawn market runs', ja:'工場見学・朝市'} },
  shinkoyasu: { quiet:{v:3, why:{en:'rail-road stack; tower blocks set back',ja:'鉄道・道路の並走。タワーは奥'}},
    air:{tier:'P', band:3, en:'closest to the bayside plants — the corridor\'s PM watch point', ja:'臨海工場最寄り — PM注意点'},
    char:{en:'Tower-and-highway sandwich with bay-bridge views — the price you see is the noise you hear; corner units face the water.', ja:'タワーと幹線の挟間。角部屋はベイビュー。'},
    style:{en:'tower-and-highway sandwich, bay views up high', ja:'タワー型・高層はベイビュー'},
    landmarks:{en:'Bay bridge sightlines · Orbi-side Yokohama access', ja:'ベイブリッジ眺望'},
    food:{en:'workers\' ramen on the Daiichi-Keihin', ja:'第一京浜ラーメン'},
    hobby:{en:'bay-view photography, JR-vs-Keikyu race watching', ja:'ベイ撮影・並走見物'} },
  koyasu:     { quiet:{v:4, why:{en:'fishing-canal backstreet; locals only',ja:'漁師運河の裏道。普通のみ'}},
    char:{en:'A real fishing-boat canal survives here — anago boats, net sheds, and a ¥65,000 new-build 1R six minutes from it all.', ja:'現役の漁師運河。穴子舟と網小屋。'},
    style:{en:'fishing-canal retro + new infill 1R/1K', ja:'運河レトロ＋新築イン フィル'},
    landmarks:{en:'Koyasu boat canal (last working one this side of the bay)', ja:'子安漁港運河'},
    food:{en:'anago tempura when the boats land', ja:'穴子天ぷら'},
    hobby:{en:'canal photography, boat-owner small talk', ja:'運河撮影・船主と世間話'} },
  shimmachi:  { quiet:{v:3, why:{en:'Keikyu\'s main depot — first trains stable here',ja:'京急の車庫。始発が寝る場所'}},
    char:{en:'The line sleeps here — depot views, guaranteed morning seats on originating trains, and a tokkyū stop nobody brags about.', ja:'車庫の駅。始発着席と特急停車。'},
    style:{en:'depot-side family mansions', ja:'車庫脇ファミリーマンション'},
    landmarks:{en:'Shimmachi depot (trainspotting royalty) · Urashima legend sites north', ja:'新町検車区 · 浦島伝説地'},
    food:{en:'depot-side kissa, family soba', ja:'車庫前喫茶・家族蕎麦'},
    hobby:{en:'depot photography at dawn, originating-train seat strategy', ja:'車庫撮影・始発戦略'} },
  hkanagawa:  { quiet:{v:3, why:{en:'two-terminal seam; through traffic',ja:'二ターミナルの継ぎ目'}},
    char:{en:'Urashima Tarō allegedly came home near here — now it\'s the quiet seam where JR transfer convenience meets Keikyu rents.', ja:'浦島太郎伝説の地。JR乗換×京急家賃。'},
    style:{en:'transfer-seam mid-rise, JR-side convenience', ja:'乗換帯の中層'},
    landmarks:{en:'Urashima shrine sites · JR Higashi-kanagawa cross-platform', ja:'浦島神社跡 · JR東神奈川'},
    food:{en:'two-terminal konbini corridor, alley snacks', ja:'コンビニ回廊・路地スナック'},
    hobby:{en:'legend-site bingo, Yokohama-line day trips', ja:'伝説地巡り・横浜線小旅行'} },
  kanagawa:   { quiet:{v:3, why:{en:'Aokibashi crossing + Yokohama spill',ja:'青木橋＋横浜の余波'}},
    char:{en:'The post town that named the prefecture, reduced to one modest platform — living here is the quietest way to own Yokohama station.', ja:'県名の由来の宿場。横浜駅を静かに所有する住み方。'},
    style:{en:'quiet grid between two terminals, Portside 1K north', ja:'静かな住宅網＋ポートサイド1K'},
    landmarks:{en:'Kanagawa-juku history road · Portside district', ja:'神奈川宿 · ポートサイド'},
    food:{en:'Tōkaidō-juku soba, Portside bakery cafés', ja:'宿場蕎麦・ポートサイドカフェ'},
    hobby:{en:'Yokohama on foot (7′), station-history plaques', ja:'徒歩横浜・史跡プレート'} },
  yokohama:   { quiet:{v:2, why:{en:'five-line mega-terminal',ja:'五社ターミナル'}},
    char:{en:'The goal line itself. Sea air, Minato Mirai\'s ferris glow, and every train home you could ever miss — you won\'t.', ja:'ゴール地点。海風と観覧車、終電の心配なし。'},
    style:{en:'west-exit towers, Portside 1K, sea-view premiums', ja:'西口タワー・ポートサイド・海側プレミア'},
    landmarks:{en:'Minato Mirai · Sōgō/Norengai · bay promenade', ja:'みなとみらい · のれん街 · 臨港プロムナード'},
    food:{en:'Norengai basement to harbor fine dining — all of it', ja:'のれん街から港レストランまで'},
    hobby:{en:'harbor runs, museum ships, Chinatown 2 stops', ja:'港ラン・帆船・中華街2駅'} },
};

/* ————— noise watch: benchmarked against actual local noise archetypes:
   mobile megaphones (yaki-imo/kerosene), political sound trucks (gaisensha),
   religious/cult loudspeakers, rowdy nomikai entertainment spillover,
   tourism luggage rumbling, Daikoku PA tuner meets / Wangan runs,
   kyūshakai/bōsōzoku arterial runs, and tourist street-karts.
   Specific street claims tier E — complaint-data adapter queued (Q). ————— */
const NOISE_TYPE_LABELS = {
  yaki_imo:       { en: 'Mobile Megaphones (Yaki-imo / Kerosene)', ja: '巡回スピーカー（焼き芋・灯油・廃品回収）' },
  gaisensha:      { en: 'Political Sound Trucks & Demonstrations', ja: '政治宣伝車（街宣車）・デモ行進' },
  cult_religious: { en: 'Religious Loudspeakers & Cult Outreach',  ja: '宗教・カルト街宣勧誘' },
  nomikai_rowdy:  { en: 'Late-Night Izakaya & Rowdy Street Noise', ja: '繁華街・泥酔・深夜の客引き騒音' },
  tourism_spikes: { en: 'Tourist Surges & Rolling Luggage Rumbles',ja: '観光集中・早朝深夜のスーツケース走行音' },
  daikoku_mod:    { en: 'Daikoku Tuner Meets & Wangan Acceleration', ja: '大黒PA・湾岸線改造車・ルーレット族' },
  bosozoku:       { en: 'Kyūshakai / Motorcycle Exhaust Convoys',  ja: '旧車會・幹線道路の爆音バイク' },
  kart:           { en: 'Tourist Street-Kart Convoys',             ja: '公道カートツアー' },
  boat_diesel:    { en: 'Early Morning Commercial Boat Engines',   ja: '早朝の漁船・作業船ディーゼル音' },
  train_viaduct:  { en: 'Railway Viaduct Rumble',                  ja: '高架鉄道の通過音・振動' },
};

const NOISE_EVENTS = {
  ningyocho: [
    { type:'tourism_spikes', when:{en:'daytime weekends & morning checkout',ja:'土日昼間・朝のチェックアウト時間帯'},
      summary:{en:'tourist foot-traffic & luggage rumble on Amazake Yokochō', ja:'甘酒横丁の観光客歩行とスーツケース走行音'},
      en:'High density of boutique hotels and visitors rolling wheeled suitcases over paving stones towards T-CAT and Ningyocho stations.',
      ja:'人形町・T-CAT周辺のホテル客によるスーツケース走行音と、週末の甘酒横丁の観光混雑。',
      tip:{en:'choose apartments on internal side-streets off Ningyocho-dori', ja:'人形町通りから1本入った裏通りが静か'},
      tier:'E', src:'local pedestrian observation' }
  ],
  nihombashi: [
    { type:'gaisensha', when:{en:'weekend afternoons',ja:'土日午後の時間帯'},
      summary:{en:'political sound trucks on Chuo-dori & Yaesu perimeter', ja:'中央通り・八重洲周辺の政治街宣車'},
      en:'Black political propaganda vans cruise Chuo-dori and the Bank of Japan perimeter with megaphones broadcasting slogans.',
      ja:'中央通りや日銀・八重洲周辺を巡回する大型街宣車の拡声器演説。休日の午後に散発。',
      tip:{en:'high-rise units need double-glazed windows facing trunk corridors', ja:'幹線に面した高層階は二重サッシ必須'},
      tier:'E', src:'Metropolitan Police traffic reports' }
  ],
  takaracho: [
    { type:'gaisensha', when:{en:'weekend daytime demonstrations',ja:'週末昼間のデモ・街宣'},
      summary:{en:'Ginza perimeter rally marches & police loudspeaker sirens', ja:'銀座外周のデモ行進・警察パトカーのサイレン'},
      en:'Marches moving from Hibiya Park along Showa-dori and Ginza perimeter bring police escorts and crowd chanting.',
      ja:'日比谷から昭和通り・銀座外周へ向かうデモ隊と警察規制車両のマイク音。',
      tip:{en:'residential blocks between Takaracho and Hatchobori are remarkably insulated', ja:'宝町〜八丁堀の間の路地はオフィス街で夜間極めて静か'},
      tier:'E', src:'Tokyo public safety logs' }
  ],
  hgashiginza: [
    { type:'tourism_spikes', when:{en:'early mornings & theater intermissions',ja:'早朝5〜8時および歌舞伎座開演前後'},
      summary:{en:'Tsukiji market wholesale trucks & Kabukiza tourist surges', ja:'旧築地周辺の市場配送車輪音と歌舞伎座の観光客集中'},
      en:'Refrigerated delivery trucks and tourist luggage roll early towards Tsukiji outer market; Harumi-dori gets periodic crowd bursts.',
      ja:'築地場外向けの早朝冷蔵トラック走行音と、晴海通り沿いの観光・キャリーケース音。',
      tip:{en:'Shintomi and Tsukiji 2-chome backblocks remain quiet residential pockets', ja:'新富町側や築地2丁目の裏手は夜間非常に静穏'},
      tier:'E', src:'ward pedestrian audit' },
    { type:'kart', when:{en:'afternoon–evening loops',ja:'昼〜夕方の周回'},
      summary:{en:'street-kart tours on Harumi-dori', ja:'晴海通りを通過する公道カート'},
      en:'Central Tokyo kart convoys pass along Harumi-dori between Ginza and Tokyo Bay; noisy revs at red lights.',
      ja:'銀座とベイエリアを結ぶ晴海通りを公道カートが走行。信号待ちでの空ぶかし。',
      tip:{en:'avoid lower floors directly fronting Harumi-dori', ja:'晴海通り直面の下層階を避ける'},
      tier:'E', src:'operator route map' }
  ],
  shimbashi: [
    { type:'nomikai_rowdy', when:{en:'nightly 21:00–04:00 (heavy Thursday–Friday)',ja:'毎夜21時〜深夜4時（特に木・金）'},
      summary:{en:'SL Square drunk revellers, touts & early morning bottle bins', ja:'SL広場・烏森口の泥酔客、客引き、早朝の空き瓶回収'},
      en:'Karasumori drinking quarter gets boisterous post-midnight banter, loud group goodbyes, and 4 AM clattering trash collection.',
      ja:'烏森口・ガード下の飲み屋街で深夜の泥酔者、グループの歓声、早朝の瓶ビール箱回収音。',
      tip:{en:'seek residences west towards Nishi-Shimbashi or Shiodome residential towers', ja:'西新橋側または汐留タワー棟が防音・住環境良好'},
      tier:'E', src:'Minato ward resident feedback' },
    { type:'gaisensha', when:{en:'weekend afternoons',ja:'土日午後の演説'},
      summary:{en:'SL Square public political speeches & sound vans', ja:'SL広場前の街頭演説・政治宣伝車'},
      en:'SL Square is Tokyo’s iconic soapbox for political campaigns, megaphone rallies, and occasional sound-truck drive-bys.',
      ja:'SL広場前での各党街頭演説やスピーカー街宣車。',
      tip:{en:'sound is concentrated squarely on the station west plaza', ja:'広場正面から離れたブロックを選ぶ'},
      tier:'E', src:'Chiyoda/Minato police filings' }
  ],
  daimon: [
    { type:'kart', when:{en:'afternoon–dusk photo halts',ja:'午後〜夕方の撮影停車'},
      summary:{en:'Tokyo Tower approach tourist kart revving', ja:'東京タワー参道での公道カート空ぶかし'},
      en:'Convoys idle, rev high-pitch 2-stroke engines, and regroup along the approach to Zojoji and Tokyo Tower.',
      ja:'芝大門〜増上寺〜東京タワーへの進入路でカート隊列が停車・空ぶかし。',
      tip:{en:'blocks south toward Hamamatsucho 2-chome bypass the tourist run entirely', ja:'浜松町2丁目寄りの街区はカートルートから外れる'},
      tier:'E', src:'Minato complaint open data' },
    { type:'gaisensha', when:{en:'selected national holidays & Sunday rallies',ja:'祝日・日曜の特定集会'},
      summary:{en:'Shiba Koen demonstration march staging', ja:'芝公園を発着点とするデモ行進・街宣'},
      en:'Shiba Park serves as a permitted gathering point for labor and civic rallies with megaphone chants.',
      ja:'芝公園での集会・デモ行進に伴う拡声器シュプレヒコール。',
      tip:{en:'settle on the residential seam north of Daimon crossing', ja:'大門交差点北側の住宅街区が好適'},
      tier:'E', src:'civic permits' }
  ],
  mita: [
    { type:'gaisensha', when:{en:'weekdays & weekend daytime near diplomatic row',ja:'平日昼間および休日'},
      summary:{en:'political sound vans near Mita embassies & Keio rallies', ja:'各国大使館・慶應大学周辺の政治街宣車'},
      en:'Sound trucks occasionally circle the Mita diplomatic enclave (Australian, Italian embassies) and Keio University perimeter.',
      ja:'各国大使館や慶應義塾大学周辺を周回する街宣車の抗議放送。',
      tip:{en:'residences up the Tsunamachi hill or off Sakurada-dori are serene', ja:'綱町や桜田通りから入った高台の住宅街は極めて閑静'},
      tier:'E', src:'Mita police precinct' }
  ],
  sengakuji: [
    { type:'gaisensha', when:{en:'national commemoration days (Dec 14 Gishi-sai etc.)',ja:'討ち入り記念日（12/14義士祭）等'},
      summary:{en:'temple festival crowds & Dai-Ichi Keihin traffic roar', ja:'義士祭の混雑と第一京浜の走行音'},
      en:'Heavy crowd surge during December Ako Gishi-sai; Dai-Ichi Keihin arterial noise buffers right at the station exit.',
      ja:'12月の赤穂義士祭時の大混雑と、第一京浜本線の交通騒音。',
      tip:{en:'blocks on Takanawa 2-chome bluff behind the temple are deeply quiet', ja:'高輪2丁目・寺院裏手の高台は驚くほど静寂'},
      tier:'E', src:'Takanawa neighborhood council' }
  ],
  shinagawa: [
    { type:'tourism_spikes', when:{en:'early morning 06:00–08:30 & Sunday evening',ja:'早朝6時〜8時半および日曜夜'},
      summary:{en:'Konan Shinkansen concourse luggage rattle & taxi queues', ja:'港南口新幹線コンコースのスーツケース音・タクシー列'},
      en:'Mass transit commuter surge and thousand-person suitcase roller noise across the massive Konan pedestrian concourse.',
      ja:'早朝新幹線利用者のキャリーケース走行音と東海道線乗り換え群の足音。',
      tip:{en:'residential mid-rises along Kyu-Kaigan-dori enjoy canal insulation', ja:'旧海岸通り沿いの住宅街は運河に守られて静穏'},
      tier:'E', src:'JR East station metrics' },
    { type:'nomikai_rowdy', when:{en:'Friday nights 22:00–02:00',ja:'金曜深夜の歓楽街'},
      summary:{en:'Konan dining alley drinking spillover', ja:'港南口飲み屋街の混雑・歓声'},
      en:'Narrow izakaya alleyways east of the station pack with corporate nomikai overflow till midnight.',
      ja:'港南口路地の居酒屋街での歓送迎会・金曜夜の喧騒。',
      tip:{en:'choose apartments west of Takanawa exit or 6+ minutes south', ja:'高輪口側または南に徒歩6分以上離れた街区が安心'},
      tier:'E', src:'Minato ward noise reports' }
  ],
  kitashina: [
    { type:'bosozoku', when:{en:'weekend midnight hours 00:00–03:00',ja:'週末深夜0時〜3時'},
      summary:{en:'Route 15 (Dai-Ichi Keihin) motorcycle exhaust runs', ja:'第一京浜（国道15号）での旧車會・バイク爆音走行'},
      en:'Motorcycle groups use the wide straight stretches of Route 15 late on Friday and Saturday nights.',
      ja:'国道15号の直線区間を週末深夜に旧車會・改造バイクが走行。',
      tip:{en:'the Old Tokaido pedestrian street sits 1 full block west and is shielded', ja:'旧東海道の宿場町通りは1本裏手にあり本線騒音が遮断される'},
      tier:'E', src:'Shinagawa police records' },
    { type:'yaki_imo', when:{en:'autumn/winter evenings 17:00–20:00',ja:'秋冬夕方17時〜20時'},
      summary:{en:'slow-rolling yaki-imo stone-baked potato loudspeakers', ja:'住宅街を回る焼き芋・廃品回収の拡声器放送'},
      en:'Classic shitamachi sweet-potato trucks roll slowly down the residential lanes chanting their melody.',
      ja:'旧東海道沿いの路地を巡回する「いしや〜きいも〜」のスピーカー音。',
      tip:{en:'regarded locally as nostalgic neighborhood charm, not distress', ja:'住民には下町の風情として定着'},
      tier:'E', src:'shitamachi seasonal logs' }
  ],
  shimbamba: [
    { type:'yaki_imo', when:{en:'winter evenings & weekend daytime',ja:'冬期夕方および週末昼間'},
      summary:{en:'kerosene delivery music chimes & yaki-imo calls', ja:'灯油巡回車のメロディ（雪やこんこ）と焼き芋アナウンス'},
      en:'Kerosene supplier mini-trucks play musical chimes; scrap collectors broadcast through megaphones.',
      ja:'狭い宿場路地を回る灯油販売車（唱歌メロディ）や廃品回収車の巡回マイク。',
      tip:{en:'shukuba grid has virtually zero through-car traffic', ja:'通り抜け車両が少なく自動車騒音は極小'},
      tier:'E', src:'Shinagawa post-town chronicle' },
    { type:'bosozoku', when:{en:'weekend midnight 01:00–03:00',ja:'週末深夜'},
      summary:{en:'Dai-Ichi Keihin arterial buffer caveat', ja:'第一京浜の深夜通過音（東側近接部）'},
      en:'Properties fronting the eastern arterial feel the midnight exhaust bursts; post-town side is protected.',
      ja:'第一京浜直面の建物のみ深夜の排気音が届く。宿場側は静か。',
      tip:{en:'pick homes on the west side of Shimbamba station', ja:'駅西側の神社・旧宿場側が静か'},
      tier:'E', src:'police arterial logs' }
  ],
  aomono: [
    { type:'nomikai_rowdy', when:{en:'evenings 19:00–23:30',ja:'夕方19時〜23時半'},
      summary:{en:'Yokocho shotengai post-work dinner crowds', ja:'横丁商店街の仕事帰り飲食混雑'},
      en:'Lively neighborhood izakaya alleys have pleasant evening chatter around the shopping street.',
      ja:'青物横丁商店街の飲食店での夕方の賑わい。',
      tip:{en:'residential blocks south toward Minami-Shinagawa 3-chome are peaceful', ja:'南品川3丁目方面へ入ると静穏な住環境'},
      tier:'E', src:'Shinagawa commercial audit' }
  ],
  samezu: [
    { type:'yaki_imo', when:{en:'winter dusk',ja:'冬期の夕方'},
      summary:{en:'quiet waterfront residential kerosene chimes', ja:'海岸沿い住宅街の灯油巡回車メロディ'},
      en:'Quiet residential grid east of the station experiences seasonal vendor trucks.',
      ja:'駅東側の静かな住宅街を巡回する灯油販売メロディ。',
      tip:{en:'drivers exam center traffic is daytime only; nights are quiet', ja:'運転免許試験場の来訪者は日中のみで夜間は静寂'},
      tier:'E', src:'Ota/Shinagawa border survey' }
  ],
  tachiaigawa: [
    { type:'boat_diesel', when:{en:'early dawn 04:30–06:00',ja:'早朝4時半〜6時'},
      summary:{en:'fishing skiff diesel motor startups in the canal basin', ja:'舟溜まりでの釣り船・作業船ディーゼル始動音'},
      en:'Skippers start low-rumble diesel engines at dawn to head out past the river mouth into Tokyo Bay.',
      ja:'東京湾へ出る遊漁船・ハゼ釣り船の早朝アイドリングと波音。',
      tip:{en:'quayside homes hear low engine purr; blocks past the highway hear nothing', ja:'水門沿いの部屋以外は聞こえない局所音'},
      tier:'E', src:'local maritime ward records' },
    { type:'yaki_imo', when:{en:'autumn/winter dusk',ja:'秋冬の黄昏時'},
      summary:{en:'neighborhood kerosene chime trucks & sweet potato calls', ja:'灯油販売車メロディと焼き芋巡回'},
      en:'Quiet post-town alleys echo with seasonal roving vendor chimes in the evening.',
      ja:'低層住宅街を流す季節巡回トラックのメロディ。',
      tip:{en:'quiet residential blocks along the river walk are peaceful', ja:'立会川緑道沿いは自動車が入らず極めて静穏'},
      tier:'E', src:'local community logs' }
  ],
  omorikaigan: [
    { type:'bosozoku', when:{en:'weekend midnight hours',ja:'週末深夜帯'},
      summary:{en:'coastal expressway bypass exhaust runs', ja:'海岸通り・高速湾岸線合流部の排気音'},
      en:'Coastal highway straightaways occasionally catch high-speed vehicle passes late at night.',
      ja:'海岸通り沿いでの深夜の高速通過音。',
      tip:{en:'blocks west toward Omori JR station are shielded by parkland', ja:'大森海岸公園や西側の街区は遮音される'},
      tier:'E', src:'Ota police logs' }
  ],
  heiwajima: [
    { type:'bosozoku', when:{en:'weekend midnight 00:00–02:30',ja:'週末深夜'},
      summary:{en:'Route 15 & industrial bypass exhaust bursts', ja:'第一京浜および環七合流部の深夜排気音'},
      en:'Broad multi-lane intersection of Route 15 and Kannana draws weekend motorcycle revving.',
      ja:'第一京浜と環七通りの大交差点付近での週末深夜の単車走行音。',
      tip:{en:'residential blocks east towards the onsen park are quiet', ja:'平和島公園・温泉側へ向かう街区は緑道で遮音'},
      tier:'E', src:'Ota precinct traffic report' }
  ],
  omorimachi: [
    { type:'yaki_imo', when:{en:'autumn/winter evenings 17:00–19:30',ja:'秋冬夕暮れ時'},
      summary:{en:'residential shōtengai seasonal vendor megaphones', ja:'住宅商店街の焼き芋・灯油巡回スピーカー'},
      en:'Shitamachi low-rise grid hears sweet-potato vendor calls echoing down narrow alleys.',
      ja:'下町の低層住宅街に響く季節の移動販売放送。',
      tip:{en:'elevated railway reconstruction eliminated all grade-crossing bells', ja:'京急本線高架化により踏切警報音は完全消滅'},
      tier:'E', src:'Ota ward acoustic logs' }
  ],
  umeyashiki: [
    { type:'yaki_imo', when:{en:'autumn/winter evenings 17:30–20:00',ja:'秋冬の夕方17時半〜20時'},
      summary:{en:'kerosene music chimes (Tooryanse) & yaki-imo calls', ja:'灯油巡回車のメロディ（通りゃんせ等）と焼き芋拡声器'},
      en:'Quintessential quiet Ota shitamachi backgrid: mobile kerosene delivery trucks and sweet potato vendors slowly circling narrow alleys.',
      ja:'大田区の静かな下町住宅街を巡回する灯油販売（メロディ音）と焼き芋屋の呼び声。',
      tip:{en:'one of the most peaceful night environments along the entire corridor', ja:'沿線屈指の夜間静けさ（夜間騒音指数5/5）'},
      tier:'E', src:'Ota ward acoustic survey' }
  ],
  kamata: [
    { type:'nomikai_rowdy', when:{en:'nightly 22:00–04:30 (peaks Friday/Saturday)',ja:'毎夜22時〜早朝4時半（週末ピーク）'},
      summary:{en:'Bourbon Road & East Exit midnight izakaya roar & touts', ja:'バーボンロード・東口歓楽街の泥酔客、客引き、早朝ゴミ出し'},
      en:'Dense nightlife maze: late-night street drinking, shouting along Bourbon Road, karaoke spillover, and morning glass disposal.',
      ja:'蒲田東口および西口バーボンロード周辺での深夜泥酔騒ぎ、客引き、カラオケ漏れ音。',
      tip:{en:'rentals situated 5+ minutes north or south in residential Hasunuma/Umeyashiki borders are serene', ja:'蓮沼方面または駅から徒歩5分以上離れると閑静な住宅街'},
      tier:'E', src:'Kamata police station blotter' },
    { type:'cult_religious', when:{en:'weekend afternoons & rush hour',ja:'土日午後および帰宅ラッシュ時'},
      summary:{en:'station plaza religious tracts & megaphone preaching', ja:'蒲田駅西口・東口前での宗教・思想街宣、ビラ配り'},
      en:'Loudspeaker preaching, fringe religious proselytizers, and political signature drives at both station plazas.',
      ja:'駅前広場でのハンドマイクによる宗教勧誘、政治街宣、署名活動の音。',
      tip:{en:'sound dissolves as soon as you turn into the residential grid', ja:'駅前広場を抜ければ路地内には届かない'},
      tier:'E', src:'Ota ward civic feedback' }
  ],
  zoshiki: [
    { type:'yaki_imo', when:{en:'winter evenings',ja:'冬期の夕方'},
      summary:{en:'covered arcade buffer; back alley seasonal trucks', ja:'アーケード外縁部の移動販売スピーカー'},
      en:'The covered shōtengai blocks external street sounds; back residential lanes hear seasonal vendor trucks.',
      ja:'全長1kmのアーケード外側の住宅路地での焼き芋巡回。',
      tip:{en:'covered arcade keeps main pedestrian spine dry and tranquil', ja:'アーケード内は車道遮断で歩行環境極めて安全'},
      tier:'E', src:'Zoshiki merchant association' }
  ],
  rokugodote: [
    { type:'bosozoku', when:{en:'weekend nights 23:30–02:00',ja:'週末深夜'},
      summary:{en:'Route 15 Rokugo Bridge motorcycle throttle acceleration', ja:'国道15号六郷橋アプローチでの単車急加速音'},
      en:'Motorcycle riders open throttles as they cross the broad Tama River bridge between Tokyo and Kanagawa.',
      ja:'都県境の六郷橋を渡るバイクが橋梁手前でアクセルを開ける音。',
      tip:{en:'units facing south over the levee hear wind and water, shielded from bridge', ja:'土手直面の部屋は川風と自然音のみで橋梁音は遮断'},
      tier:'E', src:'Kanagawa-Tokyo border patrol' },
    { type:'yaki_imo', when:{en:'winter dusk',ja:'冬期の夕暮れ'},
      summary:{en:'levee neighborhood sweet-potato trucks', ja:'土手沿い住宅街の焼き芋巡回'},
      en:'Mobile stone-oven sweet potato trucks cruise along the levee perimeter road in winter.',
      ja:'堤防沿いの街区を流す焼き芋トラックの「いしや〜きいも〜」。',
      tip:{en:'river terrace is one of the corridor’s quietest residential pockets', ja:'土手沿いは遮るもののない静穏な住環境'},
      tier:'E', src:'Ota ward resident log' }
  ],
  kawasaki: [
    { type:'cult_religious', when:{en:'weekdays & weekend daytime near East Exit',ja:'平日夕方・土日昼間の東口'},
      summary:{en:'East Plaza religious recruiters, megaphone preachers & cult tracts', ja:'東口広場・京急川崎周辺の宗教街宣・カルト勧誘・マイク演説'},
      en:'High foot-traffic junction between JR and Keikyu sees frequent religious recruiters with portable PA amplifiers and cult outreach tables.',
      ja:'JRと京急の連絡動線・東口広場前での拡声器を使った宗教勧誘や政治演説。',
      tip:{en:'East Exit pedestrian corridors are heavily monitored; residential blocks south are unaffected', ja:'南側の住宅街区（貝塚・新川通方面）は至って静か'},
      tier:'E', src:'Kawasaki ward civic affairs' },
    { type:'nomikai_rowdy', when:{en:'nightly 21:00–04:00 (heavy in Nakacho/Isago)',ja:'毎夜21時〜深夜4時（仲町・砂子）'},
      summary:{en:'Gintengai & Isago drinking alley roar, touts & early deliveries', ja:'銀柳街・砂子歓楽街の泥酔客、客引き、早朝配送トラック'},
      en:'Kawasaki’s bustling entertainment quarter has intense late-night foot traffic, street banter, and motorcycle couriers.',
      ja:'仲町・砂子の飲食街での深夜歓声、客引き、飲食卸トラックの搬入音。',
      tip:{en:'live north along the Tama riverfront or west across the tracks for pure residential quiet', ja:'多摩川沿い（本町方面）や西口再開発エリアは防音・環境良好'},
      tier:'E', src:'Kawasaki police blotter' },
    { type:'daikoku_mod', when:{en:'Friday/Saturday midnights 23:00–02:00',ja:'金・土曜深夜'},
      summary:{en:'industrial bypass & Route 132 modified exhaust bursts', ja:'産業道路・国道132号の改造車・爆音排気音'},
      en:'Tuner cars and sports bikes accelerate along Route 132 towards the coastal industrial zone and Daikoku connector.',
      ja:'臨海部・大黒方面へ向かう国道132号・産業道路沿いでの排気音。',
      tip:{en:'avoid arterial frontage in the industrial transition zone', ja:'産業道路直面の物件を避け、内側の街区を選ぶ'},
      tier:'E', src:'Kanagawa police traffic dept' }
  ],
  hatcho: [
    { type:'daikoku_mod', when:{en:'weekend midnight hours',ja:'週末深夜'},
      summary:{en:'industrial bypass freight & modified car exhaust', ja:'産業道路沿いの大型貨物および改造車通過音'},
      en:'Freight transit and sports vehicles heading towards the industrial canal zone.',
      ja:'工業港湾部へ向かう産業道路沿いの通過音。',
      tip:{en:'residential blocks west of Hatchonawate station are insulated', ja:'駅西側の住宅街は静か'},
      tier:'E', src:'Kawasaki environmental monitoring' }
  ],
  tsurumi: [
    { type:'cult_religious', when:{en:'weekend daytime around West Exit',ja:'週末昼間の西口バスターミナル'},
      summary:{en:'Sōji-ji approach & station plaza religious leafleting', ja:'總持寺参道口・駅前広場での宗教系チラシ配布・街頭演説'},
      en:'Religious organizations and political groups frequently set up pamphlet stands and megaphones outside the West Exit transport terminal.',
      ja:'西口バスターミナル前での宗教団体・政治団体のビラ配りとマイク演説。',
      tip:{en:'noise is strictly confined to the bus rotary concourse', ja:'ロータリーを離れれば閑静な寺町と住宅街'},
      tier:'E', src:'Tsurumi ward open logs' },
    { type:'nomikai_rowdy', when:{en:'late evening 21:00–00:30',ja:'夜間21時〜終電'},
      summary:{en:'Tsurumi Ginza dining street evening banter', ja:'鶴見銀座商店街の居酒屋帰りの歓声'},
      en:'Post-work gatherings along the shotengai can be lively around last-train hours.',
      ja:'駅東口の飲食店街で終電前後の飲み会客の足音と歓声。',
      tip:{en:'residential blocks across the Tsurumi River in Honcho are quiet', ja:'本町・潮田方面は車通りも少なく落ち着いた住環境'},
      tier:'E', src:'Tsurumi station feedback' }
  ],
  ichiba: [
    { type:'yaki_imo', when:{en:'autumn/winter dusk',ja:'秋冬夕方'},
      summary:{en:'historic post-road quiet lanes & seasonal trucks', ja:'旧東海道歴史の道の静かな住宅街・季節巡回車'},
      en:'Ichirizuka historic post-road lanes experience almost no commercial noise; seasonal sweet-potato trucks visit.',
      ja:'一里塚周辺の歴史的住宅街。通過交通少なく夜間は極めて静か。',
      tip:{en:'peaceful low-density living between Tsurumi and Kawasaki', ja:'鶴見と川崎に挟まれた隠れた静穏街区'},
      tier:'E', src:'Tsurumi local history council' }
  ],
  kagetsu: [
    { type:'yaki_imo', when:{en:'winter evenings',ja:'冬期の夕暮れ'},
      summary:{en:'temple forest acoustic shadow & seasonal food calls', ja:'總持寺の杜の静寂と季節の巡回販売音'},
      en:'Sōji-ji’s massive cedar forest provides an acoustic barrier; quiet residential lanes hear occasional vendor trucks.',
      ja:'總持寺の広大な杜が外界の音を吸収。夕方に巡回トラックのメロディ。',
      tip:{en:'one of the greenest, quietest residential stops in Yokohama', ja:'横浜市内でも屈指の緑と静寂を誇る'},
      tier:'E', src:'Yokohama quietude survey' }
  ],
  namamugi: [
    { type:'daikoku_mod', when:{en:'Friday & Saturday midnights 23:00–02:30',ja:'金・土曜の深夜帯'},
      summary:{en:'Wangan & Daikoku connector tuner car acceleration rumble', ja:'大黒ふ頭・湾岸線合流部へ向かう改造車の重低音排気'},
      en:'Tuned sports cars and racing enthusiasts heading to Daikoku Parking Area produce deep bass exhaust pulses across coastal flyovers.',
      ja:'大黒PAへ向かう首都高・産業道路沿いでの改造車・チューニングカーの加速音。',
      tip:{en:'residential machiya west of the Keikyu tracks sit in a quiet acoustical shadow', ja:'京急線の西側（高台方面）の住宅地は静穏そのもの'},
      tier:'E', src:'Kanagawa expressway traffic monitoring' }
  ],
  shinkoyasu: [
    { type:'daikoku_mod', when:{en:'weekend midnight hours',ja:'週末深夜'},
      summary:'Route 357 & coastal highway tuner acceleration',
      summary:{en:'Route 357 & coastal highway tuner acceleration', ja:'国道357号・湾岸線方面の改造車加速音'},
      en:'Coastal highway overpasses hear exhaust notes from sports cars heading towards Daikoku Futo.',
      ja:'高速道路・国道357号沿いでの週末夜間の改造車通過音。',
      tip:{en:'residences up the hill toward Asahidai are insulated from coastal noise', ja:'旭台方面の高台住宅街は幹線音から隔絶'},
      tier:'E', src:'Kanagawa traffic police logs' }
  ],
  koyasu: [
    { type:'boat_diesel', when:{en:'dawn 04:45–06:15',ja:'早朝4時45分〜6時15分'},
      summary:{en:'commercial fishing skiff outboard motors along canal', ja:'漁港運河での船外機・小型ディーゼル船の始動音'},
      en:'Working fishing boats and eel skiffs maneuver along the canal at first light.',
      ja:'穴子漁などの小型漁船が早朝に水路を出発する際のエンジン音と波音。',
      tip:{en:'canal shacks have zero automotive traffic; water sounds dominate', ja:'水路沿いは車道がなく波音と鳥の声が中心'},
      tier:'E', src:'Koyasu fisher association' },
    { type:'train_viaduct', when:{en:'daytime through 00:00',ja:'日中〜終電'},
      summary:{en:'JR & Keikyu quadruple-track viaduct hum to the north', ja:'北側JR・京急複々線高架の通過音'},
      en:'Multi-track trunk rail corridor passes just north of the quarter.',
      ja:'北側を走るJR東海道線・京浜東北線・京急線の通過音。',
      tip:{en:'pick homes positioned south facing the canal', ja:'運河に面した南向きの部屋が快適'},
      tier:'E', src:'Kanagawa-ku acoustic records' }
  ],
  shimmachi: [
    { type:'bosozoku', when:{en:'sporadic weekend nights',ja:'週末深夜に散発'},
      summary:{en:'depot perimeter Route 15 straightaway revving', ja:'車庫外周・国道15号の直線での排気音'},
      en:'Wide Route 15 outside the Keikyu rail depot occasionally catches midnight motorcycle revving.',
      ja:'新町車庫前の第一京浜直線部での深夜の単車走行。',
      tip:{en:'backblocks toward the canals are buffered from the highway', ja:'運河側の裏通りは本線から遮音される'},
      tier:'E', src:'Kanagawa precinct notes' }
  ],
  hkanagawa: [
    { type:'nomikai_rowdy', when:{en:'evening last-train rush 22:30–00:30',ja:'終電前後の22時半〜0時半'},
      summary:{en:'two-terminal transfer pedestrian flow & evening izakaya banter', ja:'JR東神奈川〜京急東神奈川乗換通路の足音・飲食帰り歓声'},
      en:'Heavy pedestrian transfer seam between JR Higashi-Kanagawa and Keikyu; late-night dining patrons around the plaza.',
      ja:'JRと京急の乗換客の足音および駅前飲食店街の賑わい。',
      tip:{en:'choose rentals north towards Kanagawa Skate Rink or west on the residential slope', ja:'スケートリンク側や西側高台は静かな住環境'},
      tier:'E', src:'station seam pedestrian audit' }
  ],
  kanagawa: [
    { type:'bosozoku', when:{en:'weekend midnight 00:30–02:30',ja:'週末深夜'},
      summary:{en:'Kanagawa-juku post-road Route 15 slope acceleration', ja:'国道15号青木橋・青木通交差点での加速排気音'},
      en:'Route 15 climbs slightly as it approaches Aoki-bashi, prompting throttles from passing motorcycle groups.',
      ja:'青木橋手前の登り勾配で単車がスロットルを開ける音。',
      tip:{en:'homes up the historic Kanagawa-juku hill (Tammachi direction) are tranquil', ja:'反町方面へ登る歴史ある宿場坂上の街区は極めて静か'},
      tier:'E', src:'Kanagawa police records' }
  ],
  yokohama: [
    { type:'kart', when:{en:'daytime–dusk loops',ja:'日中〜夕方の周回'},
      summary:{en:'Minato Mirai public street-kart tour convoys', ja:'みなとみらい・赤レンガ方面を周回する公道カート'},
      en:'Costumed tour convoys loop Minato Mirai landmark boulevards on public roads with high-revving lawnmower-style engines.',
      ja:'コスプレ公道カートツアーがみなとみらい大通りを爆音で周回。',
      tip:{en:'kart loops stick to tourist boulevards; residential Portside is completely clear', ja:'ポートサイド地区や平沼方面はルート外で影響なし'},
      tier:'E', src:'operator listings (Street Kart Yokohama)' },
    { type:'daikoku_mod', when:{en:'weekend midnights 23:30–03:00',ja:'週末深夜'},
      summary:{en:'Wangan / K1 expressway modified sports car runs', ja:'首都高K1・湾岸線合流部でのルーレット族・改造車排気音'},
      en:'Modified sports cars and motorcycle groups revving along the elevated highway network heading towards Daikoku Futo.',
      ja:'首都高横羽線・湾岸線を走るルーレット族や旧車會の排気音が湾岸部高層階に反響。',
      tip:{en:'Kanagawa police run dedicated countermeasures desk (045-211-1212); high-rise apartments require double glazing', ja:'高層マンションはT-3/T-4等級の防音サッシ推奨。県警対策室（045-211-1212）'},
      tier:'V-mechanism / E-locale', src:'police.pref.kanagawa.jp' },
    { type:'nomikai_rowdy', when:{en:'nightly 21:00–04:00 (West Exit Minamisaiwai)',ja:'毎夜の西口南幸・鶴屋町'},
      summary:{en:'West Exit drinking alleys, touts & dawn station crowds', ja:'西口南幸・鶴屋町歓楽街の混雑、客引き、早朝の始発待ち'},
      en:'Massive mega-terminal entertainment quarter: dense bar alleys, street musicians, touts, and late-night revelry.',
      ja:'西口南幸・鶴屋町の居酒屋・クラブ街での深夜の喧騒と客引き。',
      tip:{en:'residential rentals situated east towards Takashimacho or north in Aoki-cho are peaceful', ja:'高島町方面や青木町・反町方面へ抜けると静穏'},
      tier:'E', src:'Yokohama Nishi police blotter' }
  ],
};
const NOISE_REPORT = {
  en:'Report/verify: Kanagawa Police bōsōzoku desk 045-211-1212 · Tokyo #9110 · ward noise-complaint open data — adapter queued',
  ja:'通報・確認：神奈川県警対策室 045-211-1212 · 警視庁 #9110 · 区の騒音苦情データ — アダプタ待ち',
};

/* ————— photo ops per station (tier E — spots + light orientation) and the
   premium-grocer indicator (Sophia: Seijo Ishii presence = refined-daily-life
   signal; store presence tier E, verify — locator adapter queued) ————— */
const PHOTO_OPS = {
  ningyocho:  {en:'Amazake Yokochō lanterns at blue hour · Suitengū vermillion detail shots', ja:'甘酒横丁のブルーアワー · 水天宮の朱'},
  hgashiginza:{en:'Kabukiza dusk facade · Ginza glass canyons bounce late light', ja:'歌舞伎座の黄昏 · 銀座の反射光'},
  daimon:     {en:'THE Tokyo Tower street alignment — sunset silhouette from Daimon crossing', ja:'大門交差点からの東京タワー正対 — 夕景シルエット'},
  sengakuji:  {en:'temple gate incense light, mornings · Gateway City glass at dusk', ja:'山門の朝光 · ゲートウェイの夕景'},
  kitashina:  {en:'Tennōzu boardwalk faces WEST over the canal — true golden hour water', ja:'天王洲は西向き — 運河の黄金時間'},
  shimbamba:  {en:'fuji-zuka summit mini-panorama at sunset', ja:'富士塚頂上の夕景'},
  tachiaigawa:{en:'boat basin morning light (bay east) · Ryōma at dawn', ja:'舟溜まりの朝光'},
  omorikaigan:{en:'bayside park sunrise · monorail streaks at dusk', ja:'海辺公園の朝日 · モノレールの流し'},
  kamata:     {en:'neon alleys after rain — close-up territory, not skylines', ja:'雨上がりのネオン路地'},
  rokugodote: {en:'full WEST sky over the Tama — the corridor’s most reliable golden hour', ja:'多摩川の西空 — 沿線一の夕焼け'},
  kawasaki:   {en:'factory night views (bus/cruise) · La Cittadella evening color', ja:'工場夜景 · チッタデッラの宵'},
  tsurumi:    {en:'Sōji-ji cedar shafts, early morning · Okinawa-town lantern rows', ja:'總持寺の朝の光条 · 仲通りの提灯'},
  namamugi:   {en:'brewery tanks + canal at dusk — industrial gold', ja:'工場と運河の夕景'},
  koyasu:     {en:'boat masts + canal reflections, morning mist — photographers’ quiet favorite', ja:'舟と運河の反射・朝靄'},
  yokohama:   {en:'ferris + towers face WEST over water — textbook golden hour from the harbor promenade', ja:'観覧車と西向きの海 — 教科書的黄金時間'},
};
const PREMIUM_GROCER = {
  nihombashi: {v:'Seijo Ishii (Coredo Muromachi ≈8′) + depachika belt', ja:'成城石井（コレド室町）＋デパ地下'},
  hgashiginza:{v:'Ginza depachika belt ≈6′ (Mitsukoshi/Matsuya)', ja:'銀座デパ地下圏'},
  shinagawa:  {v:'Seijo Ishii (ecute Shinagawa, in-station)', ja:'成城石井（エキュート品川）'},
  kamata:     {v:'Seijo Ishii (Granduo Kamata)', ja:'成城石井（グランデュオ蒲田）'},
  kawasaki:   {v:'Seijo Ishii (Atre Kawasaki)', ja:'成城石井（アトレ川崎）'},
  yokohama:   {v:'Seijo Ishii ×multiple (CIAL/Joinus) + depachika', ja:'成城石井 複数＋デパ地下'},
};

/* ————— senses: what the air does (tier E — verify with your own nose, by
   design) + rush-hour feel (crowd 1–5; line-level anchor: MLIT annual
   congestion survey puts the Keikyu main and Asakusa lines in the low-130s%
   band — among the gentler majors; MLIT adapter Q, JMA weather feed Q).
   Smell tags carry valence: + pleasant · − negative · ~ depends. ————— */
const SENSES = {
  ningyocho:  { smell:{en:'+incense · +soy broth from the counters · +coffee roaster', ja:'+線香 +出汁 +焙煎'}, breeze:'still', crowd:3, feel:{en:'subway cool below, calm lanes above; light rush', ja:'地下は涼しく路地は穏やか'} },
  nihombashi: { smell:{en:'+fresh coffee · ~bank-lobby AC wash', ja:'+コーヒー ~ビル空調'}, breeze:'canyon', crowd:3, feel:{en:'underground network keeps summer walks cool', ja:'地下網で夏も涼しい'} },
  takaracho:  { smell:{en:'+coffee · ~faint print-shop solvent memory', ja:'+コーヒー ~印刷の残り香'}, breeze:'canyon', crowd:3, feel:{en:'quiet platforms, easy boarding', ja:'ホーム静か・乗車楽'} },
  hgashiginza:{ smell:{en:'+dashi from soba counters · +theater-crowd perfume', ja:'+蕎麦出汁 +観劇の香水'}, breeze:'canyon', crowd:3, feel:{en:'cool subway; Ginza crowds stay outside the gates', ja:'地下は涼、混雑は地上'} },
  shimbashi:  { smell:{en:'~yakitori smoke + beer (evening) · −exhaust on the avenues', ja:'~焼き鳥と麦酒 −排気'}, breeze:'canyon', crowd:4, feel:{en:'JR-side crush at rush; Asakusa-line platform gentler', ja:'JR側は混雑、浅草線は緩い'} },
  daimon:     { smell:{en:'+Zōjō-ji incense · ~office AC gusts', ja:'+増上寺の線香 ~空調'}, breeze:'still', crowd:3, feel:{en:'two-line junction but rarely sweaty', ja:'乗換も汗ばまず'} },
  mita:       { smell:{en:'~ramen fat (Jirō pilgrims) · +student bakeries', ja:'~二郎の脂 +ベーカリー'}, breeze:'still', crowd:4, feel:{en:'Tamachi transfer adds a warm above-ground walk', ja:'田町乗換で地上歩き'} },
  sengakuji:  { smell:{en:'+temple incense · ~new-build concrete dust (Gateway works)', ja:'+線香 ~新築の粉塵'}, breeze:'hill', crowd:2, feel:{en:'boarding origin for many trains — seats happen', ja:'始発があり座れる'} },
  shinagawa:  { smell:{en:'~terminal AC + coffee chains · −brake-dust tang on JR decks', ja:'~空調とチェーン珈琲 −ブレーキ粉'}, breeze:'canyon', crowd:5, feel:{en:'the concourse is a hike — allow sweat minutes in August', ja:'コンコース長い — 8月は汗前提'} },
  kitashina:  { smell:{en:'+canal salt · +Tennōzu roastery drift', ja:'+運河の潮 +焙煎'}, breeze:'canal', crowd:2, feel:{en:'breezy platform, light loads', ja:'風あるホーム・空いてる'} },
  shimbamba:  { smell:{en:'+shrine cedar · +croquette oil from the shōtengai', ja:'+杜の杉 +コロッケ'}, breeze:'still', crowd:2, feel:{en:'local-stop calm', ja:'普通駅の穏やかさ'} },
  aomono:     { smell:{en:'+arcade croquettes · ~fishmonger morning', ja:'+コロッケ ~魚屋の朝'}, breeze:'still', crowd:3, feel:{en:'express stop without express crowds', ja:'優等停車でも混まず'} },
  samezu:     { smell:{en:'+sea salt · ~boat-fuel hint', ja:'+潮 ~船の燃料'}, breeze:'sea', crowd:2, feel:{en:'open-air platform, bay wind through', ja:'海風の通るホーム'} },
  tachiaigawa:{ smell:{en:'+tide flats · +grilled fish evenings', ja:'+干潟 +焼き魚'}, breeze:'sea', crowd:2, feel:{en:'sea breeze does the AC\'s job', ja:'海風が空調代わり'} },
  omorikaigan:{ smell:{en:'+proper sea breeze · +park green', ja:'+海風 +公園の緑'}, breeze:'sea', crowd:2, feel:{en:'coolest summer platform on the Tokyo side', ja:'都側で最も涼しいホーム'} },
  heiwajima:  { smell:{en:'−logistics diesel · +onsen sulfur hint (pleasant, oddly)', ja:'−物流ディーゼル +温泉の硫黄'}, breeze:'sea', crowd:3, feel:{en:'truck heat on the road, wind on the island edge', ja:'道路は熱く島縁は風'} },
  omorimachi: { smell:{en:'+sentō steam · ~motsuyaki smoke evenings', ja:'+銭湯の湯気 ~もつ焼きの煙'}, breeze:'still', crowd:2, feel:{en:'unhurried', ja:'急がない駅'} },
  umeyashiki: { smell:{en:'+taiyaki batter · +line-dried laundry', ja:'+たい焼き +洗濯物'}, breeze:'still', crowd:2, feel:{en:'garden pace even at 8am', ja:'朝8時も庭の速度'} },
  kamata:     { smell:{en:'+gyōza griddle · +kuroyu mineral · −dense arcade heat in August', ja:'+餃子の鉄板 +黒湯 −8月のアーケード熱'}, breeze:'still', crowd:4, feel:{en:'sweaty summer junction — the covered arcades trade sun for stuffiness', ja:'夏は蒸す乗換 — 屋根は日差しと引換に熱こもり'} },
  zoshiki:    { smell:{en:'+bakery mornings · +croquette afternoons', ja:'+朝のパン +昼のコロッケ'}, breeze:'still', crowd:3, feel:{en:'the arcade is a shaded, sweat-free walk to the platform', ja:'アーケードで汗いらずの駅前'} },
  rokugodote: { smell:{en:'+river grass · +weekend BBQ smoke (choose your wind)', ja:'+川の草 +週末のBBQ'}, breeze:'river', crowd:2, feel:{en:'levee wind cools the walk home', ja:'土手の風が帰路を冷やす'} },
  kawasaki:   { smell:{en:'~popcorn + izakaya smoke · −industrial whiff on a south wind', ja:'~ポップコーンと居酒屋 −南風の工場臭'}, breeze:'canyon', crowd:4, feel:{en:'terminal crowds; platforms outdoor and breezy', ja:'混むが屋外ホームは風通し'} },
  hatcho:     { smell:{en:'−truck exhaust · +soup from workers\' counters', ja:'−排気 +定食のスープ'}, breeze:'still', crowd:2, feel:{en:'two quiet platforms', ja:'静かな2面'} },
  ichiba:     { smell:{en:'+fresh tofu · +market greens', ja:'+豆腐 +青物'}, breeze:'still', crowd:2, feel:{en:'village boarding', ja:'村の乗車'} },
  tsurumi:    { smell:{en:'+Okinawa-soba broth · +sātā andagī fry', ja:'+沖縄そば +揚げ菓子'}, breeze:'still', crowd:3, feel:{en:'twin stations split the load', ja:'二駅で分散'} },
  kagetsu:    { smell:{en:'+cedar + incense off Sōji-ji', ja:'+杉と線香'}, breeze:'hill', crowd:1, feel:{en:'temple air, empty platform', ja:'寺の空気・空くホーム'} },
  namamugi:   { smell:{en:'+MALT — the Kirin brewery smell is famous · +dawn fish market · −metallic note on a south wind', ja:'+麦芽（キリンの香り） +朝の魚河岸 −南風の金属臭'}, breeze:'sea', crowd:2, feel:{en:'brewery wind beats the freight noise some evenings', ja:'夕方は麦芽の風'} },
  shinkoyasu: { smell:{en:'~bay wind + highway exhaust mix', ja:'~湾風と幹線排気'}, breeze:'sea', crowd:2, feel:{en:'windy decks; bring a jacket shoulder seasons', ja:'風強いデッキ'} },
  koyasu:     { smell:{en:'+tide + net tar · +morning fish landing', ja:'+潮と網のタール +朝の水揚げ'}, breeze:'sea', crowd:1, feel:{en:'the corridor\'s calmest boarding', ja:'沿線一穏やかな乗車'} },
  shimmachi:  { smell:{en:'~depot oil hint · +quiet-street mornings', ja:'~車庫の油 +静かな朝'}, breeze:'still', crowd:2, feel:{en:'originating trains = guaranteed seats', ja:'始発で必ず座れる'} },
  hkanagawa:  { smell:{en:'~konbini coffee + neutral urban', ja:'~コンビニ珈琲'}, breeze:'still', crowd:3, feel:{en:'transfer deck adds two warm minutes', ja:'乗換デッキで2分'} },
  kanagawa:   { smell:{en:'+soba broth · ~terminal spill', ja:'+蕎麦出汁'}, breeze:'still', crowd:2, feel:{en:'one modest platform beside a mega-hub', ja:'巨大駅の隣の小駅'} },
  yokohama:   { smell:{en:'+sea breeze channels the concourse · +Norengai bakery floors · −rush crush', ja:'+海風 +のれん街のパン −ラッシュ'}, breeze:'sea', crowd:5, feel:{en:'five-line crush at 8:30; the harbor wind waits outside', ja:'8時半は五社の圧・外は港風'} },
};

function areaFor(stationId){
  if (!stationId) return null;
  if (stationId === 'yokosuka' || stationId === 'yokosukachuo') {
    return {
      ward: { en: 'Yokosuka', ja: '横須賀市', souba: { '1R':54000, '1K':62000, '1DK':74000, '1LDK':98000, '2LDK':125000 }, src: 'https://www.homes.co.jp/chintai/kanagawa/yokosuka-city/price/' },
      st: { id: 'yokosuka', en: 'Yokosuka', ja: '横須賀', tier: 3, ward: 'kanagawa', hw: 10, num: 'KK59 / JR' },
      char: { en: 'Historic deepwater naval port & maritime gateway to the Miura Peninsula — Dobuita Street Americana, seaside parks, fresh Pacific seafood, and dramatic coastal ridges.', ja: '歴史ある軍港都市・三浦半島の海の玄関口。どぶ板通りの文化と海風、新鮮な三浦半島の魚介。' },
      style: { en: 'Ocean-facing hillside terraces, retro mid-century homes, and coastal residential apartments.', ja: '海を望む高台住宅、昭和レトロ住宅、臨海マンション。' },
      landmarks: { en: 'Mikasa Park · Dobuita Street · Yokosuka Naval Port · Sarushima Island', ja: '三笠公園 · どぶ板通り · 横須賀本港 · 猿島' },
      food: { en: 'Yokosuka Navy Burger, Kaigun Curry, Misaki tuna, and fresh port sashimi.', ja: '横須賀ネイビーバーガー · 海軍カレー · 三崎まぐろ · 地魚刺身' },
      hobby: { en: 'Naval port cruises, Sarushima island exploration, coastal sailing, and Miura peninsula cycling.', ja: '軍港めぐり · 猿島散策 · セーリング · 三浦半島ツーリング' },
      quiet: { v: 4, why: { en: 'sheltered coastal inlet with peaceful harbor nights away from central arteries', ja: '国道から離れた穏やかな港湾・閑静な夜' } },
      crime: { tier: 'E', en: 'Safe maritime community with close-knit neighborhood surveillance.', ja: '落ち着いた海辺の街、地域防犯が良好。' },
      air: { tier: 'P', band: 1, en: 'Crisp, salt-tinged Pacific ocean breeze and panoramic horizons.', ja: '澄み渡る太平洋の潮風と青空。' },
      people: { tier: 'E', foreign: '≈3%', en: 'Long-time coastal families, maritime personnel, and seaside lifestyle seekers.', ja: '地元定住層、海運・防衛関係、海暮らしを好む移住層。' },
      photoOps: { en: 'Warship Mikasa against Tokyo Bay at golden hour', ja: '夕暮れの記念艦三笠と東京湾' },
      senses: { breeze: 'sea', sound: 'ship horns · gentle harbor wash', light: 'unobstructed ocean horizon' },
      grocerPlus: null,
      uber: { thin: true },
      grocery: { tier: 'E', en: 'Seiyu mega-store, Keikyu Store, and harbor fishmonger stands.', ja: '西友横須賀店、京急ストア、港の鮮魚直売所。' },
      coffee: { tier: 'E', en: 'retro kissaten drip, American diner roasts, seaside terrace cafes.', ja: 'レトロ喫茶、アメリカンダイナー、海沿いテラスカフェ。' }
    };
  }
  const stList = typeof activeStations === 'function' ? activeStations() : STATIONS;
  const wards = typeof activeWards === 'function' ? activeWards() : WARDS;
  const st = stList.find(s => s.id === stationId) || (typeof S_IDX !== 'undefined' && STATIONS[S_IDX[stationId]]);
  if (!st) return null;
  const w = (typeof AREA_WARD !== 'undefined' && AREA_WARD[st.ward]) || {};
  const s = (typeof AREA_ST !== 'undefined' && AREA_ST[stationId]) || {};
  const n = (typeof NOISE_EVENTS !== 'undefined' && NOISE_EVENTS[stationId]) || null;
  return {
    ward: wards[st.ward] || WARDS[st.ward] || { en: st.ward, ja: st.ward, souba: {} },
    st,
    char: s.char || { en: `${st.en} neighborhood with balanced residential living and direct transit access.`, ja: `${st.ja}周辺の落ち着いた生活環境と便利なアクセス。` },
    style: s.style || { en: 'Low-to-mid rise residential rental apartments and residential homes.', ja: '中低層の賃貸マンションおよび住宅街。' },
    landmarks: s.landmarks || { en: `${st.en} Station Plaza`, ja: `${st.ja}駅前` },
    food: s.food || { en: 'Local bakeries, cafes, and neighborhood restaurants.', ja: '周辺のカフェ・ベーカリー・飲食店。' },
    hobby: s.hobby || { en: 'Walking greenways, local parks, and shopping streets.', ja: '緑道散策・公園・商店街。' },
    quiet: s.quiet || { v: st.tier === 3 ? 3 : 4, why: { en: st.tier === 3 ? 'bustling station plaza, calm residential blocks set 3′ back' : 'quiet residential enclave with low through-traffic', ja: st.tier === 3 ? '駅前は活気あり、3分入れば閑静' : '通過交通が少なく静穏な住宅街' } },
    crime: w.crime || { tier:'E', en:'Standard peaceful residential area safety.', ja:'平穏な住宅地治安。' },
    air: s.air || w.air || { tier:'P', band:1, en:'Good air quality with seasonal greenery.', ja:'緑豊かな良好な住環境。' },
    people: w.people || { tier:'E', en:'Local residents, professionals, and students.', ja:'落ち着いた地域住民・通勤層。' },
    noise: n,
    photoOps: (typeof PHOTO_OPS !== 'undefined' && PHOTO_OPS[stationId]) || { en: `${st.en} station streetscape at dusk`, ja: `${st.ja}の夕景` },
    senses: (typeof SENSES !== 'undefined' && SENSES[stationId]) || null,
    grocerPlus: (typeof PREMIUM_GROCER !== 'undefined' && PREMIUM_GROCER[stationId]) || null,
    uber: w.uber || { thin: false },
    grocery: w.grocery || { tier:'E', en:'Supermarkets and convenience stores nearby.', ja:'スーパー・ドラッグストアあり。' },
    coffee: s.coffee || w.coffee || null,
  };
}
