/* HomeTikki · KANTO — Pockets (Round 3).
   Neighborhood granularity below the station: the local gems. Each pocket
   carries a personality profile on 7 legible axes (0–5, tier E editorial —
   verify on foot, which is the point), its corridor access, and its rent
   context (ward souba, tier S). The matcher: your 9-to-5 sets the cage
   (commute gate + budget gate); your personality picks the perch.

   AXES: quiet 夜静 · old 昔の肌理 (old fabric) · intl 国際性 ·
         food 食 · craft 創作 · green 緑と水 · night 夜遊び
   offCorridor pockets are reachable gems, not corridor addresses — their
   access line says exactly how, and commute adds `extra` minutes (≈, tier E). */

const AXES = [
  { id:'quiet',   en:'Quiet nights',    ja:'夜の静けさ' },
  { id:'old',     en:'Old fabric',      ja:'昔の肌理' },
  { id:'intl',    en:'International',   ja:'国際性' },
  { id:'food',    en:'Food scene',      ja:'食' },
  { id:'refined', en:'Refined dining',  ja:'洗練' },
  { id:'craft',   en:'Craft & art',     ja:'創作' },
  { id:'green',   en:'Green & water',   ja:'緑と水' },
  { id:'photo',   en:'Photogenic',      ja:'映え' },
  { id:'night',   en:'Nightlife',       ja:'夜遊び' },
];

const POCKETS_R3 = [
{ id:'amazake', st:'ningyocho', ward:'chuo',
  name:{en:'Amazake Yokochō', ja:'甘酒横丁'},
  gem:{en:'The lane that kept its trades — doll-makers, tofu shops, the sweet-sake counter that named it. Central Tokyo at a walking pace.',
       ja:'職人の残る横丁 — 人形師、豆腐屋、甘酒。徒歩速度の中央区。'},
  noiseWatch:{en:'Noise watch: Weekend tourist foot-traffic & morning delivery trolleys on stone paving; quiet residential calm after 20:30 — pick a block set 1 lane back from Amazake Yokochō.',
              ja:'騒音注意：週末昼間の観光客歩行と石畳上の配送台車音。20時半以降は静寂 — 甘酒横丁から1本奥のブロックが理想。'},
  noiseSrc:'Chūō Ward Living Environment Guidelines · Amazake Yokochō Merchant Board',
  photoOp:{en:'lantern lanes + Meijiza marquee — best in blue hour; covered spots shrug off weather', ja:'提灯の路地と明治座 — ブルーアワーが最良'},
  ax:{quiet:4, old:5, intl:2, food:5, craft:4, green:2, night:2, refined:2, photo:3} },
{ id:'hamacho', st:'ningyocho', ward:'chuo',
  name:{en:'Hamachō riverside', ja:'浜町・隅田川べり'},
  gem:{en:'Sumida terrace runs, the park with the kabuki training hall, and BAUS-class new builds hiding on quiet blocks.',
       ja:'隅田川テラスと浜町公園。静かな街区に新築が潜む。'},
  noiseWatch:{en:'Noise watch: Occasional Sumida river tour boat wakes & Kiyosu-bashi traffic on breezy nights — residential blocks set back from the river promenade are remarkably peaceful.',
              ja:'騒音注意：隅田川遊覧船の通過波音と清洲橋の走行音 — リバーサイド道路から1ブロック入ると極めて静穏。'},
  noiseSrc:'Tokyo Metropolitan Bureau of Transportation Waterway Log · Chūō Ward Acoustic Survey',
  photoOp:{en:'Sumida terraces face EAST — sunrise water; Kiyosu-bashi blue hour', ja:'隅田川テラスは東向き — 朝焼けの水面'},
  ax:{quiet:4, old:3, intl:2, food:3, craft:3, green:4, night:1, refined:3, photo:3} },
{ id:'ginzaeast', st:'hgashiginza', ward:'chuo',
  name:{en:'Ginza East · Shintomi', ja:'銀座イースト・新富'},
  gem:{en:'Ginza\'s stagehands\' side: print shops, Michelin-cheap counters, Tsukiji breakfast next door — glamour\'s quiet service entrance.',
       ja:'銀座の楽屋口。印刷所と名カウンター、隣は築地。'},
  noiseWatch:{en:'Noise watch: Early morning Tsukiji market wholesale delivery vans (05:00) & tourist roller-luggage; quiet residential blocks in Shintomi and Tsukiji 2-chome.',
              ja:'騒音注意：早朝5時台の市場配送車輪音と観光客のスーツケース走行音 — 晴海通りから入った新富町・築地2丁目側は静寂。'},
  noiseSrc:'Tsukiji Outer Market Association · Chūō Ward Environmental Health Section',
  photoOp:{en:'Kabukiza facade at dusk + Ginza neon spill — golden hour bounces off tower glass', ja:'歌舞伎座の黄昏＋銀座のネオン'},
  ax:{quiet:3, old:3, intl:3, food:5, craft:3, green:1, night:3, refined:4, photo:4} },
{ id:'shimbamba', st:'shimbamba', ward:'shinagawa',
  name:{en:'Shimbamba shukuba lanes', ja:'新馬場・旧東海道'},
  gem:{en:'The first post town\'s grid survives: shrine forest, fuji-zuka summit, a shōtengai that still knows your order.',
       ja:'品川宿の街割りが残る。神社の杜と富士塚、顔なじみの商店街。'},
  noiseWatch:{en:'Noise watch: Winter evening yaki-imo trucks and daytime kerosene delivery chimes; Old Tokaido shukuba lanes are protected 1 block west of Route 15 arterial traffic.',
              ja:'騒音注意：秋冬夕方の焼き芋拡声器や冬の灯油販売メロディ。旧宿場町通りは第一京浜の1本裏手で自動車騒音は遮断。'},
  noiseSrc:'Shinagawa Shukuba-machi Historical Preservation Society · Shinagawa Police Blotter',
  photoOp:{en:'fuji-zuka summit: small skyline panorama at sunset; shrine forest soft light', ja:'富士塚頂上の夕景パノラマ'},
  ax:{quiet:4, old:5, intl:1, food:3, craft:3, green:3, night:2, refined:1, photo:3} },
{ id:'tennozu', st:'kitashina', ward:'shinagawa',
  name:{en:'Tennōzu canalside', ja:'天王洲・運河'},
  gem:{en:'Warehouse galleries, boardwalk brewery, water on three sides — Tokyo\'s closest thing to a harbor loft district, 8′ from the old road.',
       ja:'倉庫ギャラリーとボードウォーク。東京のハーバーロフト。'},
  noiseWatch:{en:'Noise watch: Weekend gallery crowds and summer evening canal patio restaurant chatter; nights are quiet waterfront air.',
              ja:'騒音注意：週末のギャラリー来訪者や夏の運河沿いテラスの賑わい。夜間は波音と水辺の静けさのみ。'},
  noiseSrc:'Tennōzu Canalside Revitalization Council · Shinagawa Bay Ward Environmental Bureau',
  photoOp:{en:'boardwalk + warehouse murals face WEST across the canal — true golden-hour water', ja:'ボードウォークは西向き — 運河の黄金時間'},
  ax:{quiet:3, old:1, intl:4, food:3, craft:5, green:4, night:2, refined:4, photo:5} },
{ id:'tachiai', st:'tachiaigawa', ward:'shinagawa',
  name:{en:'Tachiaigawa boat basin', ja:'立会川・舟溜まり'},
  gem:{en:'Working boats inside the megacity, Ryōma\'s statue on the corner, haze-fishing skippers who\'ll talk tides.',
       ja:'都会の中の現役漁港。龍馬像とハゼ釣り船。'},
  noiseWatch:{en:'Noise watch: Early dawn fishing skiff diesel motor idles from the quayside (05:00) and evening neighborhood vendor chimes; pedestrian river greenway has zero car traffic.',
              ja:'騒音注意：早朝5時台の釣り船・遊漁船のディーゼル始動音と夕方の巡回アナウンス。緑道沿いは車両進入不可で静か。'},
  noiseSrc:'Tokyo Fishing Vessel Port Management Office · Tachiaigawa Neighborhood Association',
  photoOp:{en:'boat basin catches MORNING light (the bay is east); Ryōma statue at dawn', ja:'舟溜まりは朝光（海は東）'},
  ax:{quiet:4, old:4, intl:1, food:4, craft:2, green:4, night:1, refined:1, photo:3} },
{ id:'umeyashiki', st:'umeyashiki', ward:'ota',
  name:{en:'Umeyashiki back grid', ja:'梅屋敷・裏路地'},
  gem:{en:'The plum-garden pace two stops from the junction: croquette queues, kuroyu sentō, laundry-line quiet by ten.',
       ja:'梅園の速度。コロッケと黒湯、22時には洗濯物の静けさ。'},
  noiseWatch:{en:'Noise watch: Quintessential shitamachi residential grid: mobile kerosene delivery chimes in winter and evening sweet-potato calls; zero through-traffic — night-quiet score 5/5.',
              ja:'騒音注意：下町の静かな住宅街特有の灯油販売メロディ（冬期）と夕方の焼き芋屋の呼び声。通り抜け車両なく夜間極めて静穏（静けさ5/5）。'},
  noiseSrc:'Ōta Ward Environmental Noise Monitoring Map · Umeyashiki Merchant Cooperative',
  photoOp:{en:'plum park in February; otherwise a lived-in grid, not a shot list', ja:'2月の梅園以外は生活の街'},
  ax:{quiet:5, old:4, intl:1, food:3, craft:2, green:2, night:1, refined:1, photo:2} },
{ id:'kamataeast', st:'kamata', ward:'ota',
  name:{en:'Kamata east maze', ja:'蒲田東口・迷路'},
  gem:{en:'Gyōza pilgrimage grid, 24h shōtengai, bars that never learned to close — the corridor\'s loudest good time.',
       ja:'餃子の巡礼路と閉まらない酒場。沿線一の夜。'},
  noiseWatch:{en:'Noise watch: High-energy nightlife quarter: post-midnight nomikai revellers, gyoza alley kitchen exhaust fans, touts, and 04:00 glass bottle recycling disposal — choose apartments north near Hasunuma.',
              ja:'騒音注意：歓楽街騒音：深夜の泥酔客・歓声、餃子街の排気ファン、客引き、早朝4時の空き瓶回収音 — 蓮沼寄りの住宅街区を推奨。'},
  noiseSrc:'Kamata Police Station Blotter · Bourbon Road Izakaya Union · Ōta Ward Civic Affairs',
  photoOp:{en:'neon alley close-ups after rain; no sky to speak of', ja:'雨上がりのネオン接写'},
  ax:{quiet:1, old:3, intl:3, food:5, craft:2, green:1, night:5, refined:1, photo:2} },
{ id:'rokugo', st:'rokugodote', ward:'ota',
  name:{en:'Rokugō levee terrace', ja:'六郷土手・河岸段丘'},
  gem:{en:'The Tama river as front yard: levee sunsets, weekend baseball leagues, Kawasaki\'s lights across the water.',
       ja:'多摩川が庭。土手の夕焼けと草野球。'},
  noiseWatch:{en:'Noise watch: Seasonal winter winds whistling across the Tama river levee; late-night motorcycle throttles crossing Rokugo Bridge — riverbank terrace itself is shielded.',
              ja:'騒音注意：冬場の堤防の強い川風と、深夜の六郷橋を渡る単車の加速音 — 土手沿い内側の住宅街は静穏。'},
  noiseSrc:'MLIT Keihin River Office · Tokyo-Kanagawa Border Police Patrol Blotter',
  photoOp:{en:'the levee owns a full WEST sky — the corridor’s most reliable golden hour', ja:'土手は西空を独占 — 沿線一の夕焼け'},
  ax:{quiet:4, old:2, intl:1, food:2, craft:1, green:5, night:1, refined:1, photo:4} },
{ id:'daishi', st:'kawasaki', ward:'kawasaki',
  name:{en:'Daishi shōtengai', ja:'大師の門前町'},
  gem:{en:'Temple-gate commerce that predates the railway (the railway was built FOR it): kuzumochi shops, darumas, New Year crowds, year-round calm.',
       ja:'鉄道より古い門前町。くず餅とだるま、正月以外は静か。'},
  noiseWatch:{en:'Noise watch: Monthly temple fair days (21st) bring dense crowds and megaphone announcements; rhythmic wooden candy-chopping knife beats along the approach.',
              ja:'騒音注意：毎月21日の大師縁日や初詣時の大混雑・拡声器案内、仲見世でのとんとこ飴を切るリズミカルな包丁の音。'},
  noiseSrc:'Kawasaki Daishi Heikenji Temple Event Log · Kawasaki Ward Town Planning Office',
  photoOp:{en:'temple gates + incense smoke shafts, mornings; New Year lanterns', ja:'山門と線香の光条（朝）'},
  ax:{quiet:3, old:5, intl:2, food:4, craft:3, green:2, night:2, refined:2, photo:4} },
{ id:'nakadori', st:'tsurumi', ward:'tsurumi',
  name:{en:'Okinawa-town Nakadōri', ja:'沖縄タウン仲通り'},
  gem:{en:'Three generations of Okinawan Yokohama: soba houses, sanshin classes, Latin-American grocers sharing the street — the corridor\'s richest food story.',
       ja:'三世代の沖縄横浜。そばと三線、南米食材店。'},
  noiseWatch:{en:'Noise watch: Weekend evening Ryukyu restaurant chatter and live sanshin lute music spilling from open doorways; weeknights are quiet canal-breeze living.',
              ja:'騒音注意：週末夜の沖縄料理店からの三線生演奏や笑い声。平日の夜は運河風の吹く落ち着いた住宅街。'},
  noiseSrc:'Yokohama Okinawa Fellowship Society · Tsurumi Nakadōri Merchant Association',
  photoOp:{en:'street-culture portraits, Eisā season; lantern rows at dusk', ja:'エイサーと提灯の通り'},
  ax:{quiet:3, old:4, intl:5, food:5, craft:3, green:1, night:3, refined:2, photo:3} },
{ id:'koyasu', st:'koyasu', ward:'kanagawaku',
  name:{en:'Koyasu fishing canal', ja:'子安・漁師運河'},
  gem:{en:'The last working boat canal on this shore — net sheds, anago mornings, and new 1Rs at ¥65K six minutes away.',
       ja:'現役最後の漁師運河。穴子の朝と6.5万の新築1R。'},
  noiseWatch:{en:'Noise watch: Early morning fishing skiff outboard motors along the canal and railway viaduct hum to the north; stilt shacks themselves have no road traffic.',
              ja:'騒音注意：早朝の漁船・作業船の船外機音と、北側京急・JR高架の通過音。水路沿いは車道がなく自動車騒音ゼロ。'},
  noiseSrc:'Koyasu Fishery Cooperative · Kanagawa Ward Waterfront Preservation Registry',
  photoOp:{en:'boat masts + canal reflections — photographers’ quiet favorite; morning mist', ja:'舟と運河の反射 — 朝靄'},
  ax:{quiet:5, old:5, intl:1, food:3, craft:2, green:4, night:1, refined:1, photo:4} },
{ id:'kagurazaka', st:'nihombashi', ward:'chuo', off:true, extra:10,
  how:{en:'Tōzai line from Nihombashi, 3 stops (≈8′) + the slope', ja:'日本橋から東西線3駅＋坂'},
  name:{en:'Kagurazaka', ja:'神楽坂'},
  gem:{en:'Geisha-lane cobbles turned bistro slope — French kitchens in machiya bones, printemps festivals, cats on temple walls.',
       ja:'花街の石畳がビストロの坂に。町家のフレンチと寺の猫。'},
  noiseWatch:{en:'Noise watch: Heavy weekend tourist foot-traffic and loud suitcase wheels rattling over steep stone staircases (ishidatami); black-fence geisha alleys turn silent after 22:00.',
              ja:'騒音注意：週末昼間の観光混雑と、石段（石畳）上のキャリーケース車輪音。黒塀の路地奥は22時以降極めて静か。'},
  noiseSrc:'Shinjuku Ward Historic Preservation Guidelines · Kagurazaka Dōri Promotion Association',
  photoOp:{en:'cobbled kakurenbo lanes — lantern dusk is the famous shot; the slope faces WEST', ja:'石畳の路地 — 夕方の提灯が定番'},
  ax:{quiet:3, old:4, intl:4, food:5, craft:4, green:2, night:3, refined:5, photo:5} },
{ id:'kyojima', st:'ningyocho', ward:'chuo', off:true, extra:15,
  how:{en:'through-train north to Oshiage (≈9′) + 12′ walk into the lanes', ja:'直通で押上へ＋徒歩12分'},
  name:{en:'Kyōjima · Kirakira Tachibana', ja:'京島・キラキラ橘'},
  gem:{en:'Pre-war lanes that dodged every fire and planner — now artists\' studios between grandmother-run shops. Tokyo\'s most loved surviving fabric.',
       ja:'戦災も再開発も免れた路地。祖母の店と作家のアトリエ。'},
  noiseWatch:{en:'Noise watch: Winter fire-patrol wooden clappers (hyoshigi 21:00), roving yaki-imo trucks, and close neighbor alley conversations through timber walls.',
              ja:'騒音注意：冬期夜間の火の用心（拍子木）、焼き芋屋の拡声器、木造密集地特有の路地会話の抜け音。車の走行音はほぼ皆無。'},
  noiseSrc:'Sumida Ward Disaster-Resistant Wood Grid Audit · Kyōjima 3-chome Neighborhood Council',
  photoOp:{en:'retro lanes + Skytree juxtaposition — a photographer pilgrimage; late sun rakes the alleys', ja:'レトロ路地とスカイツリーの対比'},
  ax:{quiet:4, old:5, intl:2, food:3, craft:5, green:1, night:2, refined:2, photo:4} },
{ id:'koganecho', st:'yokohama', ward:'nishi', off:true, extra:4,
  how:{en:'Keikyu 2 stops past Yokohama (Hinodechō · Koganechō)', ja:'京急で横浜から2駅'},
  name:{en:'Koganechō arts district', ja:'黄金町・アートの高架下'},
  gem:{en:'Studios and micro-galleries built into the Keikyu girders along the Ōoka river — a red-light past deliberately repainted by artists. Rough, cheap, alive.',
       ja:'京急高架下のスタジオ群。大岡川沿い、安くて生きている。'},
  noiseWatch:{en:'Noise watch: Elevated Keikyu railway rumble directly overhead along the viaduct; art festival crowd buzz on autumn weekends.',
              ja:'騒音注意：高架直下の京急線通過音と振動、秋の黄金町バザール等アート祭開催時の人通り。'},
  noiseSrc:'Koganechō Area Management Center · Keikyu Railway Noise Mitigation Desk',
  photoOp:{en:'girder-art underpasses + Ōoka river; SPRING: cherry tunnel over the water', ja:'高架下アートと大岡川 — 春は桜のトンネル'},
  ax:{quiet:2, old:3, intl:3, food:3, craft:5, green:2, night:4, refined:2, photo:4} },
{ id:'minatomirai', st:'yokohama', ward:'nishi', off:true, extra:5,
  how:{en:'Minatomirai line 1 stop, or a 12′ harbor walk', ja:'みなとみらい線1駅／徒歩12分'},
  name:{en:'Minato Mirai', ja:'みなとみらい'},
  gem:{en:'The planned skyline that actually works: harbor air, museum ships, ferris glow in your window — newest fabric on the whole map.',
       ja:'計画都市の成功例。港の空気と観覧車の光。'},
  noiseWatch:{en:'Noise watch: Weekend afternoon street-kart convoys circling tourist landmarks; late-night tuner car and motorcycle exhaust echoes off highway flyovers (Kanagawa Police desk 045-211-1212).',
              ja:'騒音注意：週末昼間の観光公道カート周回と、深夜の首都高・臨港幹線での改造車・単車排気音（県警対策室 045-211-1212）。'},
  noiseSrc:'Kanagawa Prefectural Police Countermeasures Desk (045-211-1212) · Yokohama Minato Mirai 21 Charter',
  photoOp:{en:'THE skyline: ferris + towers face WEST over water — textbook golden hour, crowds included', ja:'観覧車と西向きの海 — 教科書的黄金時間'},
  ax:{quiet:2, old:0, intl:4, food:3, craft:2, green:4, night:3, refined:4, photo:5} },
{ id:'noge', st:'yokohama', ward:'nishi', off:true, extra:5,
  how:{en:'1 stop to Hinodechō, or a 10′ walk from Yokohama', ja:'日ノ出町1駅／徒歩10分'},
  name:{en:'Noge', ja:'野毛'},
  gem:{en:'Six hundred tiny bars on the hill behind the terminal — jazz kissa, horumon smoke, Yokohama\'s honest nightcap since 1945.',
       ja:'終戦から続く600軒の飲み屋町。ジャズ喫茶とホルモン。'},
  noiseWatch:{en:'Noise watch: Classic post-war izakaya soundscape: boisterous street drinking until 03:00, jazz bar bass, kitchen clatter, and dawn bottle-crate collection.',
              ja:'騒音注意：戦後闇市由来の飲み屋街騒音：深夜3時までの泥酔歓声、ジャズ喫茶のベース音、早朝のビールケース回収作業。'},
  noiseSrc:'Noge Food & Beverage Association · Yokohama Nishi Police Precinct',
  photoOp:{en:'lantern alleys at night — handheld, high-ISO territory', ja:'夜の提灯横丁'},
  ax:{quiet:1, old:4, intl:2, food:5, craft:3, green:1, night:5, refined:2, photo:3} },
];

/* persona picker: 6 fast either/or cards; each answer nudges axes.
   Reaction-weighted like the Radio — a fast call counts full. */
const PQ = [
 { q:{en:'Friday, 9pm. Where are you?', ja:'金曜21時、どこにいる？'},
   a:{t:{en:'Counter seat in a loud yokochō', ja:'にぎやかな横丁のカウンター'}, d:{night:2, food:1, quiet:-2} },
   b:{t:{en:'Window open — cicadas, a far-off train', ja:'窓を開けて、蝉と遠い電車の音'}, d:{quiet:2, green:1, night:-1} } },
 { q:{en:'Morning ritual?', ja:'朝の習慣は？'},
   a:{t:{en:'Kissaten morning set, same master', ja:'いつもの喫茶店のモーニング'}, d:{old:2, food:1} },
   b:{t:{en:'Flat white to go, new roaster monthly', ja:'テイクアウトのフラットホワイト'}, d:{intl:2, craft:1} } },
 { q:{en:'Ideal Sunday?', ja:'理想の日曜は？'},
   a:{t:{en:'Flea market, then a workshop visit', ja:'蚤の市と工房めぐり'}, d:{craft:2, old:1} },
   b:{t:{en:'Harbor run, then a museum', ja:'港ランと美術館'}, d:{green:2, intl:1} } },
 { q:{en:'Default dinner?', ja:'ふだんの夕食は？'},
   a:{t:{en:'Shōtengai croquette + standing soba', ja:'商店街コロッケと立ち食い蕎麦'}, d:{food:1, old:2, refined:-2} },
   b:{t:{en:'Natural-wine bistro, chef talks', ja:'自然派ワインのビストロ'}, d:{intl:2, night:1, refined:2} } },
 { q:{en:'Neighbors should…', ja:'ご近所とは…'},
   a:{t:{en:'Know my name and my order', ja:'名前も注文も覚えてほしい'}, d:{old:2, quiet:1} },
   b:{t:{en:'Nod politely and forget me', ja:'会釈だけの距離感がいい'}, d:{intl:1, night:1} } },
 { q:{en:'The street outside should be…', ja:'家の前の道は…'},
   a:{t:{en:'Laundry lines, potted gardens, cats', ja:'洗濯物と鉢植えと猫'}, d:{old:2, green:1, quiet:1} },
   b:{t:{en:'Glass, water, skyline', ja:'ガラスと水面とスカイライン'}, d:{intl:2, green:1} } },
 { q:{en:'Golden hour hits. You…', ja:'黄金時間。あなたは…'},
   a:{t:{en:'Already at the spot — I planned around it', ja:'もう撮影地にいる — 計画済み'}, d:{photo:2, green:1} },
   b:{t:{en:'Notice it from wherever I already am', ja:'いる場所から眺めるだけ'}, d:{photo:-1, quiet:1} } },
 { q:{en:'Your grocery basket…', ja:'買い物カゴは…'},
   a:{t:{en:'Seijo Ishii organic labels — I read ingredients', ja:'成城石井のオーガニック — 原材料を読む'}, d:{refined:2, intl:1} },
   b:{t:{en:'Shōtengai greengrocer — I read the auntie’s mood', ja:'商店街の八百屋 — おばちゃんの機嫌を読む'}, d:{old:2, refined:-1, food:1} } },
];

function pocketCommute(p, destId){
  const c = (typeof calcCommute === 'function') ? calcCommute(p.st, destId) : ((typeof commute === 'function') ? commute(p.st, destId) : { median: null });
  if (!c || c.median == null) {
    return { median: null, p90: null, transfers: 0, direct: false, approx: true, walkOnly: false };
  }
  const extra = p.extra || 3;                 // on-corridor pockets: ~3′ walk pad
  return { median: r5(c.median + extra), p90: r5(c.p90 + extra),
           transfers: c.transfers, direct: c.direct, approx: !!p.off, walkOnly: false };
}
function pocketFit(p, u, touched){
  const keys = AXES.map(a=>a.id).filter(k => touched.has(k));
  if (!keys.length) return null;
  let dist = 0;
  for (const k of keys) dist += Math.abs((u[k] ?? 2.5) - (p.ax?.[k] ?? 3));
  return Math.round(100 * (1 - dist / (5 * keys.length)));
}
