/* HomeTikki · KANTO — Lines topology (Multi-Corridor Architecture).
   The thesundaydata reading, applied to rail: "Same corridor, two readings.
   The Corridor preserves the full ledger; Topology shows the network grouping
   and lets you trace one line at a time." Node size = impact (express tier +
   connections). The path is editorial, not a route map.
   Station-structure facts are real and checkable (tier E — ODPT adapter
   queued for scheduled-service confirmation). walk>0 = out-of-station
   transfer on foot, minutes typical. */

const TOPO_LINES = {
  // Main corridors
  keikyu:      { en:'Keikyu Main', ja:'京急本線', color:'#c73e3a', group:'corridor',
                 sig:{en:'the coastal surface half — Shinagawa to Yokohama and beyond', ja:'沿線の地上側 — 品川から横浜以遠へ'} },
  asakusa:     { en:'Toei Asakusa', ja:'都営浅草線', color:'#e85298', group:'corridor',
                 sig:{en:'the subway through-run half — Sengakuji north through Ginza', ja:'沿線の地下鉄側 — 泉岳寺から浅草・押上へ直通'} },
  toyoko:      { en:'Tōkyū Tōyoko', ja:'東急東横線', color:'#da0442', group:'corridor',
                 sig:{en:'premier culture & lifestyle railway connecting Shibuya to Yokohama', ja:'渋谷から横浜へ — 屈指の洗練を誇る生活幹線'} },
  hibiya:      { en:'Tokyo Metro Hibiya', ja:'東京メトロ日比谷線', color:'#9caeb7', group:'corridor',
                 sig:{en:'central diplomatic, art, and dining diagonal (Ebisu·Roppongi·Ginza·Ueno)', ja:'六本木・銀座・上野を対角線に結ぶ都心回廊'} },
  denentoshiLine: { en:'Tōkyū Den-en-toshi', ja:'東急田園都市線', color:'#20a288', group:'corridor',
                 sig:{en:'western Tokyo garden-city corridor connecting Shibuya to Futako & Aoba hills', ja:'渋谷から世田谷、多摩川、青葉の丘陵へ'} },
  odakyuLine:  { en:'Odakyū Odawara', ja:'小田急小田原線', color:'#1067b8', group:'corridor',
                 sig:{en:'western Tokyo cultural & residential corridor from Shinjuku through Shimokita to Machida', ja:'新宿から下北沢・成城学園前を経て町田・箱根へ'} },

  // Branches & Feeder Lines
  kkAirport:   { en:'Keikyu Airport Line', ja:'京急空港線', color:'#c73e3a', group:'air', dash:true,
                 sig:{en:'Haneda in ~11′ from Kamata — the corridor\'s superpower', ja:'蒲田から羽田へ約11分'} },
  kkDaishi:    { en:'Keikyu Daishi Line', ja:'京急大師線', color:'#c73e3a', group:'corridor', dash:true,
                 sig:{en:'four-stop feeder into Keikyū Kawasaki; the cheap-rent shelf', ja:'京急川崎への支線 — 家賃の棚'} },
  odakyuTama:  { en:'Odakyū Tama Line', ja:'小田急多摩線', color:'#1067b8', group:'corridor', dash:true,
                 sig:{en:'Shin-Yurigaoka branch into Tama New Town & Tama Center', ja:'新百合ヶ丘から多摩センター・唐木田方面へ'} },
  enoshima:    { en:'Odakyū Enoshima', ja:'小田急江ノ島線', color:'#1067b8', group:'private',
                 sig:{en:'direct rail connection to Katase-Enoshima coast and Fujisawa', ja:'藤沢・片瀬江ノ島海岸へ直通'} },

  // Metro Network
  chiyoda:     { en:'Tokyo Metro Chiyoda', ja:'東京メトロ千代田線', color:'#00bb85', group:'metro',
                 sig:{en:'direct through-run from Yoyogi-Uehara to Kasumigaseki & Ōtemachi', ja:'代々木上原から表参道・大手町へ直通'} },
  ginza:       { en:'Tokyo Metro Ginza', ja:'東京メトロ銀座線', color:'#f39700', group:'metro',
                 sig:{en:'Shibuya↔Asakusa, the oldest subway line in Asia', ja:'渋谷↔浅草・アジア最古の地下鉄'} },
  marunouchi:  { en:'Tokyo Metro Marunouchi', ja:'東京メトロ丸ノ内線', color:'#e60012', group:'metro',
                 sig:{en:'U-shaped trunk linking Shinjuku, Ginza, and Tokyo Station', ja:'新宿・銀座・東京駅を結ぶU字幹線'} },
  tozai:       { en:'Tokyo Metro Tōzai', ja:'東京メトロ東西線', color:'#00a7db', group:'metro',
                 sig:{en:'east–west commuter artery to Nihombashi & Ōtemachi', ja:'東西通勤の大動脈'} },
  hanzomon:    { en:'Tokyo Metro Hanzōmon', ja:'東京メトロ半蔵門線', color:'#8f76d6', group:'metro',
                 sig:{en:'Den-en-toshi through-run into Omotesandō, Nagatachō, and Ōtemachi', ja:'田園都市線直通で表参道・永田町・大手町へ'} },
  fukutoshin:  { en:'Tokyo Metro Fukutoshin', ja:'東京メトロ副都心線', color:'#9c5a32', group:'metro',
                 sig:{en:'Tōyoko through-run to Shinjuku-sanchōme & Ikebukuro', ja:'東横線直通で新宿三丁目・池袋へ'} },
  oedo:        { en:'Toei Ōedo', ja:'都営大江戸線', color:'#ce045b', group:'metro',
                 sig:{en:'the deep loop — Roppongi·Shinjuku without surface congestion', ja:'六本木・新宿・大門を結ぶ環状地下鉄'} },
  mitaLine:    { en:'Toei Mita', ja:'都営三田線', color:'#0079c2', group:'metro',
                 sig:{en:'Ōtemachi & Sugamo government corridor', ja:'大手町・日比谷・三田を結ぶ'} },
  toeiShinjuku:{ en:'Toei Shinjuku', ja:'都営新宿線', color:'#6cbb5a', group:'metro',
                 sig:{en:'cross-town route to Ichigaya, Jinbōchō, and Motoyawata', ja:'新宿から市ヶ谷・神保町方面へ'} },

  // JR Trunk Lines
  yamanote:    { en:'JR Yamanote', ja:'JR山手線', color:'#9acd32', group:'jr',
                 sig:{en:'the central circular railway looping Tokyo\'s primary hubs', ja:'東京の主要拠点を結ぶ都心環状線'} },
  chuo:        { en:'JR Chūō Line', ja:'JR中央線快速', color:'#f15a22', group:'jr',
                 sig:{en:'east–west speed run: Tokyo, Shinjuku, Nakano, and Kichijōji', ja:'東京・新宿・中野・吉祥寺を一直線に結ぶ快速'} },
  saikyo:      { en:'JR Saikyō Line', ja:'JR埼京線', color:'#00ac9a', group:'jr',
                 sig:{en:'rapid north–south bypass: Ōmiya through Ikebukuro, Shinjuku, Shibuya & Osaki', ja:'大宮から池袋・新宿・渋谷・大崎を結ぶ南北幹線'} },
  shonanShinjuku: { en:'JR Shōnan-Shinjuku', ja:'JR湘南新宿ライン', color:'#e21f26', group:'jr',
                 sig:{en:'direct high-speed bypass connecting Shinjuku, Shibuya, Musashi-Kosugi, Yokohama, Kamakura, and Zushi', ja:'新宿・渋谷・武蔵小杉・横浜・鎌倉・逗子を直結する快速'} },
  keihin:      { en:'JR Keihin-Tōhoku', ja:'JR京浜東北線', color:'#00b2e5', group:'jr',
                 sig:{en:'heavy rail artery parallel to Tokyo Bay — Ōmiya to Yokohama & Ōfuna', ja:'大宮から東京・品川・川崎を経て横浜・大船へ'} },
  negishi:     { en:'JR Negishi Line', ja:'JR根岸線', color:'#00a3da', group:'jr',
                 sig:{en:'harbor loop linking Yokohama to Sakuragichō, Kannai, Motomachi, and Ōfuna', ja:'横浜から桜木町・関内・元町中華街・大船を結ぶ臨海幹線'} },
  tokaido:     { en:'JR Tōkaidō', ja:'JR東海道線', color:'#f68b1e', group:'jr',
                 sig:{en:'express heavy rail — Shimbashi·Shinagawa·Kawasaki·Yokohama only', ja:'快速の幹 — 停車駅少・高速輸送'} },
  yokosuka:    { en:'JR Yokosuka', ja:'JR横須賀線', color:'#007ac0', group:'jr',
                 sig:{en:'deep concourse route connecting Tokyo, Shinagawa, Musashi-Kosugi, Yokohama to Kamakura, Zushi & Yokosuka', ja:'東京・品川・武蔵小杉・横浜から鎌倉・逗子・横須賀へ直通'} },
  keikyuSouth: { en:'Keikyu Main (South extension)', ja:'京急本線（横須賀・三浦方面）', color:'#c73e3a', group:'corridor',
                 sig:{en:'direct rapid limited express to Kami-Ōoka, Kanazawa-Hakkei, Yokosuka-Chūō, and Misakiguchi', ja:'横浜から上大岡・金沢八景・横須賀中央・三崎口へ直通快特'} },
  nambu:       { en:'JR Nambu', ja:'JR南武線', color:'#ffd400', group:'jr',
                 sig:{en:'crescent connector linking Kawasaki, Musashi-Kosugi, Noborito & Tachikawa', ja:'川崎・武蔵小杉・登戸・立川を結ぶ東西バイパス'} },
  yokohamaLine:{ en:'JR Yokohama Line', ja:'JR横浜線', color:'#7fbe42', group:'jr',
                 sig:{en:'cross-suburban link from Higashi-Kanagawa & Kikuna to Machida & Hachiōji', ja:'東神奈川・菊名から新横浜・町田・八王子へ'} },
  joban:       { en:'JR Jōban', ja:'JR常磐線', color:'#007ac0', group:'jr',
                 sig:{en:'Kita-Senju to Ueno, Tokyo, and Shinagawa', ja:'北千住から上野・東京・品川へ直通'} },
  shinkansen:  { en:'Tōkaidō / JR Shinkansen', ja:'新幹線', color:'#1c3f94', group:'jr',
                 sig:{en:'high-speed bullet trains from Shinagawa, Tokyo, or Shin-Yokohama', ja:'品川・東京・新横浜からの新幹線幹線'} },
  tsurumiLine: { en:'JR Tsurumi Line', ja:'JR鶴見線', color:'#8fbe00', group:'jr',
                 sig:{en:'industrial waterfront branch connecting Keihin port basins', ja:'京浜臨海部の運河と工業地帯を結ぶ枝線'} },

  // Private Rail & Suburban Links
  inokashira:  { en:'Keiō Inokashira', ja:'京王井の頭線', color:'#1d2088', group:'private',
                 sig:{en:'Shibuya in 4′ & Kichijōji in 16′ directly from Shimokitazawa', ja:'下北沢から渋谷へ4分・吉祥寺へ16分'} },
  keio:        { en:'Keiō Line', ja:'京王線', color:'#dd0077', group:'private',
                 sig:{en:'Shinjuku trunk to Sasazuka, Meidaimae, Chōfu, and Hachiōji', ja:'新宿から笹塚・明大前・調布方面へ'} },
  setagayaLine:{ en:'Tōkyū Setagaya Tram', ja:'東急世田谷線', color:'#f7b52c', group:'private',
                 sig:{en:'heritage tramway through Setagaya between Sangenjaya and Gōtokuji', ja:'三軒茶屋と豪徳寺（山下）を結ぶ世田谷の路面電車'} },
  oimachi:     { en:'Tōkyū Ōimachi', ja:'東急大井町線', color:'#f5a200', group:'private',
                 sig:{en:'connecting Futako-Tamagawa, Jiyūgaoka, and Ōimachi', ja:'二子玉川・自由が丘・大井町を結ぶ横断線'} },
  meguroLine:  { en:'Tōkyū Meguro', ja:'東急目黒線', color:'#009cd3', group:'private',
                 sig:{en:'direct subway through-run from Hiyoshi and Den-en-chōfu to Mita & Namboku lines', ja:'日吉・田園調布から目黒・三田線・南北線へ直通'} },
  shinYokohamaLine: { en:'Tōkyū Shin-Yokohama', ja:'東急新横浜線', color:'#862594', group:'private',
                 sig:{en:'Hiyoshi direct to Shin-Yokohama Shinkansen in 6 minutes', ja:'日吉から新横浜新幹線へ6分直結'} },
  minatomirai: { en:'Minatomirai Line', ja:'みなとみらい線', color:'#09357f', group:'private',
                 sig:{en:'Tōyoko through-run under Yokohama harbor to Chinatown & Motomachi', ja:'横浜からみなとみらい・元町中華街へ直通'} },
  sotetsu:     { en:'Sōtetsu Line', ja:'相鉄線', color:'#0074be', group:'private',
                 sig:{en:'connecting Yokohama to western Kanagawa valleys', ja:'横浜から海老名・湘南台方面へ'} },
  blueLine:    { en:'Yokohama Blue Line', ja:'横浜市営ブルーライン', color:'#1d64ac', group:'private',
                 sig:{en:'Yokohama subway connecting Azamino, Shin-Yokohama, and Yokohama station', ja:'あざみ野・新横浜・横浜・関内を結ぶ地下鉄'} },
  greenLine:   { en:'Yokohama Green Line', ja:'横浜市営グリーンライン', color:'#008e48', group:'private',
                 sig:{en:'subway link from Hiyoshi to Hiyoshihonchō (2′) and Kohoku New Town', ja:'日吉から日吉本町（2分）・港北ニュータウン方面を結ぶ地下鉄'} },
  tobu:        { en:'Tōbu Skytree Line', ja:'東武スカイツリーライン', color:'#1f3d8a', group:'private',
                 sig:{en:'Kita-Senju to Asakusa, Skytree, and Saitama', ja:'北千住からスカイツリー・浅草・埼玉方面へ'} },
  tsukuba:     { en:'Tsukuba Express', ja:'つくばエクスプレス', color:'#002060', group:'private',
                 sig:{en:'high-speed 130 km/h run: Akihabara to Kita-Senju and Tsukuba Science City', ja:'秋葉原・北千住からつくばへ最速快速'} },
  yurikamome:  { en:'Yurikamome', ja:'ゆりかもめ', color:'#29a8dc', group:'metro',
                 sig:{en:'waterfront elevated transit through Odaiba', ja:'新橋・汐留からお台場臨海部へ'} },
  monorail:    { en:'Tokyo Monorail', ja:'東京モノレール', color:'#f5a200', group:'air',
                 sig:{en:'Hamamatsuchō direct to Haneda Airport terminals', ja:'浜松町から羽田空港へ直結'} },
  ikegami:     { en:'Tōkyū Ikegami Line', ja:'東急池上線', color:'#ee7800', group:'private',
                 sig:{en:'Kamata through quiet residential pockets to Gotanda', ja:'蒲田から池上・雪が谷大塚を経て五反田へ'} },
  tamagawaLine:{ en:'Tōkyū Tamagawa Line', ja:'東急多摩川線', color:'#a63d76', group:'private',
                 sig:{en:'connecting Kamata along the Tama River to Tamagawa (transfer to Tōyoko & Meguro lines)', ja:'蒲田から多摩川沿いに多摩川駅へ'} },
};

/* per-corridor-station connections. walk 0 = same station complex.
   hubs = onward destinations that highlight why the connection matters. */
const TOPO_CONN = {
  // === KEIKYU / ASAKUSA CORRIDOR ===
  ningyocho:        [ { l:'hibiya', walk:0, hubs:[{en:'Ginza',ja:'銀座'},{en:'Roppongi',ja:'六本木'},{en:'Ueno',ja:'上野'}] } ],
  nihombashi:       [ { l:'ginza', walk:0, hubs:[{en:'Shibuya',ja:'渋谷'},{en:'Asakusa',ja:'浅草'}] },
                      { l:'tozai', walk:0, hubs:[{en:'Ōtemachi',ja:'大手町'},{en:'Nakano',ja:'中野'}] } ],
  takaracho:        [],
  hgashiginza:      [ { l:'hibiya', walk:0, hubs:[{en:'Ginza (1 stop)',ja:'銀座まで1駅'},{en:'Tsukiji',ja:'築地'}] } ],
  shimbashi:        [ { l:'yamanote', walk:0, hubs:[{en:'Tokyo',ja:'東京'},{en:'Shibuya',ja:'渋谷'}] },
                      { l:'keihin', walk:0, hubs:[{en:'Akihabara',ja:'秋葉原'}] },
                      { l:'tokaido', walk:0, hubs:[{en:'Yokohama fast',ja:'横浜速達'}] },
                      { l:'yokosuka', walk:0, hubs:[{en:'Kamakura',ja:'鎌倉'}] },
                      { l:'ginza', walk:0, hubs:[{en:'Shibuya',ja:'渋谷'}] },
                      { l:'yurikamome', walk:0, hubs:[{en:'Odaiba',ja:'お台場'}] } ],
  daimon:           [ { l:'oedo', walk:0, hubs:[{en:'Roppongi',ja:'六本木'},{en:'Shinjuku',ja:'新宿'}] },
                      { l:'yamanote', walk:3, via:{en:'Hamamatsuchō',ja:'浜松町'}, hubs:[{en:'Tokyo',ja:'東京'}] },
                      { l:'monorail', walk:3, via:{en:'Hamamatsuchō',ja:'浜松町'}, hubs:[{en:'Haneda',ja:'羽田'}] } ],
  mita:             [ { l:'mitaLine', walk:0, hubs:[{en:'Ōtemachi',ja:'大手町'}] },
                      { l:'yamanote', walk:3, via:{en:'Tamachi',ja:'田町'}, hubs:[{en:'Tokyo',ja:'東京'}] },
                      { l:'keihin', walk:3, via:{en:'Tamachi',ja:'田町'}, hubs:[] } ],
  sengakuji:        [ { l:'yamanote', walk:6, via:{en:'Takanawa Gateway',ja:'高輪GW'}, hubs:[{en:'Gateway City',ja:'ゲートウェイシティ'}] } ],
  shinagawa:        [ { l:'yamanote', walk:0, hubs:[{en:'Shibuya 12′',ja:'渋谷12分'},{en:'Shinjuku 19′',ja:'新宿19分'},{en:'Tokyo 11′',ja:'東京11分'}] },
                      { l:'keihin', walk:0, hubs:[{en:'Tokyo',ja:'東京'},{en:'Kawasaki',ja:'川崎'}] },
                      { l:'tokaido', walk:0, hubs:[{en:'Kawasaki 8′',ja:'川崎8分'},{en:'Yokohama 17′',ja:'横浜17分'},{en:'Odawara',ja:'小田原'}] },
                      { l:'yokosuka', walk:0, hubs:[{en:'Yokohama 17′',ja:'横浜17分'},{en:'Kamakura 48′',ja:'鎌倉48分'},{en:'Zushi 53′',ja:'逗子53分'},{en:'Yokosuka 66′',ja:'横須賀66分'}] },
                      { l:'shinkansen', walk:0, hubs:[{en:'Nagoya 1h16',ja:'名古屋1時間16分'},{en:'Kyoto 2h07',ja:'京都2時間7分'}] } ],
  kitashina: [], shimbamba: [], aomono: [], samezu: [], tachiaigawa: [],
  omorikaigan: [], heiwajima: [], omorimachi: [], umeyashiki: [],
  kamata:           [ { l:'kkAirport', walk:0, hubs:[{en:'Haneda T1·T2·T3 (11′)',ja:'羽田空港11分'}] },
                      { l:'nambu', walk:9, via:{en:'JR Kamata',ja:'JR蒲田'}, hubs:[{en:'Kawasaki',ja:'川崎'}] },
                      { l:'keihin', walk:9, via:{en:'JR Kamata',ja:'JR蒲田'}, hubs:[{en:'Shinagawa',ja:'品川'},{en:'Yokohama',ja:'横浜'}] },
                      { l:'ikegami', walk:9, via:{en:'Tōkyū Kamata',ja:'東急蒲田'}, hubs:[{en:'Ikegami 4′',ja:'池上4分'},{en:'Gotanda 25′',ja:'五反田25分'}] },
                      { l:'tamagawaLine', walk:9, via:{en:'Tōkyū Kamata',ja:'東急蒲田'}, hubs:[{en:'Tamagawa 11′',ja:'多摩川11分'}] } ],
  zoshiki: [], rokugodote: [],
  kawasaki:         [ { l:'kkDaishi', walk:0, hubs:[{en:'Kawasaki Daishi',ja:'川崎大師'}] },
                      { l:'tokaido', walk:7, via:{en:'JR Kawasaki',ja:'JR川崎'}, hubs:[{en:'Tokyo 18′',ja:'東京18分'}] },
                      { l:'keihin', walk:7, via:{en:'JR Kawasaki',ja:'JR川崎'}, hubs:[] },
                      { l:'nambu', walk:7, via:{en:'JR Kawasaki',ja:'JR川崎'}, hubs:[{en:'Musashi-Kosugi',ja:'武蔵小杉'}] } ],
  hatcho:           [ { l:'nambu', walk:0, hubs:[{en:'Shitte branch',ja:'尻手・支線'}] } ],
  ichiba: [],
  tsurumi:          [ { l:'keihin', walk:6, via:{en:'JR Tsurumi',ja:'JR鶴見'}, hubs:[] },
                      { l:'tsurumiLine', walk:6, via:{en:'JR Tsurumi',ja:'JR鶴見'}, hubs:[{en:'Umi-Shibaura',ja:'海芝浦'}] } ],
  kagetsu: [], namamugi: [], shinkoyasu: [], koyasu: [], shimmachi: [],
  hkanagawa:        [ { l:'keihin', walk:3, via:{en:'JR Higashi-Kanagawa',ja:'JR東神奈川'}, hubs:[] },
                      { l:'yokohamaLine', walk:3, via:{en:'JR Higashi-Kanagawa',ja:'JR東神奈川'}, hubs:[{en:'Shin-Yokohama',ja:'新横浜'}] } ],
  kanagawa: [],
  yokohama:         [ { l:'yokosuka', walk:0, hubs:[{en:'Kamakura 24′',ja:'鎌倉24分'},{en:'Zushi 29′',ja:'逗子29分'},{en:'Yokosuka 42′',ja:'横須賀42分'},{en:'Kurihama 53′',ja:'久里浜53分'}] },
                      { l:'keikyuSouth', walk:0, hubs:[{en:'Kami-Ōoka 8′',ja:'上大岡8分'},{en:'Kanazawa-Hakkei 18′',ja:'金沢八景18分'},{en:'Yokosuka-Chūō 26′',ja:'横須賀中央26分'},{en:'Misakiguchi 48′',ja:'三崎口48分'}] },
                      { l:'tokaido', walk:0, hubs:[{en:'Shinagawa 17′',ja:'品川17分'},{en:'Tokyo 26′',ja:'東京26分'},{en:'Odawara 54′',ja:'小田原54分'},{en:'Atami',ja:'熱海'}] },
                      { l:'shonanShinjuku', walk:0, hubs:[{en:'Shibuya 25′',ja:'渋谷25分'},{en:'Shinjuku 30′',ja:'新宿30分'},{en:'Ikebukuro 36′',ja:'池袋36分'},{en:'Zushi 31′',ja:'逗子31分'}] },
                      { l:'toyoko', walk:0, hubs:[{en:'Musashi-Kosugi 13′',ja:'武蔵小杉13分'},{en:'Jiyūgaoka 17′',ja:'自由が丘17分'},{en:'Shibuya 25′',ja:'渋谷25分'},{en:'Shinjuku-sanchōme 30′',ja:'新宿三丁目30分'}] },
                      { l:'minatomirai', walk:0, hubs:[{en:'Minatomirai 3′',ja:'みなとみらい3分'},{en:'Chinatown (Motomachi) 8′',ja:'元町・中華街8分'}] },
                      { l:'keihin', walk:0, hubs:[{en:'Kawasaki 12′',ja:'川崎12分'},{en:'Shinagawa 29′',ja:'品川29分'},{en:'Tokyo 38′',ja:'東京38分'}] },
                      { l:'negishi', walk:0, hubs:[{en:'Sakuragichō 3′',ja:'桜木町3分'},{en:'Kannai 5′',ja:'関内5分'},{en:'Ishikawachō 7′',ja:'石川町7分'},{en:'Ōfuna 30′',ja:'大船30分'}] },
                      { l:'sotetsu', walk:0, hubs:[{en:'Futamatagawa 11′',ja:'二俣川11分'},{en:'Ebina 26′',ja:'海老名26分'},{en:'Shōnandai',ja:'湘南台'}] },
                      { l:'blueLine', walk:0, hubs:[{en:'Shin-Yokohama (Shinkansen) 11′',ja:'新横浜（新幹線）11分'},{en:'Azamino 28′',ja:'あざみ野28分'}] } ],

  // === ODAKYŪ CORRIDOR ===
  shinjuku:         [ { l:'yamanote', walk:0, hubs:[{en:'Shibuya 5′',ja:'渋谷5分'},{en:'Ikebukuro 8′',ja:'池袋8分'},{en:'Tokyo 14′',ja:'東京14分'}] },
                      { l:'chuo', walk:0, hubs:[{en:'Tokyo 14′ (rapid)',ja:'東京14分（中央特快）'},{en:'Kichijōji 14′',ja:'吉祥寺14分'}] },
                      { l:'saikyo', walk:0, hubs:[{en:'Ebisu',ja:'恵比寿'},{en:'Ōmiya',ja:'大宮'}] },
                      { l:'shonanShinjuku', walk:0, hubs:[{en:'Shibuya 5′',ja:'渋谷5分'},{en:'Yokohama 30′',ja:'横浜30分'},{en:'Kamakura 57′',ja:'鎌倉57分'},{en:'Zushi 63′',ja:'逗子63分'},{en:'Odawara',ja:'小田原'}] },
                      { l:'marunouchi', walk:0, hubs:[{en:'Ginza 16′',ja:'銀座16分'},{en:'Tokyo Stn',ja:'東京駅'}] },
                      { l:'toeiShinjuku', walk:0, hubs:[{en:'Jinbōchō',ja:'神保町'},{en:'Ichigaya',ja:'市ヶ谷'}] },
                      { l:'oedo', walk:0, hubs:[{en:'Roppongi 9′',ja:'六本木9分'}] },
                      { l:'keio', walk:0, hubs:[{en:'Chōfu',ja:'調布'},{en:'Takao-san',ja:'高尾山'}] } ],
  minamishinjuku:   [ { l:'yamanote', walk:5, via:{en:'JR Yoyogi',ja:'JR代々木'}, hubs:[{en:'Shinjuku 2′',ja:'新宿2分'},{en:'Shibuya 5′',ja:'渋谷5分'}] } ],
  sangubashi:       [],
  yoyogihachiman:   [ { l:'chiyoda', walk:1, via:{en:'Yoyogi-Kōen',ja:'代々木公園'}, hubs:[{en:'Omotesandō 4′',ja:'表参道4分'},{en:'Kasumigaseki 10′',ja:'霞ケ関10分'}] } ],
  yoyogiuehara:     [ { l:'chiyoda', walk:0, hubs:[{en:'Omotesandō 5′',ja:'表参道5分'},{en:'Kasumigaseki 11′',ja:'霞ケ関11分'},{en:'Ōtemachi 16′',ja:'大手町16分'}] } ],
  higashikitazawa:  [],
  shimokitazawa:    [ { l:'inokashira', walk:0, hubs:[{en:'Shibuya 4′ (exp)',ja:'渋谷4分（急行）'},{en:'Kichijōji 16′',ja:'吉祥寺16分'},{en:'Meidaimae 3′',ja:'明大前3分'}] } ],
  setagayadaita:    [],
  umegaoka:         [],
  gotokuji:         [ { l:'setagayaLine', walk:0, via:{en:'Yamashita',ja:'山下駅'}, hubs:[{en:'Sangen-jaya',ja:'三軒茶屋'},{en:'Shimotakaido',ja:'下高井戸'}] } ],
  kyodo:            [],
  chitosefunabashi: [],
  soshigayadaikura: [],
  seijogakuenmae:   [],
  kitami:           [],
  komae:            [],
  izumitamagawa:    [],
  noborito:         [ { l:'nambu', walk:0, hubs:[{en:'Musashi-Kosugi 16′',ja:'武蔵小杉16分'},{en:'Kawasaki 28′',ja:'川崎28分'},{en:'Tachikawa 24′',ja:'立川24分'}] } ],
  mukogaokayuen:    [],
  shinurigaoka:     [ { l:'odakyuTama', walk:0, hubs:[{en:'Tama Center',ja:'多摩センター'},{en:'Karakida',ja:'唐木田'}] } ],
  machida:          [ { l:'yokohamaLine', walk:0, hubs:[{en:'Shin-Yokohama (Shinkansen) 19′',ja:'新横浜（新幹線）19分'},{en:'Hachiōji 25′',ja:'八王子25分'},{en:'Yokohama 29′',ja:'横浜29分'}] } ],

  // === TŌYOKO CORRIDOR ===
  shibuya:          [ { l:'yamanote', walk:0, hubs:[{en:'Shinjuku 5′',ja:'新宿5分'},{en:'Tokyo 18′',ja:'東京18分'}] },
                      { l:'saikyo', walk:0, hubs:[{en:'Ikebukuro',ja:'池袋'},{en:'Ōmiya',ja:'大宮'}] },
                      { l:'shonanShinjuku', walk:0, hubs:[{en:'Yokohama 25′',ja:'横浜25分'},{en:'Kamakura 52′',ja:'鎌倉52分'},{en:'Zushi 58′',ja:'逗子58分'}] },
                      { l:'ginza', walk:0, hubs:[{en:'Omotesandō 2′',ja:'表参道2分'},{en:'Ginza 15′',ja:'銀座15分'}] },
                      { l:'fukutoshin', walk:0, hubs:[{en:'Shinjuku-sanchōme 5′',ja:'新宿三丁目5分'},{en:'Ikebukuro 12′',ja:'池袋12分'}] },
                      { l:'inokashira', walk:0, hubs:[{en:'Shimokitazawa 4′',ja:'下北沢4分'},{en:'Kichijōji 16′',ja:'吉祥寺16分'}] },
                      { l:'denentoshiLine', walk:0, hubs:[{en:'Sangen-jaya 5′',ja:'三軒茶屋5分'},{en:'Futako-Tamagawa 11′',ja:'二子玉川11分'}] } ],
  daikanyama:       [],
  nakameguro:       [ { l:'hibiya', walk:0, hubs:[{en:'Ebisu 2′',ja:'恵比寿2分'},{en:'Roppongi 8′',ja:'六本木8分'},{en:'Ginza 18′',ja:'銀座18分'}] } ],
  yutenji:          [],
  gakugeidaigaku:   [],
  toritsudaigaku:   [],
  jiyugaoka:        [ { l:'oimachi', walk:0, hubs:[{en:'Futako-Tamagawa 6′',ja:'二子玉川6分'},{en:'Ōimachi 15′',ja:'大井町15分'}] } ],
  denenchofu:       [ { l:'meguroLine', walk:0, hubs:[{en:'Meguro',ja:'目黒'},{en:'Mita',ja:'三田'}] } ],
  tamagawa:         [ { l:'meguroLine', walk:0, hubs:[{en:'Meguro',ja:'目黒'}] } ],
  shinnmaruko:      [],
  musashikosugi:    [ { l:'nambu', walk:0, hubs:[{en:'Kawasaki 9′',ja:'川崎9分'},{en:'Tachikawa',ja:'立川'}] },
                      { l:'yokosuka', walk:4, hubs:[{en:'Shinagawa 10′',ja:'品川10分'},{en:'Tokyo 18′',ja:'東京18分'},{en:'Yokohama 11′',ja:'横浜11分'},{en:'Kamakura 35′',ja:'鎌倉35分'},{en:'Yokosuka 53′',ja:'横須賀53分'}] },
                      { l:'shonanShinjuku', walk:4, hubs:[{en:'Shibuya 13′',ja:'渋谷13分'},{en:'Shinjuku 18′',ja:'新宿18分'},{en:'Yokohama 11′',ja:'横浜11分'},{en:'Zushi 42′',ja:'逗子42分'}] },
                      { l:'meguroLine', walk:0, hubs:[{en:'Ōtemachi 25′',ja:'大手町25分'}] } ],
  motosumiyoshi:    [],
  hiyoshi:          [ { l:'meguroLine', walk:0, hubs:[{en:'Meguro',ja:'目黒'}] },
                      { l:'shinYokohamaLine', walk:0, hubs:[{en:'Shin-Yokohama (Shinkansen) 6′',ja:'新横浜（新幹線）6分'}] },
                      { l:'greenLine', walk:0, hubs:[{en:'Hiyoshihonchō 2′',ja:'日吉本町2分'},{en:'Center Kita/Minami',ja:'センター北・南'}] } ],
  tsunashima:       [],
  okurayama:        [],
  kikuna:           [ { l:'yokohamaLine', walk:0, hubs:[{en:'Shin-Yokohama (Shinkansen) 2′',ja:'新横浜2分'},{en:'Machida',ja:'町田'}] } ],
  myorenji: [], hakuraku: [], higashihakuraku: [], tammachi: [],

  // === HIBIYA CORRIDOR ===
  ebisu:            [ { l:'yamanote', walk:0, hubs:[{en:'Shibuya 2′',ja:'渋谷2分'},{en:'Shinjuku 9′',ja:'新宿9分'},{en:'Shinagawa 9′',ja:'品川9分'}] },
                      { l:'saikyo', walk:0, hubs:[{en:'Shinjuku',ja:'新宿'},{en:'Ōmiya',ja:'大宮'}] } ],
  hiroo:            [],
  roppongi:         [ { l:'oedo', walk:0, hubs:[{en:'Shinjuku 9′',ja:'新宿9分'},{en:'Daimon 6′',ja:'大門6分'}] } ],
  kamiyacho:        [],
  toranomonhills:   [ { l:'ginza', walk:3, via:{en:'Toranomon',ja:'虎ノ門'}, hubs:[{en:'Shibuya 11′',ja:'渋谷11分'},{en:'Ginza 4′',ja:'銀座4分'}] } ],
  kasumigaseki:     [ { l:'marunouchi', walk:0, hubs:[{en:'Tokyo Stn 5′',ja:'東京駅5分'},{en:'Shinjuku 12′',ja:'新宿12分'}] },
                      { l:'chiyoda', walk:0, hubs:[{en:'Omotesandō',ja:'表参道'},{en:'Ōtemachi',ja:'大手町'}] } ],
  hibiya:           [ { l:'chiyoda', walk:0, hubs:[{en:'Ōtemachi 2′',ja:'大手町2分'}] },
                      { l:'mitaLine', walk:0, hubs:[{en:'Meguro',ja:'目黒'},{en:'Mita',ja:'三田'}] },
                      { l:'yamanote', walk:3, via:{en:'JR Yūrakuchō',ja:'JR有楽町'}, hubs:[{en:'Tokyo 2′',ja:'東京2分'},{en:'Shinbashi',ja:'新橋'}] } ],
  ginza:            [ { l:'ginza', walk:0, hubs:[{en:'Shibuya 15′',ja:'渋谷15分'},{en:'Asakusa 17′',ja:'浅草17分'}] },
                      { l:'marunouchi', walk:0, hubs:[{en:'Tokyo Stn 3′',ja:'東京駅3分'},{en:'Ikebukuro',ja:'池袋'}] } ],
  tsukiji:          [],
  hatchobori:       [ { l:'tokaido', walk:0, none:true },
                      { l:'keihin', walk:0, none:true } ],
  kayabacho:        [ { l:'tozai', walk:0, hubs:[{en:'Ōtemachi 4′',ja:'大手町4分'},{en:'Nihombashi 2′',ja:'日本橋2分'}] } ],
  kodemmacho:       [],
  akihabara:        [ { l:'yamanote', walk:0, hubs:[{en:'Tokyo 4′',ja:'東京4分'},{en:'Ueno 3′',ja:'上野3分'}] },
                      { l:'keihin', walk:0, hubs:[{en:'Shinagawa',ja:'品川'}] },
                      { l:'tsukuba', walk:0, hubs:[{en:'Tsukuba 45′',ja:'つくば45分'}] } ],
  nakaokachimachi:  [ { l:'yamanote', walk:3, via:{en:'JR Okachimachi',ja:'JR御徒町'}, hubs:[] },
                      { l:'oedo', walk:2, via:{en:'Ueno-okachimachi',ja:'上野御徒町'}, hubs:[] } ],
  ueno:             [ { l:'yamanote', walk:0, hubs:[{en:'Tokyo 6′',ja:'東京6分'}] },
                      { l:'keihin', walk:0, hubs:[] },
                      { l:'ginza', walk:0, hubs:[{en:'Asakusa',ja:'浅草'},{en:'Ginza',ja:'銀座'}] },
                      { l:'shinkansen', walk:0, hubs:[{en:'Tōhoku / Jōetsu',ja:'東北・上越新幹線'}] } ],
  iriya: [], minowa: [],
  minamisenju:      [ { l:'joban', walk:0, hubs:[{en:'Ueno 6′',ja:'上野6分'}] },
                      { l:'tsukuba', walk:0, hubs:[{en:'Akihabara 7′',ja:'秋葉原7分'}] } ],
  kitasenju:        [ { l:'chiyoda', walk:0, hubs:[{en:'Ōtemachi 16′',ja:'大手町16分'}] },
                      { l:'joban', walk:0, hubs:[{en:'Ueno 10′',ja:'上野10分'},{en:'Tokyo 17′',ja:'東京17分'}] },
                      { l:'tobu', walk:0, hubs:[{en:'Skytree',ja:'スカイツリー'}] },
                      { l:'tsukuba', walk:0, hubs:[{en:'Akihabara 10′',ja:'秋葉原10分'}] } ],

  // === DEN-EN-TOSHI CORRIDOR ===
  ikejiriohashi:    [],
  sangenjaya:       [ { l:'setagayaLine', walk:0, hubs:[{en:'Gōtokuji',ja:'豪徳寺'},{en:'Shimotakaido',ja:'下高井戸'}] } ],
  komazawadaigaku:  [],
  sakurashinmachi:  [],
  yoga:             [],
  futakotamagawa:   [ { l:'oimachi', walk:0, hubs:[{en:'Jiyūgaoka 6′',ja:'自由が丘6分'},{en:'Ōimachi 18′',ja:'大井町18分'}] } ],
  futakoshinchi:    [],
  takatsu:          [],
  mizonokuchi:      [ { l:'nambu', walk:0, via:{en:'JR Musashi-Mizonokuchi',ja:'JR武蔵溝ノ口'}, hubs:[{en:'Kawasaki 20′',ja:'川崎20分'},{en:'Noborito 8′',ja:'登戸8分'}] } ],
  kajigaya: [], miyamaedaira: [], saginuma: [], tamaplaza: [],
  azamino:          [ { l:'blueLine', walk:0, hubs:[{en:'Shin-Yokohama (Shinkansen) 16′',ja:'新横浜（新幹線）16分'},{en:'Yokohama 27′',ja:'横浜27分'}] } ],
  eda: [], ichigao: [], fujigaoka: [], aobadai: [],
  nagatsuta:        [ { l:'yokohamaLine', walk:0, hubs:[{en:'Machida 5′',ja:'町田5分'},{en:'Shin-Yokohama 23′',ja:'新横浜23分'}] } ],
  chuorinkan:       [ { l:'enoshima', walk:0, hubs:[{en:'Fujisawa 20′',ja:'藤沢20分'},{en:'Shinjuku 40′',ja:'新宿40分'}] } ],
};

// Clean any omitted entries
Object.keys(TOPO_CONN).forEach(k => {
  TOPO_CONN[k] = (TOPO_CONN[k] || []).filter(c => !c.none);
});

function impact(stationId){
  const cData = (typeof getActiveCorridor === 'function') ? getActiveCorridor() : null;
  const stList = (cData && cData.stations) ? cData.stations : STATIONS;
  const st = stList.find(s => s.id === stationId) || (typeof S_IDX !== 'undefined' && STATIONS[S_IDX[stationId]]) || { tier: 1 };
  const conns = TOPO_CONN[stationId] || [];
  let sc = st.tier || 1;
  for (const c of conns) sc += c.walk === 0 ? 1 : 0.6;
  return Math.round(sc * 10) / 10;
}

const TOPO_GROUPS = [
  { id:'all',      en:'All lines',     ja:'全路線' },
  { id:'corridor', en:'Main Corridor', ja:'主要幹線' },
  { id:'jr',       en:'JR trunk',      ja:'JR幹線' },
  { id:'metro',    en:'Subway / Metro',ja:'地下鉄' },
  { id:'private',  en:'Private rail',  ja:'私鉄' },
  { id:'air',      en:'Airport ✈',     ja:'空港 ✈' },
];

