/* HomeTikki · KANTO — Multi-Corridor Data Architecture (Round 3)
   Corridors:
     1. keikyu:      Keikyu Main & Toei Asakusa Through-Run (Ningyōchō → Yokohama)
     2. toyoko:      Tōkyū Tōyoko Line (Shibuya → Yokohama)
     3. hibiya:      Tokyo Metro Hibiya Line (Naka-Meguro → Kita-Senju)
     4. denentoshi:  Tōkyū Den-en-toshi Line (Shibuya → Chūō-Rinkan)
     5. odakyu:      Odakyū Odawara Line (Shinjuku → Machida)
*/

const CORRIDORS_DATA = {
  keikyu: {
    id: 'keikyu',
    name: 'Keikyu',
    ja: '京急本線・都営浅草線',
    tag: 'Ningyōchō → Yokohama',
    desc: {
      en: 'Historic seaside corridor connecting Tokyo’s shitamachi core through Shinagawa, Kamata, and Kawasaki to Yokohama Harbor with rapid airport branches.',
      ja: '日本橋・銀座から品川・蒲田・川崎を経て横浜港へ。羽田空港直通、東海道の宿場町と下町情緒が息づくベイサイド幹線。'
    },
    color: 'var(--shu)',
    accent: '#e85298',
    badge: '⛩',
    goalMin: 26.5,
    zones: [
      { num:'01', en:'Shitamachi & Financial Core', ja:'下町・ビジネス中枢', stns:'Ningyōchō → Shimbashi', desc:{en:'Historic craft quarters, Kabukiza theater, and central business hubs.', ja:'人形師の路地、歌舞伎座、そして新橋・銀座の中枢。'} },
      { num:'02', en:'Canals & Post-Town Shukuba', ja:'運河と品川宿の街並み', stns:'Shinagawa → Tachiaigawa', desc:{en:'Old Tōkaidō merchant streets, boat basins, and Tennōzu warehouse lofts.', ja:'旧東海道の宿場町、舟溜まり、天王洲のロフト。'} },
      { num:'03', en:'Crafts & Airport Gateway', ja:'ものづくりと空港ゲートウェイ', stns:'Ōmorimachi → Rokugōdote', desc:{en:'Kuroyu onsen sentō, famous gyoza, and Tama river levee sunsets.', ja:'黒湯温泉、羽根つき餃子、多摩川の夕焼け。'} },
      { num:'04', en:'Industrial Waterfront & Harbor', ja:'臨海工業帯と横浜港', stns:'Kawasaki → Yokohama', desc:{en:'Okinawa-town food, fishing canal stilt shacks, and harbor skyline.', ja:'仲通りの沖縄食文化、子安の漁港、みなとみらい。'} },
    ]
  },

  toyoko: {
    id: 'toyoko',
    name: 'Tōyoko',
    ja: '東急東横線',
    tag: 'Shibuya → Yokohama',
    desc: {
      en: 'Tokyo’s premier lifestyle & cultural railway corridor connecting Shibuya’s creative core to Yokohama Harbor via Daikanyama, Naka-Meguro, and Jiyūgaoka.',
      ja: '渋谷のカルチャー拠点から代官山・中目黒・自由が丘を経て横浜港へ。首都圏屈指の人気を誇る洗練の生活幹線。'
    },
    color: '#da0442',
    accent: '#ff3366',
    badge: '🌸',
    goalMin: 25.0,
    zones: [
      { num:'01', en:'Creative Heights & Boutique Slopes', ja:'カルチャー中枢とカフェ坂', stns:'Shibuya → Naka-Meguro', desc:{en:'Independent fashion, river cherry blossoms, and design studios.', ja:'最先端のファッション、目黒川の桜並木、デザインスタジオ。'} },
      { num:'02', en:'Curated High-Streets & Cafes', ja:'活気ある商店街と洋菓子店', stns:'Yūtenji → Jiyūgaoka', desc:{en:'Twin shotengai, natural wine bars, and European pedestrian lanes.', ja:'学大の賑わい、自然派ワイン、自由が丘の石畳遊歩道。'} },
      { num:'03', en:'Garden Suburbs & Riverfront Levee', ja:'田園邸宅街と多摩川の風', stns:'Den-en-chōfu → Musashi-Kosugi', desc:{en:'Concentric tree-lined garden suburb and modern high-rise river hub.', ja:'放射状並木道の田園調布とタワーシティ武蔵小杉。'} },
      { num:'04', en:'Campuses & Harbor Approach', ja:'大学キャンパスと横浜アプローチ', stns:'Hiyoshi → Yokohama', desc:{en:'Ginkgo university boulevards, retro arcades, and harbor terminal.', ja:'慶應義塾の銀杏並木、白楽のレトロ商店街、横浜駅。'} },
    ],
    dests: [
      { id:'shibuya',     en:'Shibuya',        ja:'渋谷',       tier:'V', hub:true },
      { id:'yokohama',    en:'Yokohama',       ja:'横浜',       tier:'V', hub:true },
      { id:'yokosuka',    en:'Yokosuka-Chūō',  ja:'横須賀中央',  tier:'V', hub:true, yk:true },
      { id:'yokosuka_jr', en:'JR Yokosuka',    ja:'JR横須賀',   tier:'V', yk_jr:true },
      { id:'shinjuku',    en:'Shinjuku',       ja:'新宿',       tier:'E' },
      { id:'tokyo',       en:'Tokyo Stn',      ja:'東京駅',     tier:'E' },
    ],
    wards: {
      shibuya:    { en:'Shibuya',              ja:'渋谷区',       souba:{'1R':152000,'1K':138000,'1DK':172000,'1LDK':265000,'2LDK':442000}, src:'https://www.homes.co.jp/chintai/tokyo/shibuya-city/price/' },
      meguro:     { en:'Meguro',               ja:'目黒区',       souba:{'1R':125000,'1K':116000,'1DK':154000,'1LDK':232000,'2LDK':355000}, src:'https://www.homes.co.jp/chintai/tokyo/meguro-city/price/' },
      ota:        { en:'Ōta',                 ja:'大田区',       souba:{'1R':100400,'1K':105100,'1DK':136400,'1LDK':170100,'2LDK':229500}, src:'https://www.homes.co.jp/chintai/tokyo/ota-city/price/' },
      nakahara:   { en:'Nakahara (Kawasaki)',  ja:'川崎市中原区', souba:{'1R':88000,'1K':92000,'1DK':118000,'1LDK':152000,'2LDK':235000},  src:'https://www.homes.co.jp/chintai/kanagawa/kawasaki_nakahara-city/price/' },
      kohoku:     { en:'Kōhoku (Yokohama)',    ja:'横浜市港北区', souba:{'1R':72000,'1K':78000,'1DK':98000,'1LDK':135000,'2LDK':188000},   src:'https://www.homes.co.jp/chintai/kanagawa/yokohama_kohoku-city/price/' },
      kanagawaku: { en:'Kanagawa-ku',          ja:'神奈川区',     souba:{'1R':76000,'1K':89500,'1DK':103100,'1LDK':157600,'2LDK':206900},  src:'https://www.homes.co.jp/chintai/kanagawa/yokohama_kanagawa-city/price/' },
      nishi:      { en:'Nishi (Yokohama)',     ja:'横浜市西区',   souba:{'1R':80900,'1K':90600,'1DK':129600,'1LDK':166200,'2LDK':238500},  src:'https://www.homes.co.jp/chintai/kanagawa/yokohama_nishi-city/price/' },
    },
    stations: [
      { id:'shibuya',         en:'Shibuya',            ja:'渋谷',         num:'TY01', ward:'shibuya',    cumL:0,    tier:3, hw:3, junction:true },
      { id:'daikanyama',      en:'Daikanyama',         ja:'代官山',       num:'TY02', ward:'shibuya',    cumL:2,    tier:1, hw:5 },
      { id:'nakameguro',      en:'Naka-meguro',        ja:'中目黒',       num:'TY03', ward:'meguro',     cumL:4,    tier:3, hw:3, junction:true },
      { id:'yutenji',         en:'Yūtenji',            ja:'祐天寺',       num:'TY04', ward:'meguro',     cumL:6,    tier:1, hw:5 },
      { id:'gakugeidaigaku',  en:'Gakugei-daigaku',    ja:'学芸大学',     num:'TY05', ward:'meguro',     cumL:8,    tier:2, hw:4 },
      { id:'toritsudaigaku',  en:'Toritsu-daigaku',    ja:'都立大学',     num:'TY06', ward:'meguro',     cumL:10.5, tier:1, hw:5 },
      { id:'jiyugaoka',       en:'Jiyūgaoka',          ja:'自由が丘',     num:'TY07', ward:'meguro',     cumL:13,   tier:3, hw:3, junction:true },
      { id:'denenchofu',      en:'Den-en-chōfu',       ja:'田園調布',     num:'TY08', ward:'ota',        cumL:15,   tier:2, hw:4 },
      { id:'tamagawa',        en:'Tamagawa',           ja:'多摩川',       num:'TY09', ward:'ota',        cumL:17,   tier:2, hw:4 },
      { id:'shinnmaruko',     en:'Shin-Maruko',        ja:'新丸子',       num:'TY10', ward:'nakahara',   cumL:19,   tier:1, hw:5 },
      { id:'musashikosugi',   en:'Musashi-Kosugi',     ja:'武蔵小杉',     num:'TY11', ward:'nakahara',   cumL:21,   tier:3, hw:3, junction:true },
      { id:'motosumiyoshi',   en:'Motosumiyoshi',      ja:'元住吉',       num:'TY12', ward:'nakahara',   cumL:23.5, tier:1, hw:5 },
      { id:'hiyoshi',         en:'Hiyoshi',            ja:'日吉',         num:'TY13', ward:'kohoku',     cumL:26,   tier:3, hw:3, junction:true },
      { id:'tsunashima',      en:'Tsunashima',         ja:'綱島',         num:'TY14', ward:'kohoku',     cumL:28.5, tier:2, hw:4 },
      { id:'okurayama',       en:'Ōkurayama',          ja:'大倉山',       num:'TY15', ward:'kohoku',     cumL:31,   tier:1, hw:5 },
      { id:'kikuna',          en:'Kikuna',             ja:'菊名',         num:'TY16', ward:'kohoku',     cumL:33.5, tier:3, hw:3, junction:true },
      { id:'myorenji',        en:'Myōrenji',           ja:'妙蓮寺',       num:'TY17', ward:'kohoku',     cumL:36,   tier:1, hw:5 },
      { id:'hakuraku',        en:'Hakuraku',           ja:'白楽',         num:'TY18', ward:'kanagawaku', cumL:38,   tier:1, hw:5 },
      { id:'higashihakuraku', en:'Higashi-Hakuraku',   ja:'東白楽',       num:'TY19', ward:'kanagawaku', cumL:40,   tier:1, hw:5 },
      { id:'tammachi',        en:'Tammachi',           ja:'反町',         num:'TY20', ward:'kanagawaku', cumL:42,   tier:1, hw:5 },
      { id:'yokohama',        en:'Yokohama',           ja:'横浜',         num:'TY21', ward:'nishi',      cumL:45,   tier:3, hw:3, junction:true },
    ],
    anchors: [
      { id:'ty_exp', tier:'V', en:'Shibuya → Yokohama in 26′ via F-Liner / Limited Express', ja:'Fライナー・特急で渋谷〜横浜26分（最速直通）', src:'Tokyu Corporation Timetable 2026' },
      { id:'ty_jiyu', tier:'V', en:'Shibuya → Jiyūgaoka in 8′ express', ja:'急行で渋谷〜自由が丘8分', src:'Tokyu Railway Guide' },
      { id:'ty_kosugi', tier:'V', en:'Musashi-Kosugi provides 5-line cross-corridor connectivity', ja:'武蔵小杉はJR横須賀・湘南新宿・南武・目黒・新横浜線と結節', src:'JR / Tokyu Interchange' },
    ],
    pockets: [
      { id:'pk_daikanyama', st:'daikanyama', ward:'shibuya',
        name:{en:'Daikanyama T-Site terrace', ja:'代官山・T-SITEテラス'},
        gem:{en:'Low-rise architectural sanctuary: tree-shaded book lounges, indie boutiques, and calm cafe slopes minutes from Shibuya.',
             ja:'低層の建築美と木陰のブックテラス。渋谷至近の洗練された静穏街区。'},
        noiseWatch:{en:'Noise watch: Weekend afternoon design boutique shoppers and evening dining chatter; virtually zero automotive transit noise.',
                    ja:'騒音注意：週末午後のブティック来訪者とカフェの話し声。通過交通は皆無。'},
        noiseSrc:'Shibuya Ward Living Environment Ordinance',
        ax:{quiet:4, old:2, intl:4, food:4, craft:5, green:3, night:2, refined:5, photo:5} },
      { id:'pk_nakameguro', st:'nakameguro', ward:'meguro',
        name:{en:'Meguro River promenade', ja:'中目黒・目黒川緑道'},
        gem:{en:'Canopy of cherry trees over the river: specialty espresso roasters, design workshops, and lively bistro courtyards.',
             ja:'目黒川の桜並木沿いに並ぶスペシャルティコーヒーと小さなビストロ。'},
        noiseWatch:{en:'Noise watch: Spring cherry blossom tourist surges (March/April); evening bar chatter along Yamate-dori.',
                    ja:'騒音注意：春の桜まつり期間の大混雑、山手通り沿いの通過車両音。'},
        noiseSrc:'Meguro Police Precinct Blotter',
        ax:{quiet:2, old:2, intl:4, food:5, craft:4, green:4, night:4, refined:4, photo:5} },
      { id:'pk_gakugei', st:'gakugeidaigaku', ward:'meguro',
        name:{en:'Gakudai twin shōtengai', ja:'学芸大学・東西商店街'},
        gem:{en:'Two vibrant commercial promenades buzzing with craft bakeries, natural wine counters, and multigenerational community warmth.',
             ja:'東西に伸びる商店街。ベーカリー、自然派ワイン、下町情緒が同居。'},
        noiseWatch:{en:'Noise watch: Evening bicycle traffic and lively restaurant spillover; quiet residential streets set 2 minutes back.',
                    ja:'騒音注意：夕方の買い物自転車と居酒屋の賑わい。駅から2分離れると静寂。'},
        noiseSrc:'Meguro Commercial Promotion Council',
        ax:{quiet:3, old:3, intl:2, food:5, craft:3, green:2, night:3, refined:3, photo:3} },
      { id:'pk_jiyugaoka', st:'jiyugaoka', ward:'meguro',
        name:{en:'Jiyūgaoka European lanes', ja:'自由が丘・マリクレール通り'},
        gem:{en:'Paved pedestrian lanes, open-air green street benches, patisseries, and curated homeware boutiques.',
             ja:'石畳の遊歩道、パティスリー、インテリア雑貨店が織りなす街並み。'},
        noiseWatch:{en:'Noise watch: Weekend family and shopping foot traffic; quiet residential tranquility after 20:00.',
                    ja:'騒音注意：週末の買い物客の歩行音。20時以降は落ち着いた住宅地。'},
        noiseSrc:'Jiyūgaoka Merchant Association',
        ax:{quiet:4, old:3, intl:3, food:5, craft:4, green:3, night:2, refined:5, photo:4} },
      { id:'pk_hakuraku', st:'hakuraku', ward:'kanagawaku',
        name:{en:'Rokkakubashi retro arcade', ja:'白楽・六角橋商店街'},
        gem:{en:'Atmospheric pre-war retro covered market: antique bookshops, record counters, noodle stalls, and artistic student vitality.',
             ja:'昭和レトロな闇市由来のアーケード。古書店、レコード、学生カルチャー。'},
        noiseWatch:{en:'Noise watch: Daytime arcade chatter and evening student nomikai banter; hillside residential lanes are silent.',
                    ja:'騒音注意：アーケード内の活気ある会話と夕方の学生客。坂の上の住宅街は極めて静穏。'},
        noiseSrc:'Kanagawa-ku Historic Commercial Survey',
        ax:{quiet:3, old:5, intl:1, food:4, craft:4, green:2, night:3, refined:2, photo:4} },
    ],
    homes: [
      { id:'ty_hiyoshi_annex', st:'hiyoshi', ward:'kohoku', name:{en:'Park Heights Annex', ja:'パークハイツアネックス'}, rent:68000, fee:3000, mgmt:3000, layout:'1K', size:20.5, m2:20.5, walk:8, year:1981, built:'1981 · 2F 軽量鉄骨造', tag:'LIVE', live:true, tier:'LIVE', srcName:'SUUMO / Google Maps', url:'https://maps.app.goo.gl/cJMiGzpkunkw1E439?g_st=ac', listed:{st:{en:'Hiyoshi',ja:'日吉'}, line:'Tokyu Toyoko / Meguro / Shin-Yokohama', walk:8}, extra:{en:'8 min walk to Hiyoshi Stn · 7 min walk to Green Line Hiyoshihonchō · 44 min commute to Yokosuka-Chūō (1 transfer at Yokohama)', ja:'日吉駅徒歩8分・グリーンライン日吉本町駅徒歩7分 · 横浜乗換1回で横須賀中央へ44分（60分上限内）'}, why:{en:'Quiet residential hillside in Hiyoshihoncho 3-chome. 44 min one-transfer commute to Yokosuka naval/engineering hub via Yokohama Keikyu Kaitoku (fits within 60′ boundary).', ja:'日吉本町3丁目の閑静な高台住宅街。横浜駅乗換で横須賀中央へ44分、エンジニア通勤の60分上限内に直結。'} },
      { id:'ty_h01', st:'daikanyama', ward:'shibuya', name:{en:'Daikanyama Terrace Court', ja:'代官山テラスコート'}, rent:185000, fee:10000, layout:'1LDK', size:38.5, walk:4, year:2020, tag:'✨ High-End', live:true, why:{en:'Designer concrete finish, west-facing balcony overlooking lush courtyard.', ja:'打ち放しコンクリート、中庭を望む西向きバルコニー。'} },
      { id:'ty_h02', st:'nakameguro', ward:'meguro', name:{en:'Riverfront Meguro Residence', ja:'リバーフロント中目黒'}, rent:142000, fee:8000, layout:'1K', size:27.2, walk:5, year:2018, tag:'LIVE', live:true, why:{en:'Directly fronting the quiet residential segment of Meguro River.', ja:'目黒川の静かな上流エリアに面した上質1K。'} },
      { id:'ty_h03', st:'gakugeidaigaku', ward:'meguro', name:{en:'Gakudai Green Flat', ja:'学芸大学グリーンフラット'}, rent:118000, fee:7000, layout:'1K', size:25.8, walk:3, year:2016, tag:'LIVE', live:true, why:{en:'Steppes from the east shotengai, double-glazed acoustic sash.', ja:'東口商店街すぐ、二重サッシ完備で静寂確保。'} },
      { id:'ty_h04', st:'jiyugaoka', ward:'meguro', name:{en:'Jiyugaoka Maison Blanche', ja:'自由が丘メゾンブランシュ'}, rent:128000, fee:8000, layout:'1DK', size:31.0, walk:6, year:2019, tag:'LIVE', live:true, why:{en:'Sunlit corner apartment in quiet residential Jiyugaoka 2-chome.', ja:'自由が丘2丁目の閑静な住宅街に位置する角部屋。'} },
      { id:'ty_h05', st:'musashikosugi', ward:'nakahara', name:{en:'Kosugi Tower Vista', ja:'武蔵小杉タワービスタ'}, rent:165000, fee:12000, layout:'1LDK', size:42.0, walk:3, year:2021, tag:'✨ High-End', live:true, why:{en:'High-floor city views, direct indoor concourse to train lines.', ja:'高層階からのパノラマ眺望、駅直結地下通路利用可能。'} },
      { id:'ty_h06', st:'hiyoshi', ward:'kohoku', name:{en:'Hiyoshi Hill Terrace', ja:'日吉ヒルテラス'}, rent:78000, fee:5000, layout:'1K', size:22.5, walk:5, year:2015, tag:'LIVE', live:true, why:{en:'Peaceful hilltop residential pocket, excellent cost-performance.', ja:'日吉本町の高台に佇む落ち着いた住環境、コスパ抜群。'} },
      { id:'ty_h07', st:'hakuraku', ward:'kanagawaku', name:{en:'Rokkakubashi Machiya Atelier', ja:'六角橋マチヤアトリエ'}, rent:72000, fee:4000, layout:'1R', size:24.0, walk:4, year:2017, tag:'LIVE', live:true, why:{en:'Renovated timber design flat steps from the retro shopping lane.', ja:'レトロ商店街から1本入ったリノベーション木造フラット。'} },
      { id:'ty_h08', st:'kikuna', ward:'kohoku', name:{en:'Kikuna Forest Court', ja:'菊名フォレストコート'}, rent:68000, fee:4000, layout:'1K', size:21.8, walk:7, year:2014, tag:'LIVE', live:true, why:{en:'Quiet residential hillside, dual access to Toyoko Express & JR.', ja:'急行停車駅・菊名の閑静な住宅街、2路線利用可。'} },
    ]
  },

  hibiya: {
    id: 'hibiya',
    name: 'Hibiya',
    ja: '東京メトロ日比谷線',
    tag: 'Naka-Meguro → Kita-Senju',
    desc: {
      en: 'Tokyo’s central diplomatic, arts, and cultural artery connecting Ebisu, Roppongi, Ginza, and Ueno to the historic transit hub of Kita-Senju.',
      ja: '恵比寿・六本木・銀座・上野から北千住へ。東京の文化・外交・都心商業を縦断する主要地下鉄回廊。'
    },
    color: '#9caeb7',
    accent: '#5c7482',
    badge: '🌹',
    goalMin: 20.0,
    zones: [
      { num:'01', en:'Art, Dining & Diplomatic Enclaves', ja:'食と文化・外交の邸宅街', stns:'Naka-Meguro → Roppongi', desc:{en:'Arisugawa greenery, Roppongi Hills art triangle, and Michelin dining.', ja:'有栖川宮記念公園の杜、六本木ヒルズ、恵比寿の美食。'} },
      { num:'02', en:'Government Axis & Imperial Lawns', ja:'政治中枢と日比谷公園', stns:'Kamiyachō → Hibiya', desc:{en:'Central ministries, Tokyo Tower views, and grand urban park lawns.', ja:'霞ケ関の官庁街、東京タワー眺望、劇場と日比谷の緑。'} },
      { num:'03', en:'Financial Core & Shitamachi Waterways', ja:'銀座商業と下町の水路', stns:'Ginza → Kodemmachō', desc:{en:'Ginza flagship boulevards, Tsukiji wholesale fish market, and Amazake Yokochō.', ja:'銀座のメイン通り、築地場外市場、人形町の工芸路地。'} },
      { num:'04', en:'Museum Ridge & Northern Terminals', ja:'上野の文化と北の結節点', stns:'Akihabara → Kita-Senju', desc:{en:'Ueno Park national museums, Ameyoko street life, and 5-railway interchange.', ja:'上野恩賜公園の博物館群、アメ横、5路線結節の北千住。'} },
    ],
    dests: [
      { id:'roppongi', en:'Roppongi',  ja:'六本木', tier:'V', hub:true },
      { id:'ginza',    en:'Ginza',     ja:'銀座',   tier:'V', hub:true },
      { id:'ebisu',    en:'Ebisu',     ja:'恵比寿', tier:'V', hub:true },
      { id:'ueno',     en:'Ueno',      ja:'上野',   tier:'E' },
    ],
    wards: {
      meguro:   { en:'Meguro',   ja:'目黒区',   souba:{'1R':125000,'1K':116000,'1LDK':232000,'2LDK':355000}, src:'https://www.homes.co.jp/chintai/tokyo/meguro-city/price/' },
      shibuya:  { en:'Shibuya',  ja:'渋谷区',   souba:{'1R':152000,'1K':138000,'1LDK':265000,'2LDK':442000}, src:'https://www.homes.co.jp/chintai/tokyo/shibuya-city/price/' },
      minato:   { en:'Minato',   ja:'港区',     souba:{'1R':177400,'1K':147000,'1LDK':292200,'2LDK':467000}, src:'https://www.homes.co.jp/chintai/tokyo/minato-city/price/' },
      chuo:     { en:'Chūō',     ja:'中央区',   souba:{'1R':156000,'1K':134300,'1LDK':234000,'2LDK':328200}, src:'https://www.homes.co.jp/chintai/tokyo/chuo-city/price/' },
      chiyoda:  { en:'Chiyoda',  ja:'千代田区', souba:{'1R':160000,'1K':142000,'1LDK':270000,'2LDK':420000}, src:'https://www.homes.co.jp/chintai/tokyo/chiyoda-city/price/' },
      taito:    { en:'Taitō',    ja:'台東区',   souba:{'1R':98000,'1K':102000,'1LDK':172000,'2LDK':245000},  src:'https://www.homes.co.jp/chintai/tokyo/taito-city/price/' },
      arakawa:  { en:'Arakawa',  ja:'荒川区',   souba:{'1R':78000,'1K':84000,'1LDK':142000,'2LDK':198000},   src:'https://www.homes.co.jp/chintai/tokyo/arakawa-city/price/' },
      adachi:   { en:'Adachi',   ja:'足立区',   souba:{'1R':68000,'1K':74000,'1LDK':125000,'2LDK':165000},   src:'https://www.homes.co.jp/chintai/tokyo/adachi-city/price/' },
    },
    stations: [
      { id:'nakameguro',      en:'Naka-meguro',       ja:'中目黒',       num:'H01', ward:'meguro',   cumL:0,    tier:3, hw:3, junction:true },
      { id:'ebisu',           en:'Ebisu',             ja:'恵比寿',       num:'H02', ward:'shibuya',  cumL:3,    tier:3, hw:3, junction:true },
      { id:'hiroo',           en:'Hiroo',             ja:'広尾',         num:'H03', ward:'minato',   cumL:6,    tier:1, hw:3 },
      { id:'roppongi',        en:'Roppongi',          ja:'六本木',       num:'H04', ward:'minato',   cumL:9,    tier:3, hw:3, junction:true },
      { id:'kamiyacho',       en:'Kamiyachō',         ja:'神谷町',       num:'H05', ward:'minato',   cumL:11.5, tier:1, hw:3 },
      { id:'toranomonhills',  en:'Toranomon Hills',   ja:'虎ノ門ヒルズ', num:'H06', ward:'minato',   cumL:13,   tier:1, hw:3 },
      { id:'kasumigaseki',    en:'Kasumigaseki',      ja:'霞ケ関',       num:'H07', ward:'chiyoda',  cumL:15,   tier:3, hw:3, junction:true },
      { id:'hibiya',          en:'Hibiya',            ja:'日比谷',       num:'H08', ward:'chiyoda',  cumL:17,   tier:3, hw:3, junction:true },
      { id:'ginza',           en:'Ginza',             ja:'銀座',         num:'H09', ward:'chuo',     cumL:18.5, tier:3, hw:3, junction:true },
      { id:'higashiginza',    en:'Higashi-ginza',     ja:'東銀座',       num:'H10', ward:'chuo',     cumL:20,   tier:1, hw:3, junction:true },
      { id:'tsukiji',         en:'Tsukiji',           ja:'築地',         num:'H11', ward:'chuo',     cumL:22,   tier:1, hw:3 },
      { id:'hatchobori',      en:'Hatchōbori',        ja:'八丁堀',       num:'H12', ward:'chuo',     cumL:24,   tier:2, hw:3, junction:true },
      { id:'kayabacho',       en:'Kayabachō',         ja:'茅場町',       num:'H13', ward:'chuo',     cumL:25.5, tier:2, hw:3, junction:true },
      { id:'ningyocho',       en:'Ningyōchō',         ja:'人形町',       num:'H14', ward:'chuo',     cumL:27.5, tier:2, hw:3, junction:true },
      { id:'kodemmacho',      en:'Kodemmachō',        ja:'小伝馬町',     num:'H15', ward:'chuo',     cumL:29,   tier:1, hw:3 },
      { id:'akihabara',       en:'Akihabara',         ja:'秋葉原',       num:'H16', ward:'chiyoda',  cumL:31,   tier:3, hw:3, junction:true },
      { id:'nakaokachimachi', en:'Naka-Okachimachi',  ja:'仲御徒町',     num:'H17', ward:'taito',    cumL:32.5, tier:2, hw:3 },
      { id:'ueno',            en:'Ueno',              ja:'上野',         num:'H18', ward:'taito',    cumL:34,   tier:3, hw:3, junction:true },
      { id:'iriya',           en:'Iriya',             ja:'入谷',         num:'H19', ward:'taito',    cumL:36,   tier:1, hw:3.5 },
      { id:'minowa',          en:'Minowa',            ja:'三ノ輪',       num:'H20', ward:'taito',    cumL:38,   tier:1, hw:3.5 },
      { id:'minamisenju',     en:'Minami-Senju',      ja:'南千住',       num:'H21', ward:'arakawa',  cumL:40.5, tier:2, hw:3.5, junction:true },
      { id:'kitasenju',       en:'Kita-Senju',        ja:'北千住',       num:'H22', ward:'adachi',   cumL:43,   tier:3, hw:3, junction:true },
    ],
    anchors: [
      { id:'h_core', tier:'V', en:'Naka-Meguro → Ginza in 18′ direct', ja:'中目黒〜銀座18分直通', src:'Tokyo Metro Timetable' },
      { id:'h_hub', tier:'V', en:'Kita-Senju terminal links 5 railways with sub-¥80k rents', ja:'北千住は5路線結節の巨大ハブ・家賃相場7万円台', src:'Adachi Ward Transit Study' },
    ],
    pockets: [
      { id:'pk_hiroo', st:'hiroo', ward:'minato',
        name:{en:'Arisugawa Park embassy hill', ja:'広尾・有栖川公園の丘'},
        gem:{en:'Green forest pond, international grocers, diplomatic quietude, and refined European cafe terraces.',
             ja:'緑豊かな有栖川宮記念公園、大使館の静寂、インターナショナルな街並み。'},
        noiseWatch:{en:'Noise watch: Occasional political sound vans on Meiji-dori; residential slopes up to the park are deeply serene.',
                    ja:'騒音注意：明治通り沿いの散発的な街宣車。公園側の高台住宅街は極めて静寂。'},
        noiseSrc:'Minato Ward Environmental Registry',
        ax:{quiet:5, old:2, intl:5, food:4, craft:3, green:5, night:1, refined:5, photo:4} },
      { id:'pk_ebisu', st:'ebisu', ward:'shibuya',
        name:{en:'Yebisu Garden Place & alleys', ja:'恵比寿・ガーデンプレイス裏'},
        gem:{en:'Brick plazas and Michelin dining transition into cozy dining alleys and craft beer bars.',
             ja:'レンガの広場から路地裏のビストロ・酒場へ。食通が集う大人の街。'},
        noiseWatch:{en:'Noise watch: Evening nomikai crowd spillover near west exit; Garden Place east side is peaceful.',
                    ja:'騒音注意：西口周辺の夜間飲食客の足音。東側ガーデンプレイス方面は静穏。'},
        noiseSrc:'Shibuya Police Station Blotter',
        ax:{quiet:3, old:2, intl:4, food:5, craft:3, green:3, night:4, refined:5, photo:4} },
      { id:'pk_kitasenju', st:'kitasenju', ward:'adachi',
        name:{en:'Kita-Senju post-town lanes', ja:'北千住・宿場町通り'},
        gem:{en:'Historic Nikkō Kaidō shukuba: bathhouses, izakayas, artisan bakeries, and university campus vitality.',
             ja:'日光街道の宿場町の面影。銭湯、昭和酒場、大学キャンパスが同居。'},
        noiseWatch:{en:'Noise watch: West exit bustling entertainment alleys till midnight; residential lanes east of the tracks are tranquil.',
                    ja:'騒音注意：西口駅前商店街の終電前後の賑わい。東口住宅街は静か。'},
        noiseSrc:'Adachi Ward Living Safety Blotter',
        ax:{quiet:2, old:5, intl:2, food:5, craft:3, green:3, night:4, refined:2, photo:4} },
    ],
    homes: [
      { id:'hb_h01', st:'ebisu', ward:'shibuya', name:{en:'Ebisu South Court', ja:'恵比寿サウスコート'}, rent:148000, fee:10000, layout:'1K', size:28.0, walk:5, year:2019, tag:'LIVE', live:true, why:{en:'Quiet residential pocket south of Garden Place.', ja:'ガーデンプレイス南側の落ち着いた邸宅街。'} },
      { id:'hb_h02', st:'hiroo', ward:'minato', name:{en:'Hiroo Forest Residence', ja:'広尾フォレストレジデンス'}, rent:195000, fee:15000, layout:'1LDK', size:40.2, walk:4, year:2021, tag:'✨ High-End', live:true, why:{en:'Designer wood interior overlooking Arisugawa green belt.', ja:'有栖川公園の緑を望むデザイナーズ1LDK。'} },
      { id:'hb_h03', st:'hatchobori', ward:'chuo', name:{en:'Hatchobori Canal Suite', ja:'八丁堀キャナルスイート'}, rent:128000, fee:8000, layout:'1K', size:26.5, walk:3, year:2020, tag:'LIVE', live:true, why:{en:'Direct line to Ginza & Roppongi, quiet canal walkway view.', ja:'銀座・六本木直通、水辺の遊歩道に面した静かな部屋。'} },
      { id:'hb_h04', st:'kitasenju', ward:'adachi', name:{en:'Kita-Senju Retro Garden', ja:'北千住レトロガーデン'}, rent:76000, fee:5000, layout:'1K', size:23.0, walk:6, year:2018, tag:'LIVE', live:true, why:{en:'Minutes from 5 train lines, quiet post-town residential alley.', ja:'5路線利用可能なメガハブ、宿場町の情緒ある路地。'} },
    ]
  },

  denentoshi: {
    id: 'denentoshi',
    name: 'Den-en-toshi',
    ja: '東急田園都市線',
    tag: 'Shibuya → Chūō-Rinkan',
    desc: {
      en: 'Western Tokyo’s celebrated garden-city green belt connecting Shibuya to Setagaya parks, the Tama River at Futako-Tamagawa, and the rolling residential hills of Yokohama Aoba.',
      ja: '渋谷から世田谷の公園群、二子玉川の水辺を経て横浜青葉の緑豊かな丘陵住宅街へ。ファミリーとクリエイターに愛される田園都市の理想形。'
    },
    color: '#20a288',
    accent: '#167a66',
    badge: '🌿',
    goalMin: 24.0,
    zones: [
      { num:'01', en:'Inner Suburbs & Dining Mazes', ja:'都心隣接と三角地帯', stns:'Shibuya → Sangenjaya', desc:{en:'Craft coffee, elevated sky gardens, and labyrinth tavern alleys.', ja:'クラフトコーヒー、目黒天空庭園、三角地帯の路地。'} },
      { num:'02', en:'Olympic Parks & Riverfront', ja:'緑豊かな公園と水辺', stns:'Komazawa → Futako-Tamagawa', desc:{en:'Sprawling park lawns, tree avenues, and Tama riverbank open space.', ja:'駒沢公園の緑、サザエさんの桜並木、多摩川の水辺テラス。'} },
      { num:'03', en:'Cross-Town Hubs & Spas', ja:'多摩丘陵と温泉スパ', stns:'Mizonokuchi → Saginuma', desc:{en:'Nambu line transfer hub, hot spring sentos, and elevated ridges.', ja:'JR南武線結節点、天然温泉、鷺沼の丘陵景観。'} },
      { num:'04', en:'Planned Garden City Terraces', ja:'計画された田園都市', stns:'Tama-Plaza → Chūō-Rinkan', desc:{en:'Wide cherry boulevards, hill walks, and leafy suburban calm.', ja:'美しが丘の並木道、青葉台の公園群、中央林間。'} },
    ],
    dests: [
      { id:'shibuya',        en:'Shibuya',         ja:'渋谷',       tier:'V', hub:true },
      { id:'otemachi',       en:'Otemachi',        ja:'大手町',     tier:'V', hub:true },
      { id:'futakotamagawa', en:'Futako-Tamagawa', ja:'二子玉川',   tier:'V' },
      { id:'nagatsuta',      en:'Nagatsuta',       ja:'長津田',     tier:'E' },
    ],
    wards: {
      shibuya:  { en:'Shibuya',           ja:'渋谷区',       souba:{'1R':152000,'1K':138000,'1LDK':265000,'2LDK':442000}, src:'https://www.homes.co.jp/chintai/tokyo/shibuya-city/price/' },
      setagaya: { en:'Setagaya',          ja:'世田谷区',     souba:{'1R':95000,'1K':94000,'1LDK':178000,'2LDK':268000},   src:'https://www.homes.co.jp/chintai/tokyo/setagaya-city/price/' },
      takatsu:  { en:'Takatsu (Kawasaki)', ja:'川崎市高津区', souba:{'1R':75000,'1K':82000,'1LDK':132000,'2LDK':185000},  src:'https://www.homes.co.jp/chintai/kanagawa/kawasaki_takatsu-city/price/' },
      miyamae:  { en:'Miyamae (Kawasaki)', ja:'川崎市宮前区', souba:{'1R':68000,'1K':76000,'1LDK':124000,'2LDK':168000},  src:'https://www.homes.co.jp/chintai/kanagawa/kawasaki_miyamae-city/price/' },
      aoba:     { en:'Aoba (Yokohama)',    ja:'横浜市青葉区', souba:{'1R':69000,'1K':78000,'1LDK':128000,'2LDK':175000},  src:'https://www.homes.co.jp/chintai/kanagawa/yokohama_aoba-city/price/' },
      midori:   { en:'Midori (Yokohama)',  ja:'横浜市緑区',   souba:{'1R':62000,'1K':68000,'1LDK':110000,'2LDK':152000},  src:'https://www.homes.co.jp/chintai/kanagawa/yokohama_midori-city/price/' },
    },
    stations: [
      { id:'shibuya',         en:'Shibuya',            ja:'渋谷',         num:'DT01', ward:'shibuya',  cumL:0,    tier:3, hw:3, junction:true },
      { id:'ikejiriohashi',   en:'Ikejiri-Ōhashi',     ja:'池尻大橋',     num:'DT02', ward:'setagaya', cumL:3,    tier:1, hw:4 },
      { id:'sangenjaya',      en:'Sangen-jaya',        ja:'三軒茶屋',     num:'DT03', ward:'setagaya', cumL:5,    tier:3, hw:3, junction:true },
      { id:'komazawadaigaku', en:'Komazawa-daigaku',   ja:'駒沢大学',     num:'DT04', ward:'setagaya', cumL:7.5,  tier:1, hw:4 },
      { id:'sakurashinmachi', en:'Sakura-shimmachi',   ja:'桜新町',       num:'DT05', ward:'setagaya', cumL:10,   tier:1, hw:4 },
      { id:'yoga',            en:'Yōga',               ja:'用賀',         num:'DT06', ward:'setagaya', cumL:12,   tier:1, hw:4 },
      { id:'futakotamagawa',  en:'Futako-tamagawa',    ja:'二子玉川',     num:'DT07', ward:'setagaya', cumL:14.5, tier:3, hw:3, junction:true },
      { id:'futakoshinchi',   en:'Futako-shinchi',     ja:'二子新地',     num:'DT08', ward:'takatsu',  cumL:16,   tier:1, hw:5 },
      { id:'takatsu',         en:'Takatsu',            ja:'高津',         num:'DT09', ward:'takatsu',  cumL:17.5, tier:1, hw:5 },
      { id:'mizonokuchi',     en:'Mizonokuchi',        ja:'溝の口',       num:'DT10', ward:'takatsu',  cumL:19.5, tier:3, hw:3, junction:true },
      { id:'kajigaya',        en:'Kajigaya',           ja:'梶が谷',       num:'DT11', ward:'takatsu',  cumL:22,   tier:1, hw:5 },
      { id:'miyamaedaira',    en:'Miyamaedaira',       ja:'宮前平',       num:'DT12', ward:'miyamae',  cumL:24,   tier:1, hw:5 },
      { id:'saginuma',        en:'Saginuma',           ja:'鷺沼',         num:'DT13', ward:'miyamae',  cumL:26,   tier:3, hw:3 },
      { id:'tamaplaza',       en:'Tama-plaza',         ja:'たまプラーザ', num:'DT14', ward:'aoba',     cumL:28.5, tier:3, hw:3 },
      { id:'azamino',         en:'Azamino',            ja:'あざみ野',     num:'DT15', ward:'aoba',     cumL:30.5, tier:3, hw:3, junction:true },
      { id:'eda',             en:'Eda',                ja:'江田',         num:'DT16', ward:'aoba',     cumL:33,   tier:1, hw:5 },
      { id:'ichigao',         en:'Ichigao',            ja:'市が尾',       num:'DT17', ward:'aoba',     cumL:35,   tier:1, hw:5 },
      { id:'fujigaoka',       en:'Fujigaoka',          ja:'藤が丘',       num:'DT18', ward:'aoba',     cumL:37,   tier:1, hw:5 },
      { id:'aobadai',         en:'Aobadai',            ja:'青葉台',       num:'DT19', ward:'aoba',     cumL:39,   tier:3, hw:3 },
      { id:'nagatsuta',       en:'Nagatsuta',          ja:'長津田',       num:'DT22', ward:'midori',   cumL:43,   tier:3, hw:3, junction:true },
    ],
    anchors: [
      { id:'dt_exp', tier:'V', en:'Shibuya → Futako-Tamagawa in 11′ express', ja:'急行で渋谷〜二子玉川11分', src:'Tokyu Railway Timetable' },
      { id:'dt_thru', tier:'V', en:'Direct through-running onto Tokyo Metro Hanzomon Line to Otemachi', ja:'半蔵門線直通で大手町まで乗り換えなし', src:'Tokyo Metro Through-Run Agreement' },
    ],
    pockets: [
      { id:'pk_sangenjaya', st:'sangenjaya', ward:'setagaya',
        name:{en:'Sangenjaya Sankaku-chitai', ja:'三軒茶屋・三角地帯'},
        gem:{en:'Iconic labyrinth of tiny taverns and izakayas beneath the retro Carrot Tower, steps from the Setagaya tram line.',
             ja:'キャロットタワーの足元に広がる迷路のような酒場街。路面電車とカルチャーの街。'},
        noiseWatch:{en:'Noise watch: Route 246 / expressway overhead rumble; narrow drinking alley chatter until 02:00. Side streets off Taishido are quiet.',
                    ja:'騒音注意：国道246号・首都高の高架走行音と深夜の酒場街の賑わい。太子堂側の裏路地は閑静。'},
        noiseSrc:'Setagaya Ward Acoustic Survey',
        ax:{quiet:2, old:3, intl:3, food:5, craft:4, green:2, night:5, refined:3, photo:4} },
      { id:'pk_futako', st:'futakotamagawa', ward:'setagaya',
        name:{en:'Futako-Tamagawa River Terrace', ja:'二子玉川・水辺テラス'},
        gem:{en:'Vast grass riverbanks, open-air cinema, roof gardens, and high-end shopping along the Tama River.',
             ja:'多摩川の広大な河川敷と緑豊かな屋上庭園。洗練と自然が調和する水辺都市。'},
        noiseWatch:{en:'Noise watch: Weekend riverbank recreational crowd noise and summer fireworks; residential blocks on the bluff are deeply peaceful.',
                    ja:'騒音注意：週末の河川敷バーベキュー・広場の賑わい。国分寺崖線上の住宅地は極めて閑静。'},
        noiseSrc:'MLIT Keihin River Office',
        ax:{quiet:4, old:1, intl:3, food:4, craft:3, green:5, night:2, refined:5, photo:5} },
      { id:'pk_tamaplaza', st:'tamaplaza', ward:'aoba',
        name:{en:'Tama-Plaza garden terrace', ja:'たまプラーザ・美しが丘'},
        gem:{en:'Tokyu’s flagship planned garden suburb: wide cherry avenues, terraced plaza dining, and serene hill living.',
             ja:'東急が心血を注いだ理想の田園都市。美しい街路樹とテラスの開放感。'},
        noiseWatch:{en:'Noise watch: Evening bus terminal movements; residential grid has virtually zero through-car noise (quiet 5/5).',
                    ja:'騒音注意：駅前バスターミナルの発着音。美しが丘の住宅街は夜間完全な静寂（静けさ5/5）。'},
        noiseSrc:'Yokohama Aoba Ward Planning Board',
        ax:{quiet:5, old:1, intl:3, food:3, craft:2, green:4, night:1, refined:5, photo:4} },
    ],
    homes: [
      { id:'dt_h01', st:'sangenjaya', ward:'setagaya', name:{en:'Sangenjaya Retro Flat', ja:'三軒茶屋レトロフラット'}, rent:112000, fee:7000, layout:'1K', size:26.5, walk:4, year:2018, tag:'LIVE', live:true, why:{en:'In Taishido quiet residential grid, 4 minutes to express station.', ja:'太子堂の閑静な住宅街、急行停車駅から徒歩4分。'} },
      { id:'dt_h02', st:'futakotamagawa', ward:'setagaya', name:{en:'River Terrace Futako', ja:'リバーテラス二子玉川'}, rent:148000, fee:10000, layout:'1LDK', size:36.0, walk:6, year:2020, tag:'LIVE', live:true, why:{en:'Direct view toward the green river levee and Mount Fuji on clear days.', ja:'緑豊かな河川敷を望み、晴れた日には富士山も遠望。'} },
      { id:'dt_h03', st:'tamaplaza', ward:'aoba', name:{en:'Utsukushigaoka Court', ja:'美しが丘コート'}, rent:82000, fee:5000, layout:'1K', size:25.0, walk:5, year:2016, tag:'LIVE', live:true, why:{en:'Lined with trees, private balcony overlooking green garden.', ja:'並木道に面した緑豊かな低層マンション。'} },
      { id:'dt_h04', st:'aobadai', ward:'aoba', name:{en:'Aobadai Park View', ja:'青葉台パークビュー'}, rent:68000, fee:4000, layout:'1K', size:23.5, walk:7, year:2015, tag:'LIVE', live:true, why:{en:'Suburban calm, spacious kitchen, close to nature parks.', ja:'自然公園至近、広々としたキッチン付きの落ち着いた部屋。'} },
    ]
  },

  odakyu: {
    id: 'odakyu',
    name: 'Odakyū',
    ja: '小田急小田原線',
    tag: 'Shinjuku → Machida',
    desc: {
      en: 'Tokyo’s subcultural and green residential spine connecting Shinjuku mega-terminal through Shimokitazawa theatres and leafy Setagaya estates to Machida and the Tama River.',
      ja: '新宿から下北沢のサブカルチャー、世田谷の閑静な邸宅街を経て多摩川・町田へ。複々線化で劇的に進化した西東京の快適生活幹線。'
    },
    color: '#1067b8',
    accent: '#0b4d8c',
    badge: '🗻',
    goalMin: 25.0,
    zones: [
      { num:'01', en:'Shinjuku Fringe & Forest Gates', ja:'都心ターミナルと明治神宮の杜', stns:'Shinjuku → Yoyogi-Hachiman', desc:{en:'Mega-terminal vitality, tranquil park boundaries, and bakery alleys.', ja:'新宿の利便性、明治神宮西門の静けさ、富ヶ谷のパン屋。'} },
      { num:'02', en:'Theatres, Vintage & Greenways', ja:'演劇・古着と地下化緑道', stns:'Yoyogi-Uehara → Umegaoka', desc:{en:'Indie music and theatre epicenter, Chiyoda through-run, and Reload greenway.', ja:'小劇場の街、千代田線直通、世田谷代田の温泉旅館。'} },
      { num:'03', en:'Temples, Trams & River Estates', ja:'招き猫の寺町と成城の緑', stns:'Gōtokuji → Komae', desc:{en:'Maneki-Neko temple, retro tram transfers, and prestigious garden bluffs.', ja:'豪徳寺の杜、世田谷線、成城学園前の美しい銀杏並木。'} },
      { num:'04', en:'Tama River & Western Capitals', ja:'多摩川越えと西の商業拠点', stns:'Noborito → Machida', desc:{en:'Riverbanks, Ikuta Ryokuchi folk museum, and Machida mega-commercial hub.', ja:'多摩川河川敷、生田緑地、町田の巨大商業集積。'} },
    ],
    dests: [
      { id:'shinjuku',        en:'Shinjuku',        ja:'新宿',       tier:'V', hub:true },
      { id:'yoyogiuehara',    en:'Yoyogi-Uehara',   ja:'代々木上原', tier:'V', hub:true },
      { id:'shimokitazawa',   en:'Shimokitazawa',   ja:'下北沢',     tier:'V' },
      { id:'machida',         en:'Machida',         ja:'町田',       tier:'E' },
    ],
    wards: {
      shinjuku: { en:'Shinjuku',         ja:'新宿区',       souba:{'1R':135000,'1K':128000,'1LDK':245000,'2LDK':385000}, src:'https://www.homes.co.jp/chintai/tokyo/shinjuku-city/price/' },
      shibuya:  { en:'Shibuya',          ja:'渋谷区',       souba:{'1R':152000,'1K':138000,'1LDK':265000,'2LDK':442000}, src:'https://www.homes.co.jp/chintai/tokyo/shibuya-city/price/' },
      setagaya: { en:'Setagaya',         ja:'世田谷区',     souba:{'1R':95000,'1K':94000,'1LDK':178000,'2LDK':268000},   src:'https://www.homes.co.jp/chintai/tokyo/setagaya-city/price/' },
      komae:    { en:'Komae-shi',        ja:'狛江市',       souba:{'1R':68000,'1K':72000,'1LDK':118000,'2LDK':155000},   src:'https://www.homes.co.jp/chintai/tokyo/komae-city/price/' },
      tama_ku:  { en:'Tama-ku (Kawasaki)', ja:'川崎市多摩区', souba:{'1R':64000,'1K':72000,'1LDK':115000,'2LDK':152000},  src:'https://www.homes.co.jp/chintai/kanagawa/kawasaki_tama-city/price/' },
      asao_ku:  { en:'Asao-ku (Kawasaki)', ja:'川崎市麻生区', souba:{'1R':66000,'1K':75000,'1LDK':122000,'2LDK':162000},  src:'https://www.homes.co.jp/chintai/kanagawa/kawasaki_asao-city/price/' },
      machida:  { en:'Machida-shi',      ja:'町田市',       souba:{'1R':58000,'1K':65000,'1LDK':105000,'2LDK':142000},   src:'https://www.homes.co.jp/chintai/tokyo/machida-city/price/' },
    },
    stations: [
      { id:'shinjuku',          en:'Shinjuku',           ja:'新宿',           num:'OH01', ward:'shinjuku',  cumL:0,    tier:3, hw:2.5, junction:true },
      { id:'minamishinjuku',    en:'Minami-Shinjuku',    ja:'南新宿',         num:'OH02', ward:'shibuya',   cumL:2,    tier:1, hw:6 },
      { id:'sangubashi',        en:'Sangūbashi',         ja:'参宮橋',         num:'OH03', ward:'shibuya',   cumL:3.5,  tier:1, hw:6 },
      { id:'yoyogihachiman',    en:'Yoyogi-Hachiman',    ja:'代々木八幡',     num:'OH04', ward:'shibuya',   cumL:5.5,  tier:1, hw:6 },
      { id:'yoyogiuehara',      en:'Yoyogi-Uehara',      ja:'代々木上原',     num:'OH05', ward:'shibuya',   cumL:7,    tier:3, hw:3, junction:true },
      { id:'higashikitazawa',   en:'Higashi-Kitazawa',   ja:'東北沢',         num:'OH06', ward:'setagaya',  cumL:9,    tier:1, hw:6 },
      { id:'shimokitazawa',     en:'Shimo-Kitazawa',     ja:'下北沢',         num:'OH07', ward:'setagaya',  cumL:11,   tier:3, hw:3, junction:true },
      { id:'setagayadaita',     en:'Setagaya-Daita',     ja:'世田谷代田',     num:'OH08', ward:'setagaya',  cumL:13,   tier:1, hw:6 },
      { id:'umegaoka',          en:'Umegaoka',           ja:'梅ヶ丘',         num:'OH09', ward:'setagaya',  cumL:14.5, tier:1, hw:6 },
      { id:'gotokuji',          en:'Gōtokuji',           ja:'豪徳寺',         num:'OH10', ward:'setagaya',  cumL:16,   tier:1, hw:6, junction:true },
      { id:'kyodo',             en:'Kyōdō',              ja:'経堂',           num:'OH11', ward:'setagaya',  cumL:18,   tier:2, hw:4 },
      { id:'chitosefunabashi',  en:'Chitose-Funabashi',  ja:'千歳船橋',       num:'OH12', ward:'setagaya',  cumL:20.5, tier:1, hw:6 },
      { id:'soshigayadaikura',  en:'Soshigaya-Ōkura',    ja:'祖師ヶ谷大蔵',   num:'OH13', ward:'setagaya',  cumL:22.5, tier:1, hw:6 },
      { id:'seijogakuenmae',    en:'Seijōgakuen-mae',    ja:'成城学園前',     num:'OH14', ward:'setagaya',  cumL:25,   tier:3, hw:3 },
      { id:'kitami',            en:'Kitami',             ja:'喜多見',         num:'OH15', ward:'setagaya',  cumL:27.5, tier:1, hw:6 },
      { id:'komae',             en:'Komae',              ja:'狛江',           num:'OH16', ward:'komae',     cumL:29.5, tier:1, hw:6 },
      { id:'izumitamagawa',     en:'Izumi-Tamagawa',     ja:'和泉多摩川',     num:'OH17', ward:'komae',     cumL:31,   tier:1, hw:6 },
      { id:'noborito',          en:'Noborito',           ja:'登戸',           num:'OH18', ward:'tama_ku',   cumL:33,   tier:3, hw:3, junction:true },
      { id:'mukogaokayuen',     en:'Mukōgaoka-yūen',     ja:'向ヶ丘遊園',     num:'OH19', ward:'tama_ku',   cumL:35,   tier:2, hw:4 },
      { id:'shinurigaoka',      en:'Shin-Yurigaoka',     ja:'新百合ヶ丘',     num:'OH23', ward:'asao_ku',   cumL:40,   tier:3, hw:3, junction:true },
      { id:'machida',           en:'Machida',            ja:'町田',           num:'OH27', ward:'machida',   cumL:48,   tier:3, hw:3, junction:true },
    ],
    anchors: [
      { id:'od_rapid', tier:'V', en:'Shinjuku → Machida in 29′ via Rapid Express (kaisoku-kyūkō)', ja:'快速急行で新宿〜町田29分', src:'Odakyu Electric Railway Timetable' },
      { id:'od_chiyoda', tier:'V', en:'Direct through-run onto Tokyo Metro Chiyoda Line at Yoyogi-Uehara', ja:'代々木上原から千代田線直通（大手町・霞ケ関直結）', src:'Tokyo Metro / Odakyu Through Run' },
    ],
    pockets: [
      { id:'pk_shimokitazawa', st:'shimokitazawa', ward:'setagaya',
        name:{en:'Shimokitazawa theater & vintage maze', ja:'下北沢・演劇と古着の路地'},
        gem:{en:'Epicenter of Tokyo indie theatre, live music venues, curated vintage apparel, and new sunken greenway parks.',
             ja:'小劇場、ライブハウス、古着屋が密集。小田急線地下化で誕生した緑道「リロード」が話題。'},
        noiseWatch:{en:'Noise watch: Weekend youth foot-traffic and evening livehouse spillover; residential blocks past the old rail trace turn silent after 22:30.',
                    ja:'騒音注意：週末昼間の若者歩行混雑とライブハウスの出入り。旧線路跡から離れた住宅街は夜間静寂。'},
        noiseSrc:'Setagaya Ward Cultural Promotion Blotter',
        ax:{quiet:2, old:3, intl:4, food:5, craft:5, green:3, night:5, refined:3, photo:5} },
      { id:'pk_gotokuji', st:'gotokuji', ward:'setagaya',
        name:{en:'Gōtokuji Lucky Cat Sanctuary', ja:'豪徳寺・招き猫の寺町'},
        gem:{en:'Thousands of white beckoning cats under temple cedars; quiet tramway transfer to the Setagaya retro line.',
             ja:'招き猫発祥の寺院の杜と、東急世田谷線のチンチン電車が走る穏やかな寺町。'},
        noiseWatch:{en:'Noise watch: Occasional tram bells and daytime temple visitors; nighttime is virtually silent (quiet 5/5).',
                    ja:'騒音注意：日中の参拝客と世田谷線の警報音。夜間は完全な静寂（夜間静けさ5/5）。'},
        noiseSrc:'Setagaya Heritage Registry',
        ax:{quiet:5, old:5, intl:3, food:3, craft:3, green:4, night:1, refined:3, photo:4} },
      { id:'pk_seijo', st:'seijogakuenmae', ward:'setagaya',
        name:{en:'Seijō Garden Bluffs', ja:'成城学園前・学園都市'},
        gem:{en:'Setagaya’s most prestigious residential garden enclave: cherry-tree avenues, weeping willows along the Nogawa, and strict architectural quietude.',
             ja:'厳しい建築協定で守られた邸宅街。野川の水辺と桜並木が織りなす圧倒的な品格。'},
        noiseWatch:{en:'Noise watch: Ultra-strict local residential noise covenants; zero commercial nighttime noise (quiet 5/5).',
                    ja:'騒音注意：成城憲章による厳格な住環境保護。商業騒音ゼロ（静けさ5/5）。'},
        noiseSrc:'Seijō Charter Neighborhood Council',
        ax:{quiet:5, old:4, intl:2, food:3, craft:2, green:5, night:1, refined:5, photo:4} },
    ],
    homes: [
      { id:'od_h01', st:'shimokitazawa', ward:'setagaya', name:{en:'Shimokita Reload Flat', ja:'下北沢リロードフラット'}, rent:115000, fee:8000, layout:'1K', size:27.0, walk:4, year:2021, tag:'LIVE', live:true, why:{en:'Steps from the new greenway park, concrete soundproof construction.', ja:'新緑道リロード至近、遮音性の高いRC造デザイナーズ。'} },
      { id:'od_h02', st:'gotokuji', ward:'setagaya', name:{en:'Gotokuji Cat Terrace', ja:'豪徳寺キャットテラス'}, rent:88000, fee:5000, layout:'1K', size:24.5, walk:3, year:2018, tag:'LIVE', live:true, why:{en:'Quiet temple alley, wood-deck terrace with peaceful garden view.', ja:'寺院の森を望むテラス付き、静穏そのものの住環境。'} },
      { id:'od_h03', st:'seijogakuenmae', ward:'setagaya', name:{en:'Seijo Green Villa', ja:'成城グリーンヴィラ'}, rent:135000, fee:9000, layout:'1LDK', size:38.2, walk:6, year:2019, tag:'LIVE', live:true, why:{en:'Located in prestigious Seijo 4-chome, sun-drenched south exposure.', ja:'成城4丁目の邸宅街、南向き日当たり良好な1LDK。'} },
      { id:'od_h04', st:'machida', ward:'machida', name:{en:'Machida Serigaya Residence', ja:'町田芹ヶ谷レジデンス'}, rent:65000, fee:4000, layout:'1K', size:23.0, walk:7, year:2017, tag:'LIVE', live:true, why:{en:'Near Serigaya sculpture park, 29 min direct rapid express to Shinjuku.', ja:'芹ヶ谷公園近く、快速急行で新宿へ29分直通。'} },
    ]
  }
};
